[package]
name = "pidfd"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
sched = { path = "../sched" }
vfs = { path = "../vfs" }

[dev-dependencies]
namespace-identity = { path = "../namespace-identity" }

[features]
default = []
hosted = ["sched/hosted"]
