[package]
name = "iommu"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
pci = { path = "../../drivers/pci" }
mmio-map = { path = "../mmio-map" }
firmware = { path = "../firmware" }
pmm = { path = "../mm-pmm" }
sync = { path = "../../shared/sync" }
klog = { path = "../../shared/klog" }
hal-x86_64 = { path = "../../arch/hal-x86_64" }
hal-aarch64 = { path = "../../arch/hal-aarch64" }

[features]
debug-boot = []

[lints]
workspace = true
