// Static userspace-binary lists for the rootfs build, extracted from rootfs.rs
// to keep it under the 1000-line cap (08§7). These are the kernel-acceptance
// smoke + dynamic-loader test sources compiled static-musl at rootfs build time.

/// `-static -no-pie` smoke/probe binaries: (out_rel, src_rel).
pub(crate) const CRT_BINS: &[(&str, &str)] = &[
    ("userspace/bare/bare3",                      "userspace/bare/bare3.c"),
    ("userspace/sem_smoke/sem_smoke",             "userspace/sem_smoke/sem_smoke.c"),
    ("userspace/msg_smoke/msg_smoke",             "userspace/msg_smoke/msg_smoke.c"),
    ("userspace/mq_smoke/mq_smoke",               "userspace/mq_smoke/mq_smoke.c"),
    ("userspace/ptrace_smoke/ptrace_smoke",       "userspace/ptrace_smoke/ptrace_smoke.c"),
    ("userspace/ptrace_singlestep_smoke/ptrace_singlestep_smoke",
                                                  "userspace/ptrace_singlestep_smoke/ptrace_singlestep_smoke.c"),
    ("userspace/mprotect_smoke/mprotect_smoke",   "userspace/mprotect_smoke/mprotect_smoke.c"),
    ("userspace/mremap_dontunmap_smoke/mremap_dontunmap_smoke",
                                                  "userspace/mremap_dontunmap_smoke/mremap_dontunmap_smoke.c"),
    ("userspace/inet6_smoke/inet6_smoke",         "userspace/inet6_smoke/inet6_smoke.c"),
    ("userspace/mmsg_smoke/mmsg_smoke",           "userspace/mmsg_smoke/mmsg_smoke.c"),
    ("userspace/scm_smoke/scm_smoke",             "userspace/scm_smoke/scm_smoke.c"),
    ("userspace/cgroup_smoke/cgroup_smoke",       "userspace/cgroup_smoke/cgroup_smoke.c"),
    ("userspace/cmdsubst_probe/cmdsubst_probe",   "userspace/cmdsubst_probe/cmdsubst_probe.c"),
    ("userspace/alarm_probe/alarm_probe",         "userspace/alarm_probe/alarm_probe.c"),
    ("userspace/sigframe_probe/sigframe_probe",   "userspace/sigframe_probe/sigframe_probe.c"),
    ("userspace/symlink_probe/symlink_probe",     "userspace/symlink_probe/symlink_probe.c"),
    ("userspace/mount_smoke/mount_smoke",         "userspace/mount_smoke/mount_smoke.c"),
    ("userspace/statfs_smoke/statfs_smoke",       "userspace/statfs_smoke/statfs_smoke.c"),
    ("userspace/fsmount_probe/fsmount_probe",     "userspace/fsmount_probe/fsmount_probe.c"),
    ("userspace/memfd_seal_probe/memfd_seal_probe", "userspace/memfd_seal_probe/memfd_seal_probe.c"),
    ("userspace/uevent_probe/uevent_probe",       "userspace/uevent_probe/uevent_probe.c"),
    ("userspace/rtlink_probe/rtlink_probe",       "userspace/rtlink_probe/rtlink_probe.c"),
    ("userspace/dev_smoke/dev_smoke",             "userspace/dev_smoke/dev_smoke.c"),
    ("userspace/mmap_zero_smoke/mmap_zero_smoke", "userspace/mmap_zero_smoke/mmap_zero_smoke.c"),
    ("userspace/mmchurn_smoke/mmchurn_smoke",     "userspace/mmchurn_smoke/mmchurn_smoke.c"),
    ("userspace/mallocstress_smoke/mallocstress_smoke", "userspace/mallocstress_smoke/mallocstress_smoke.c"),
    ("userspace/sigmalloc_smoke/sigmalloc_smoke", "userspace/sigmalloc_smoke/sigmalloc_smoke.c"),
    ("userspace/rawecho_smoke/rawecho_smoke", "userspace/rawecho_smoke/rawecho_smoke.c"),
    ("userspace/termios_rt_smoke/termios_rt_smoke", "userspace/termios_rt_smoke/termios_rt_smoke.c"),
    ("userspace/isatty_smoke/isatty_smoke", "userspace/isatty_smoke/isatty_smoke.c"),
    ("userspace/pollecho_smoke/pollecho_smoke", "userspace/pollecho_smoke/pollecho_smoke.c"),
    ("userspace/mremap_alias_smoke/mremap_alias_smoke", "userspace/mremap_alias_smoke/mremap_alias_smoke.c"),
    ("userspace/usleep_smoke/usleep_smoke",       "userspace/usleep_smoke/usleep_smoke.c"),
    ("userspace/af_packet_smoke/af_packet_smoke", "userspace/af_packet_smoke/af_packet_smoke.c"),
    ("userspace/online_smoke/online_smoke",       "userspace/online_smoke/online_smoke.c"),
    ("userspace/tcp_smoke/tcp_smoke",             "userspace/tcp_smoke/tcp_smoke.c"),
    ("userspace/exit_test/exit_test",             "userspace/exit_test/exit_test.c"),
    ("userspace/socketpair_fork_probe/socketpair_fork_probe",
                                                  "userspace/socketpair_fork_probe/socketpair_fork_probe.c"),
    ("userspace/vim_smoke/vim_smoke",             "userspace/vim_smoke/vim_smoke.c"),
    ("userspace/tty_reset_probe/tty_reset_probe", "userspace/tty_reset_probe/tty_reset_probe.c"),
    ("userspace/dsr_probe/dsr_probe",             "userspace/dsr_probe/dsr_probe.c"),
    ("userspace/vtswitch_probe/vtswitch_probe",   "userspace/vtswitch_probe/vtswitch_probe.c"),
    ("userspace/vtmode_probe/vtmode_probe",       "userspace/vtmode_probe/vtmode_probe.c"),
    ("userspace/vtresize_probe/vtresize_probe",   "userspace/vtresize_probe/vtresize_probe.c"),
    ("userspace/kdfont_probe/kdfont_probe",       "userspace/kdfont_probe/kdfont_probe.c"),
    ("userspace/fbdev_probe/fbdev_probe",         "userspace/fbdev_probe/fbdev_probe.c"),
    ("userspace/vcs_probe/vcs_probe",             "userspace/vcs_probe/vcs_probe.c"),
    ("userspace/ptyhup_probe/ptyhup_probe",       "userspace/ptyhup_probe/ptyhup_probe.c"),
];
