//! Module manifest: ordinary hosted compilation of target-adapter policy contracts.
#[path = "nt_window/caret.rs"]
pub(crate) mod nt_caret_contract;
#[path = "nt_window/redraw.rs"]
pub(crate) mod nt_redraw_contract;
#[path = "nt_wine_window/pfn.rs"]
pub(crate) mod nt_wine_pfn_contract;
#[path = "nt_wine_window/placement.rs"]
pub(crate) mod nt_wine_placement_contract;
#[path = "nt_wine_window/position.rs"]
pub(crate) mod nt_wine_position_contract;
#[path = "nt_wine_window/gdi_raw.rs"]
pub(crate) mod nt_wine_gdi_contract;
#[path = "nt_window/control_color.rs"]
pub(crate) mod nt_control_color_contract;
#[path = "nt_wine_window/raw_args.rs"]
pub(crate) mod nt_wine_raw_args_contract;
#[path = "nt_window/send/work.rs"]
pub(crate) mod nt_window_send_contract;
#[path = "nt_wine_window/bitmap_raw.rs"]
pub(crate) mod nt_wine_bitmap_contract;
#[path = "nt_wine_window/brush_raw.rs"]
pub(crate) mod nt_wine_brush_contract;
#[path = "nt_wine_window/hwnd_param.rs"]
pub(crate) mod nt_wine_hwnd_param_contract;
#[path = "nt_wine_window/hwnd_call.rs"]
pub(crate) mod nt_wine_hwnd_call_contract;
#[path = "nt_wine_window/msg_filter.rs"]
pub(crate) mod nt_wine_msg_filter_contract;
#[path = "nt_wine_window/two_param.rs"]
pub(crate) mod nt_wine_two_param_contract;
#[path = "nt_wine_window/accel_raw.rs"]
pub(crate) mod nt_wine_accel_contract;
#[path = "nt_wine_window/dpi_context.rs"]
pub(crate) mod nt_wine_dpi_context_contract;
#[path = "nt_wine_window/builtin_classes.rs"]
pub(crate) mod nt_wine_builtin_classes_contract;
#[path = "nt_wine_window/unclaimed.rs"]
pub(crate) mod nt_wine_unclaimed_contract;
#[path = "nt_wine_window/long_raw.rs"]
pub(crate) mod nt_wine_long_contract;
#[path = "nt_wine_window/clip_raw.rs"]
pub(crate) mod nt_wine_clip_contract;
#[path = "nt_window/rect_query/policy.rs"]
pub(crate) mod nt_window_rect_contract;
#[path = "nt_gdi/lifecycle/transaction.rs"]
pub(crate) mod nt_gdi_transaction_contract;
#[path = "nt_gdi/object_query/transfer.rs"]
pub(crate) mod nt_gdi_object_transfer_contract;
#[path = "nt_wine_window/gdi_route.rs"]
pub(crate) mod nt_wine_gdi_route_contract;
#[path = "nt_window/bridge.rs"]
pub(crate) mod nt_window_bridge_contract;
#[path = "nt_rtl/wndproc_payload.rs"]
pub(crate) mod nt_wndproc_payload_contract;
#[path = "nt_window/scroll.rs"]
pub(crate) mod nt_scroll_contract;
#[path = "028_madvise.rs"]
pub(crate) mod s028_madvise;
