//! Module manifest: ordinary hosted compilation of target-adapter policy contracts.
#[path = "nt_window/caret.rs"]
pub(crate) mod nt_caret_contract;
#[path = "nt_window/redraw.rs"]
pub(crate) mod nt_redraw_contract;
#[path = "nt_wine_window/pfn.rs"]
pub(crate) mod nt_wine_pfn_contract;
#[path = "nt_wine_window/placement.rs"]
pub(crate) mod nt_wine_placement_contract;
#[path = "nt_wine_window/position.rs"]
pub(crate) mod nt_wine_position_contract;
#[path = "nt_wine_window/gdi_raw.rs"]
pub(crate) mod nt_wine_gdi_contract;
#[path = "nt_window/control_color.rs"]
pub(crate) mod nt_control_color_contract;
#[path = "nt_wine_window/raw_args.rs"]
pub(crate) mod nt_wine_raw_args_contract;
#[path = "nt_wine_window/chain.rs"]
pub(crate) mod nt_wine_chain_contract;
#[path = "nt_wine_window/raw_gather.rs"]
pub(crate) mod nt_wine_raw_gather_contract;

#[path = "nt_wine_window/queue_raw.rs"]
pub(crate) mod nt_wine_queue_contract;
#[path = "nt_window/timer/raw.rs"]
pub(crate) mod nt_window_timer_contract;
#[path = "nt_window/update_region/raw.rs"]
pub(crate) mod nt_window_update_region_contract;
#[path = "nt_window/caption/raw.rs"]
pub(crate) mod nt_window_caption_contract;
#[path = "nt_window/sys_colors/raw.rs"]
pub(crate) mod nt_window_sys_colors_contract;
#[path = "nt_window/scroll/bar_raw.rs"]
pub(crate) mod nt_window_scroll_bar_contract;
#[path = "nt_window/scroll/dc_raw.rs"]
pub(crate) mod nt_window_scroll_dc_contract;
#[path = "nt_window/menu_raw/raw.rs"]
pub(crate) mod nt_window_menu_contract;
#[path = "nt_window/menu_raw/session.rs"]
pub(crate) mod nt_window_menu_session_contract;
#[path = "nt_window/menu_raw/popup_proc.rs"]
pub(crate) mod nt_window_menu_popup_proc_contract;
#[path = "nt_window/display/raw.rs"]
pub(crate) mod nt_window_display_contract;
#[path = "nt_window/display/devmode.rs"]
pub(crate) mod nt_window_devmode_contract;
#[path = "nt_window/send/work.rs"]
pub(crate) mod nt_window_send_contract;
#[path = "nt_wine_window/bitmap_raw.rs"]
pub(crate) mod nt_wine_bitmap_contract;
#[path = "nt_wine_window/device_caps.rs"]
pub(crate) mod nt_wine_device_caps_contract;
#[path = "nt_wine_window/input_context.rs"]
pub(crate) mod nt_wine_input_context_contract;
#[path = "nt_wine_window/query_window.rs"]
pub(crate) mod nt_wine_query_window_contract;
#[path = "nt_wine_window/brush_raw.rs"]
pub(crate) mod nt_wine_brush_contract;
#[path = "nt_wine_window/hwnd_param.rs"]
pub(crate) mod nt_wine_hwnd_param_contract;
#[path = "nt_wine_window/hwnd_call.rs"]
pub(crate) mod nt_wine_hwnd_call_contract;
#[path = "nt_wine_window/msg_filter.rs"]
pub(crate) mod nt_wine_msg_filter_contract;
#[path = "nt_wine_window/two_param.rs"]
pub(crate) mod nt_wine_two_param_contract;
#[path = "nt_wine_window/accel_raw.rs"]
pub(crate) mod nt_wine_accel_contract;
#[path = "nt_wine_window/dpi_context.rs"]
pub(crate) mod nt_wine_dpi_context_contract;
#[path = "nt_wine_window/builtin_classes.rs"]
pub(crate) mod nt_wine_builtin_classes_contract;
#[path = "nt_wine_window/clipboard_raw.rs"]
pub(crate) mod nt_wine_clipboard_contract;
#[path = "nt_wine_window/atom_raw.rs"]
pub(crate) mod nt_wine_atom_contract;
#[path = "nt_wine_window/hook_raw.rs"]
pub(crate) mod nt_wine_hook_contract;
#[path = "nt_wine_window/window_raw.rs"]
pub(crate) mod nt_wine_window_family_contract;
#[path = "nt_wine_window/station_raw.rs"]
pub(crate) mod nt_wine_station_contract;
#[path = "nt_wine_window/unclaimed.rs"]
pub(crate) mod nt_wine_unclaimed_contract;
#[path = "nt_wine_window/long_raw.rs"]
pub(crate) mod nt_wine_long_contract;
#[path = "nt_wine_window/class_raw.rs"]
pub(crate) mod nt_wine_class_long_contract;
#[path = "nt_wine_window/cursor_raw.rs"]
pub(crate) mod nt_wine_cursor_contract;
#[path = "nt_wine_window/cursor_icon_raw.rs"]
pub(crate) mod nt_wine_cursor_icon_contract;
#[path = "nt_wine_window/input_raw.rs"]
pub(crate) mod nt_wine_input_contract;
#[path = "nt_wine_window/drag_raw.rs"]
pub(crate) mod nt_wine_drag_contract;
#[path = "nt_wine_window/draw_icon_raw.rs"]
pub(crate) mod nt_wine_draw_icon_contract;
#[path = "nt_wine_window/keyboard_raw.rs"]
pub(crate) mod nt_wine_keyboard_contract;
#[path = "nt_wine_window/rawinput_raw.rs"]
pub(crate) mod nt_wine_rawinput_contract;
#[path = "nt_wine_window/clip_raw.rs"]
pub(crate) mod nt_wine_clip_contract;
#[path = "nt_window/rect_query/policy.rs"]
pub(crate) mod nt_window_rect_contract;
#[path = "nt_gdi/lifecycle/transaction.rs"]
pub(crate) mod nt_gdi_transaction_contract;
#[path = "nt_gdi/object_query/transfer.rs"]
pub(crate) mod nt_gdi_object_transfer_contract;
#[path = "nt_wine_window/gdi_route.rs"]
pub(crate) mod nt_wine_gdi_route_contract;
#[path = "nt_window/geom_trace.rs"]
pub(crate) mod geom_trace;
#[path = "nt_window/bridge.rs"]
pub(crate) mod nt_window_bridge_contract;
#[path = "nt_rtl/wndproc_payload.rs"]
pub(crate) mod nt_wndproc_payload_contract;
#[path = "nt_window/scroll.rs"]
pub(crate) mod nt_scroll_contract;
#[path = "028_madvise.rs"]
pub(crate) mod s028_madvise;
#[path = "nt_window/hosted_policy.rs"]
pub(crate) mod nt_window;
