use syscall::errno::Errno;

/// Map a network work-function error to a negated Linux syscall errno. # C: O(1)
pub(crate) fn errno_from_neterr(error: net::NetError) -> i64 {
    -(match error {
        net::NetError::Eaddrinuse => Errno::Eaddrinuse,
        net::NetError::Eaddrnotavail => Errno::Eaddrnotavail,
        net::NetError::Edestaddrreq => Errno::Edestaddrreq,
        net::NetError::Emsgsize => Errno::Emsgsize,
        net::NetError::Enobufs => Errno::Enobufs,
        net::NetError::Enomem => Errno::Enomem,
        net::NetError::Enetunreach => Errno::Enetunreach,
        net::NetError::Ehostunreach => Errno::Ehostunreach,
        net::NetError::Eacces => Errno::Eacces,
        net::NetError::Enonet => Errno::Enonet,
        net::NetError::Enoprotoopt => Errno::Enoprotoopt,
        net::NetError::Eopnotsupp => Errno::Eopnotsupp,
        net::NetError::Eproto => Errno::Eproto,
        net::NetError::Ehostdown => Errno::Ehostdown,
        net::NetError::Enodev => Errno::Enodev,
        net::NetError::Enetdown => Errno::Enetdown,
        net::NetError::Einval => Errno::Einval,
        net::NetError::Eio => Errno::Eio,
        net::NetError::Eagain => Errno::Eagain,
        net::NetError::Eafnosupport => Errno::Eafnosupport,
        net::NetError::Eisconn => Errno::Eisconn,
        net::NetError::Ealready => Errno::Ealready,
        net::NetError::Ebusy => Errno::Ebusy,
        net::NetError::Enospc => Errno::Enospc,
        net::NetError::Eperm => Errno::Eperm,
        net::NetError::Einprogress => Errno::Einprogress,
        net::NetError::Enotconn => Errno::Enotconn,
        net::NetError::Erange => Errno::Erange,
        net::NetError::Econnrefused => Errno::Econnrefused,
        net::NetError::Econnreset => Errno::Econnreset,
        net::NetError::Etimedout => Errno::Etimedout,
        net::NetError::Epipe => Errno::Epipe,
        net::NetError::Enoent => Errno::Enoent,
        net::NetError::Eintr => Errno::Eintr,
    } as i32 as i64)
}
