//! NT status to Win32 error translation, shared by the two native entries
//! that differ only in whether they record the status on the thread block.

#[cfg(test)]
#[path = "nt_status_dos/tests.rs"]
mod tests;

/// Customer-defined statuses pass through untranslated.
const CUSTOMER_BIT: u32 = 0x2000_0000;
/// Severity nibble that normalizes onto the error severity.
const SEVERITY_MASK: u32 = 0xf000_0000;
const SEVERITY_ALTERNATE: u32 = 0xd000_0000;
const SEVERITY_NORMALIZE: u32 = 0x1000_0000;
const LOW_WORD_MASK: u32 = 0xffff;
/// Facilities whose low word is already the Win32 error.
const FACILITY_NTWIN32: u32 = 0xc001;
const FACILITY_WIN32_WARNING: u32 = 0x8007;
const FACILITY_WIN32_ERROR: u32 = 0xc007;

const ERROR_INVALID_FUNCTION: u32 = 1;
const ERROR_FILE_NOT_FOUND: u32 = 2;
const ERROR_PATH_NOT_FOUND: u32 = 3;
const ERROR_ACCESS_DENIED: u32 = 5;
const ERROR_INVALID_HANDLE: u32 = 6;
const ERROR_NOT_ENOUGH_MEMORY: u32 = 8;
const ERROR_SHARING_VIOLATION: u32 = 32;
const ERROR_LOCK_VIOLATION: u32 = 33;
const ERROR_HANDLE_EOF: u32 = 38;
const ERROR_NOT_SUPPORTED: u32 = 50;
const ERROR_UNEXP_NET_ERR: u32 = 59;
const ERROR_INVALID_PARAMETER: u32 = 87;
const ERROR_SEM_TIMEOUT: u32 = 121;
const ERROR_INSUFFICIENT_BUFFER: u32 = 122;
const ERROR_INVALID_NAME: u32 = 123;
const ERROR_ALREADY_EXISTS: u32 = 183;
const ERROR_BAD_EXE_FORMAT: u32 = 193;
const ERROR_FILENAME_EXCED_RANGE: u32 = 206;
const ERROR_MORE_DATA: u32 = 234;
const ERROR_NO_MORE_ITEMS: u32 = 259;
const ERROR_DIRECTORY: u32 = 267;
const ERROR_MR_MID_NOT_FOUND: u32 = 317;
const ERROR_OPERATION_ABORTED: u32 = 995;
const ERROR_IO_PENDING: u32 = 997;
const ERROR_NOACCESS: u32 = 998;
const ERROR_FILE_CORRUPT: u32 = 1392;
const ERROR_NO_SYSTEM_RESOURCES: u32 = 1450;
const ERROR_TIMEOUT: u32 = 1460;
const ERROR_NOT_A_REPARSE_POINT: u32 = 4390;

const STATUS_TIMEOUT: u32 = 0x0000_0102;
const STATUS_PENDING: u32 = 0x0000_0103;
const STATUS_BUFFER_OVERFLOW: u32 = 0x8000_0005;
const STATUS_NO_MORE_ENTRIES: u32 = 0x8000_001a;
const STATUS_NOT_IMPLEMENTED: u32 = 0xc000_0002;
const STATUS_ACCESS_VIOLATION: u32 = 0xc000_0005;
const STATUS_INVALID_HANDLE: u32 = 0xc000_0008;
const STATUS_INVALID_PARAMETER: u32 = 0xc000_000d;
const STATUS_NO_SUCH_FILE: u32 = 0xc000_000f;
const STATUS_END_OF_FILE: u32 = 0xc000_0011;
const STATUS_NO_MEMORY: u32 = 0xc000_0017;
const STATUS_ACCESS_DENIED: u32 = 0xc000_0022;
const STATUS_BUFFER_TOO_SMALL: u32 = 0xc000_0023;
const STATUS_OBJECT_NAME_INVALID: u32 = 0xc000_0033;
const STATUS_OBJECT_NAME_NOT_FOUND: u32 = 0xc000_0034;
const STATUS_OBJECT_NAME_COLLISION: u32 = 0xc000_0035;
const STATUS_OBJECT_PATH_NOT_FOUND: u32 = 0xc000_003a;
const STATUS_SHARING_VIOLATION: u32 = 0xc000_0043;
const STATUS_FILE_LOCK_CONFLICT: u32 = 0xc000_0054;
const STATUS_INVALID_IMAGE_FORMAT: u32 = 0xc000_007b;
const STATUS_INSUFFICIENT_RESOURCES: u32 = 0xc000_009a;
const STATUS_IO_TIMEOUT: u32 = 0xc000_00b5;
const STATUS_NOT_SUPPORTED: u32 = 0xc000_00bb;
const STATUS_FILE_CORRUPT_ERROR: u32 = 0xc000_0102;
const STATUS_NOT_A_DIRECTORY: u32 = 0xc000_0103;
const STATUS_NAME_TOO_LONG: u32 = 0xc000_0106;
const STATUS_MESSAGE_NOT_FOUND: u32 = 0xc000_0109;
const STATUS_CANCELLED: u32 = 0xc000_0120;
const STATUS_CANNOT_DELETE: u32 = 0xc000_0121;
const STATUS_INVALID_ADDRESS: u32 = 0xc000_0141;
const STATUS_NOT_A_REPARSE_POINT: u32 = 0xc000_0275;

/// Translate one NT status. Success and customer statuses pass through, the
/// alternate severity normalizes onto the error severity, the facilities that
/// already carry a Win32 error answer with their low word, and a status the
/// table does not name answers the message-not-found error.
/// # C: O(1)
pub(crate) fn nt_status_to_dos_error(status: u32) -> u32 {
    if status == 0 || status & CUSTOMER_BIT != 0 { return status; }
    let status = if status & SEVERITY_MASK == SEVERITY_ALTERNATE { status & !SEVERITY_NORMALIZE } else { status };
    let facility = status >> 16;
    if facility == FACILITY_NTWIN32 || facility == FACILITY_WIN32_WARNING || facility == FACILITY_WIN32_ERROR { return status & LOW_WORD_MASK; }
    match status {
        STATUS_TIMEOUT => ERROR_TIMEOUT,
        STATUS_PENDING => ERROR_IO_PENDING,
        STATUS_BUFFER_OVERFLOW => ERROR_MORE_DATA,
        STATUS_NO_MORE_ENTRIES => ERROR_NO_MORE_ITEMS,
        STATUS_NOT_IMPLEMENTED => ERROR_INVALID_FUNCTION,
        STATUS_ACCESS_VIOLATION => ERROR_NOACCESS,
        STATUS_INVALID_HANDLE => ERROR_INVALID_HANDLE,
        STATUS_INVALID_PARAMETER => ERROR_INVALID_PARAMETER,
        STATUS_NO_SUCH_FILE | STATUS_OBJECT_NAME_NOT_FOUND => ERROR_FILE_NOT_FOUND,
        STATUS_END_OF_FILE => ERROR_HANDLE_EOF,
        STATUS_NO_MEMORY => ERROR_NOT_ENOUGH_MEMORY,
        STATUS_ACCESS_DENIED | STATUS_CANNOT_DELETE => ERROR_ACCESS_DENIED,
        STATUS_BUFFER_TOO_SMALL => ERROR_INSUFFICIENT_BUFFER,
        STATUS_OBJECT_NAME_INVALID => ERROR_INVALID_NAME,
        STATUS_OBJECT_NAME_COLLISION => ERROR_ALREADY_EXISTS,
        STATUS_OBJECT_PATH_NOT_FOUND => ERROR_PATH_NOT_FOUND,
        STATUS_SHARING_VIOLATION => ERROR_SHARING_VIOLATION,
        STATUS_FILE_LOCK_CONFLICT => ERROR_LOCK_VIOLATION,
        STATUS_INVALID_IMAGE_FORMAT => ERROR_BAD_EXE_FORMAT,
        STATUS_INSUFFICIENT_RESOURCES => ERROR_NO_SYSTEM_RESOURCES,
        STATUS_IO_TIMEOUT => ERROR_SEM_TIMEOUT,
        STATUS_NOT_SUPPORTED => ERROR_NOT_SUPPORTED,
        STATUS_FILE_CORRUPT_ERROR => ERROR_FILE_CORRUPT,
        STATUS_NOT_A_DIRECTORY => ERROR_DIRECTORY,
        STATUS_NAME_TOO_LONG => ERROR_FILENAME_EXCED_RANGE,
        STATUS_MESSAGE_NOT_FOUND => ERROR_MR_MID_NOT_FOUND,
        STATUS_CANCELLED => ERROR_OPERATION_ABORTED,
        STATUS_INVALID_ADDRESS => ERROR_UNEXP_NET_ERR,
        STATUS_NOT_A_REPARSE_POINT => ERROR_NOT_A_REPARSE_POINT,
        _ => ERROR_MR_MID_NOT_FOUND,
    }
}
