[package]
name = "overlayfs"
version = "0.1.0"
edition = "2021"
publish = false
[lib]
path = "src/lib.rs"
[dependencies]
sync    = { path = "../../shared/sync" }
syscall = { path = "../syscall" }
klog    = { path = "../../shared/klog" }
vfs     = { path = "../vfs" }
sched   = { path = "../sched", features = ["hosted"] }

[features]
default = []
hosted = []

[lints]
workspace = true
