[package]
name = "drv-serial"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
drv            = { path = "../drv" }
# 16550 is the x86 + host-fallback backend, so it's a plain dependency.
drv-uart-16550 = { path = "../drv-uart-16550" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
drv-uart-pl011 = { path = "../drv-uart-pl011" }
