[package]
name = "windows-runtime"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "windows-runtime"
path = "src/main.rs"

[dependencies]
libc = { workspace = true }
elf = { path = "../../../crates/shared/elf" }
pe = { path = "../../../crates/shared/pe" }
syscall = { path = "../../../crates/kernel/syscall" }
windows-gdi = { path = "../windows-gdi" }

[dev-dependencies]
ipc = { path = "../../../crates/kernel/ipc" }
