[package]
name = "console"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
klog       = { path = "../../shared/klog" }
kmacros    = { path = "../../shared/kmacros" }
vfs        = { path = "../vfs" }
tty        = { path = "../tty" }
devfs      = { path = "../devfs" }
sched      = { path = "../sched" }
serialtty  = { path = "../serialtty" }
drv-serial = { path = "../../drivers/drv-serial" }
fbcon      = { path = "../../drivers/fbcon" }

[features]
debug-trace = ["kmacros/debug-trace"]
