/// `25§3` network result error.
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum NetError {
    Eagain,
    Eio,
    Einval,
    Enobufs,
    Enomem,
    Eaddrnotavail,
    Edestaddrreq,
    Emsgsize,
    Eaddrinuse,
    Enodev,
    Enetdown,
    Enetunreach,
    Ehostunreach,
    Eacces,
    Enonet,
    Enoprotoopt,
    Eopnotsupp,
    Esocktnosupport,
    Eproto,
    Ehostdown,
    Eafnosupport,
    Eisconn,
    Ealready,
    Ebusy,
    Enospc,
    Eperm,
    Einprogress,
    Enotconn,
    Erange,
    Econnrefused,
    Econnaborted,
    Econnreset,
    Etimedout,
    Epipe,
    Enoent,
    Eintr,
}

pub type NetResult<T> = core::result::Result<T, NetError>;
