[package]
name = "procfs"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
hal  = { path = "../../arch/hal" }
klog = { path = "../../shared/klog" }
sync = { path = "../../shared/sync" }
pmm  = { path = "../mm-pmm" }
cpu  = { path = "../cpu" }
block = { path = "../block" }
arch-irq = { path = "../arch-irq" }
vfs  = { path = "../vfs" }
net  = { path = "../net" }
modules = { path = "../modules" }
sched = { path = "../sched" }
vmm   = { path = "../mm-vmm" }
devfs = { path = "../devfs" }
kernfs = { path = "../kernfs" }
nscg  = { path = "../nscg" }
network-namespace = { path = "../network-namespace" }
namespace-identity = { path = "../namespace-identity" }
sysfs = { path = "../sysfs" }
cgroup = { path = "../cgroup" }
slab = { path = "../../shared/slab" }
kmacros = { path = "../../shared/kmacros" }

[features]
debug-cgroup = []  # [PROCCG]/[OPENCG-adjacent] /proc/<pid>/cgroup read trace
debug-mnt = []  # [MNTINFO] /proc mountinfo reader namespace/projection trace
default = []
hosted  = []

[target.'cfg(target_arch = "x86_64")'.dependencies]
hal-x86_64 = { path = "../../arch/hal-x86_64" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
hal-aarch64 = { path = "../../arch/hal-aarch64" }
