[package]
name = "socket"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
hal     = { path = "../../arch/hal" }
netlink = { path = "../netlink" }
nscg    = { path = "../nscg" }
network-namespace = { path = "../network-namespace" }
sched   = { path = "../sched" }
vfs     = { path = "../vfs" }

[target.'cfg(not(target_os = "oxide-kernel"))'.dependencies]
net = { path = "../net", features = ["hosted"] }

[target.'cfg(target_os = "oxide-kernel")'.dependencies]
net = { path = "../net" }

[target.'cfg(all(target_os = "oxide-kernel", target_arch = "x86_64"))'.dependencies]
hal-x86_64 = { path = "../../arch/hal-x86_64" }

[target.'cfg(all(target_os = "oxide-kernel", target_arch = "aarch64"))'.dependencies]
hal-aarch64 = { path = "../../arch/hal-aarch64" }
