[package]
name = "selinux-runtime"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
audit   = { path = "../audit" }
cmdline = { path = "../cmdline" }
klog    = { path = "../../shared/klog" }
selinux = { path = "../selinux" }
sync    = { path = "../../shared/sync" }

[lints]
workspace = true
