[package]
name = "drv-virtio-fs"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
hal     = { path = "../../arch/hal" }
iommu   = { path = "../../kernel/iommu" }
pci     = { path = "../../drivers/pci" }
virtio  = { path = "../../drivers/virtio" }
sync    = { path = "../../shared/sync" }
pmm     = { path = "../../kernel/mm-pmm" }
fuse-transport = { path = "../../shared/fuse-transport" }
sched   = { path = "../../kernel/sched" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
hal-x86_64 = { path = "../../arch/hal-x86_64" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
hal-aarch64 = { path = "../../arch/hal-aarch64" }

[features]
default = []

[lints]
workspace = true
