[package]
name = "sysfs"
version = "0.1.0"
edition = "2021"
publish = false
[lib]
path = "src/lib.rs"
[dependencies]
vfs    = { path = "../vfs" }
kernfs = { path = "../kernfs" }
sync   = { path = "../../shared/sync" }
net   = { path = "../net" }
block = { path = "../block" }
netlink = { path = "../netlink" }
network-namespace = { path = "../network-namespace" }
drv   = { path = "../../drivers/drv" }
modules = { path = "../modules" }
firmware = { path = "../firmware" }
klog = { path = "../../shared/klog" }
hal  = { path = "../../arch/hal" }
drv-zram = { path = "../../drivers/drv-zram" }
sched = { path = "../sched" }
cmdline = { path = "../cmdline" }

[dev-dependencies]
drv-zram = { path = "../../drivers/drv-zram", features = ["hosted"] }

[features]
default = []
hosted = ["modules/hosted"]
debug-udevdb = []
debug-zram = []
debug-zram-lifecycle = ["drv-zram/debug-zram-lifecycle"]
