[package]
name = "security"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
cgroup  = { path = "../../kernel/cgroup" }
crng    = { path = "../../kernel/crng" }
hal     = { path = "../../arch/hal" }
klog    = { path = "../../shared/klog" }
cmdline = { path = "../cmdline" }
lsm-framework = { package = "lsm", path = "../lsm" }
kernfs  = { path = "../../kernel/kernfs" }
namespace-identity = { path = "../../kernel/namespace-identity" }
nscg    = { path = "../../kernel/nscg" }
pmm     = { path = "../../kernel/mm-pmm" }
sched   = { path = "../../kernel/sched" }
selinux-runtime = { path = "../../kernel/selinux-runtime" }
sync    = { path = "../../shared/sync" }
syscall = { path = "../../kernel/syscall" }
uaccess = { path = "../../kernel/uaccess" }
vfs     = { path = "../../kernel/vfs" }

[dev-dependencies]
selinux = { path = "../selinux", features = ["test-policy"] }

[lints]
workspace = true
