#![cfg(target_os = "oxide-kernel")]

use syscall::SyscallArgs;

pub(super) fn dispatch_route_b(nr: u64, args: &SyscallArgs) -> Option<i64> {
    Some(match nr {
        syscall::nrs::NR_FSOPEN => crate::s430_fsopen::sys_fsopen(args),
        syscall::nrs::NR_FSCONFIG => crate::s431_fsconfig::sys_fsconfig(args),
        syscall::nrs::NR_FSMOUNT => crate::s432_fsmount::sys_fsmount(args),
        syscall::nrs::NR_MOVE_MOUNT => crate::s429_move_mount::sys_move_mount(args),
        syscall::nrs::NR_FSPICK => crate::s433_fspick::sys_fspick(args),
        syscall::nrs::NR_OPEN_TREE => crate::s428_open_tree::sys_open_tree(args),
        syscall::nrs::NR_MOUNT_SETATTR => crate::s442_mount_setattr::sys_mount_setattr(args),
        syscall::nrs::NR_GETRLIMIT => crate::s097_getrlimit::sys_getrlimit(args),
        syscall::nrs::NR_SETRLIMIT => crate::s160_setrlimit::sys_setrlimit(args),
        syscall::nrs::NR_GETRUSAGE => crate::s098_getrusage::sys_getrusage(args),
        syscall::nrs::NR_TIMES => crate::s100_times::sys_times(args),
        syscall::nrs::NR_SYSINFO => crate::s099_sysinfo::sys_sysinfo(args),
        syscall::nrs::NR_MREMAP => crate::s025_mremap::sys_mremap(args),
        syscall::nrs::NR_MSYNC => crate::s026_msync::sys_msync(args),
        syscall::nrs::NR_MINCORE => crate::s027_mincore::sys_mincore(args),
        syscall::nrs::NR_MLOCK => crate::s149_mlock_family::sys_mlock(args),
        syscall::nrs::NR_MUNLOCK => crate::s149_mlock_family::sys_munlock(args),
        syscall::nrs::NR_MLOCKALL => crate::s149_mlock_family::sys_mlockall(args),
        syscall::nrs::NR_MUNLOCKALL => crate::s149_mlock_family::sys_munlockall(args),
        syscall::nrs::NR_GETPGRP => crate::s111_getpgrp::sys_getpgrp(args),
        syscall::nrs::NR_GETPRIORITY => crate::proc::sys_getpriority(args),
        syscall::nrs::NR_SETPRIORITY => crate::proc::sys_setpriority(args),
        syscall::nrs::NR_ALARM => crate::s037_alarm::sys_alarm(args),
        syscall::nrs::NR_PAUSE => crate::s034_pause::sys_pause(args),
        syscall::nrs::NR_GETITIMER => crate::s036_getitimer::sys_getitimer(args),
        syscall::nrs::NR_SETITIMER => crate::s038_setitimer::sys_setitimer(args),
        syscall::nrs::NR_PIDFD_OPEN => crate::s434_pidfd_open::sys_pidfd_open(args),
        syscall::nrs::NR_PIDFD_GETFD => crate::s438_pidfd_getfd::sys_pidfd_getfd(args),
        syscall::nrs::NR_PIDFD_SEND_SIGNAL => crate::s424_pidfd_send_signal::sys_pidfd_send_signal(args),
        syscall::nrs::NR_INOTIFY_INIT => ::fs::inotify::sys_inotify_init(args),
        syscall::nrs::NR_INOTIFY_INIT1 => ::fs::inotify::sys_inotify_init1(args),
        syscall::nrs::NR_INOTIFY_ADD_WATCH => ::fs::inotify::sys_inotify_add_watch(args),
        syscall::nrs::NR_INOTIFY_RM_WATCH => ::fs::inotify::sys_inotify_rm_watch(args),
        syscall::nrs::NR_SIGNALFD => ::fs::signalfd::sys_signalfd(args),
        syscall::nrs::NR_SIGNALFD4 => ::fs::signalfd::sys_signalfd4(args),
        syscall::nrs::NR_TIMERFD_CREATE => ::fs::timerfd::sys_timerfd_create(args),
        syscall::nrs::NR_TIMERFD_SETTIME => ::fs::timerfd::sys_timerfd_settime(args),
        syscall::nrs::NR_TIMERFD_GETTIME => ::fs::timerfd::sys_timerfd_gettime(args),
        syscall::nrs::NR_EPOLL_CREATE => ::fs::epoll::sys_epoll_create(args),
        syscall::nrs::NR_EPOLL_CREATE1 => ::fs::epoll::sys_epoll_create1(args),
        syscall::nrs::NR_EPOLL_CTL => ::fs::epoll::sys_epoll_ctl(args),
        syscall::nrs::NR_EPOLL_WAIT => ::fs::epoll::sys_epoll_wait(args),
        syscall::nrs::NR_EPOLL_PWAIT => ::fs::epoll::sys_epoll_pwait(args),
        syscall::nrs::NR_EPOLL_PWAIT2 => ::fs::epoll::sys_epoll_pwait2(args),
        syscall::nrs::NR_GETPGID => crate::s121_getpgid::sys_getpgid(args),
        syscall::nrs::NR_GETSID => crate::s124_getsid::sys_getsid(args),
        syscall::nrs::NR_SETPGID => crate::s109_setpgid::sys_setpgid(args),
        syscall::nrs::NR_SETSID => crate::s112_setsid::sys_setsid(args),
        syscall::nrs::NR_UMASK => crate::s095_umask::sys_umask(args),
        syscall::nrs::NR_ACCESS => crate::fs_access::sys_access(args),
        syscall::nrs::NR_FACCESSAT => crate::fs_access::sys_faccessat(args),
        syscall::nrs::NR_EVENTFD => crate::s290_eventfd2::sys_eventfd(args),
        syscall::nrs::NR_EVENTFD2 => crate::s290_eventfd2::sys_eventfd2(args),
        syscall::nrs::NR_GETDENTS => crate::s217_getdents64::sys_getdents(args),
        syscall::nrs::NR_GETDENTS64 => crate::s217_getdents64::sys_getdents64(args),
        syscall::nrs::NR_PREAD64 => crate::s017_pread64::sys_pread64(args),
        syscall::nrs::NR_PWRITE64 => crate::s018_pwrite64::sys_pwrite64(args),
        syscall::nrs::NR_PREADV => crate::s295_preadv::sys_preadv(args),
        syscall::nrs::NR_PWRITEV => crate::s296_pwritev::sys_pwritev(args),
        syscall::nrs::NR_PREADV2 => crate::s295_preadv::sys_preadv2(args),
        syscall::nrs::NR_PWRITEV2 => crate::s296_pwritev::sys_pwritev2(args),
        syscall::nrs::NR_MEMFD_CREATE => crate::s319_memfd_create::sys_memfd_create(args),
        syscall::nrs::NR_MEMFD_SECRET => {
            let mut sa = *args; sa.a0 = 0; sa.a1 = args.a0;
            crate::s319_memfd_create::sys_memfd_create(&sa)
        }
        syscall::nrs::NR_MKDIR => crate::s083_mkdir::sys_mkdir(args),
        syscall::nrs::NR_MKDIRAT => crate::s258_mkdirat::sys_mkdirat(args),
        syscall::nrs::NR_RMDIR => crate::s084_rmdir::sys_rmdir(args),
        syscall::nrs::NR_UNLINK => crate::s087_unlink::sys_unlink(args),
        syscall::nrs::NR_UNLINKAT => crate::s263_unlinkat::sys_unlinkat(args),
        syscall::nrs::NR_RENAME => crate::s082_rename::sys_rename(args),
        syscall::nrs::NR_RENAMEAT => crate::s264_renameat::sys_renameat(args),
        syscall::nrs::NR_RENAMEAT2 => crate::s316_renameat2::sys_renameat2(args),
        syscall::nrs::NR_TRUNCATE => crate::s076_truncate::sys_truncate(args),
        syscall::nrs::NR_FTRUNCATE => crate::s077_ftruncate::sys_ftruncate(args),
        syscall::nrs::NR_FALLOCATE => sched::falloc::sys_fallocate(args),
        syscall::nrs::NR_SENDFILE => sched::xfer::sys_sendfile(args),
        syscall::nrs::NR_COPY_FILE_RANGE => sched::xfer::sys_copy_file_range(args),
        syscall::nrs::NR_SPLICE => sched::xfer::sys_splice(args),
        syscall::nrs::NR_TEE => sched::xfer::sys_tee(args),
        syscall::nrs::NR_VMSPLICE => sched::xfer::sys_vmsplice(args),
        syscall::nrs::NR_OPENAT => crate::s257_openat::sys_openat(args),
        syscall::nrs::NR_OPENAT2 => crate::s257_openat::sys_openat2(args),
        syscall::nrs::NR_FACCESSAT2 => crate::fs_access::sys_faccessat2(args),
        syscall::nrs::NR_SYNC => crate::misc::sys_sync(args),
        syscall::nrs::NR_SYNCFS => crate::misc::sys_syncfs(args),
        syscall::nrs::NR_REBOOT => crate::misc::sys_reboot(args),
        syscall::nrs::NR_FDATASYNC => crate::misc::sys_fdatasync(args),
        nr if matches!(nr, syscall::nrs::NR_FSYNC | syscall::nrs::NR_SYNC_FILE_RANGE) => crate::misc::sys_fsync(args),
        syscall::nrs::NR_CACHESTAT => crate::s451_cachestat::sys_cachestat(args),
        nr if matches!(nr, syscall::nrs::NR_PKEY_ALLOC | syscall::nrs::NR_PKEY_FREE | syscall::nrs::NR_PKEY_MPROTECT | syscall::nrs::NR_KCMP | syscall::nrs::NR_SET_MEMPOLICY | syscall::nrs::NR_GET_MEMPOLICY | syscall::nrs::NR_MBIND | syscall::nrs::NR_SET_MEMPOLICY_HOME_NODE | syscall::nrs::NR_MIGRATE_PAGES | syscall::nrs::NR_MOVE_PAGES | syscall::nrs::NR_PROCESS_MADVISE | syscall::nrs::NR_PROCESS_MRELEASE) => crate::misc::dispatch(nr, args),
        _ => return None,
    })
}
