#![cfg(target_os = "oxide-kernel")]

use syscall::SyscallArgs;

pub(super) fn dispatch_route_c(nr: u64, args: &SyscallArgs) -> Option<i64> {
    Some(match nr {
        syscall::nrs::NR_SOCKET => crate::s041_socket::sys_socket(args),
        syscall::nrs::NR_BIND => crate::s049_bind::sys_bind(args),
        syscall::nrs::NR_SENDTO => crate::s044_sendto::sys_sendto(args),
        syscall::nrs::NR_RECVFROM => crate::net_recv::sys_recvfrom(args),
        syscall::nrs::NR_LISTEN => crate::s050_listen::sys_listen(args),
        syscall::nrs::NR_ACCEPT => crate::s043_accept::sys_accept(args),
        syscall::nrs::NR_ACCEPT4 => crate::s043_accept::sys_accept4(args),
        syscall::nrs::NR_CONNECT => crate::s042_connect::sys_connect(args),
        syscall::nrs::NR_SOCKETPAIR => crate::s053_socketpair::sys_socketpair(args),
        syscall::nrs::NR_GETSOCKNAME => crate::s051_getsockname::sys_getsockname(args),
        syscall::nrs::NR_GETPEERNAME => crate::s052_getpeername::sys_getpeername(args),
        syscall::nrs::NR_SHUTDOWN => crate::s048_shutdown::sys_shutdown(args),
        syscall::nrs::NR_SETSOCKOPT => crate::s054_setsockopt::sys_setsockopt(args),
        syscall::nrs::NR_GETSOCKOPT => crate::s055_getsockopt::sys_getsockopt(args),
        syscall::nrs::NR_SENDMSG => crate::s046_sendmsg::sys_sendmsg(args),
        syscall::nrs::NR_RECVMSG => crate::s047_recvmsg::sys_recvmsg(args),
        syscall::nrs::NR_SENDMMSG => crate::net::sys_sendmmsg(args),
        syscall::nrs::NR_RECVMMSG => crate::net::sys_recvmmsg(args),
        syscall::nrs::NR_FLOCK => ::fs::flock::sys_flock(args),
        syscall::nrs::NR_PERSONALITY => crate::s135_personality::sys_personality(args),
        syscall::nrs::NR_CHROOT => crate::chroot::sys_chroot(args),
        syscall::nrs::NR_MOUNT => crate::s165_mount::sys_mount(args),
        syscall::nrs::NR_UMOUNT2 => crate::s166_umount2::sys_umount2(args),
        syscall::nrs::NR_PIVOT_ROOT => crate::s155_pivot_root::sys_pivot_root(args),
        syscall::nrs::NR_GET_MEMPOLICY => syscall::numa::sys_get_mempolicy(args),
        syscall::nrs::NR_VHANGUP => crate::s153_vhangup::sys_vhangup(args),
        syscall::nrs::NR_FUTIMESAT | syscall::nrs::NR_UTIMENSAT => crate::s280_utimensat::sys_utimensat(args),
        syscall::nrs::NR_MQ_NOTIFY => ::ipc::live::posix_mq::sys_mq_notify(args),
        syscall::nrs::NR_MQ_GETSETATTR => ::ipc::live::posix_mq::sys_mq_getsetattr(args),
        syscall::nrs::NR_PROCESS_VM_READV => crate::pvmrw::sys_process_vm_readv(args),
        syscall::nrs::NR_PROCESS_VM_WRITEV => crate::pvmrw::sys_process_vm_writev(args),
        syscall::nrs::NR_UTIMES | syscall::nrs::NR_UTIME => crate::utime_common::sys_utime_dispatch(nr, args),
        syscall::nrs::NR_LINK => crate::s086_link::sys_link(args),
        syscall::nrs::NR_LINKAT => crate::s265_linkat::sys_linkat(args),
        syscall::nrs::NR_SYMLINK => crate::s088_symlink::sys_symlink(args),
        syscall::nrs::NR_SYMLINKAT => crate::s266_symlinkat::sys_symlinkat(args),
        syscall::nrs::NR_MKNOD => crate::s133_mknod::sys_mknod(args),
        syscall::nrs::NR_MKNODAT => crate::s259_mknodat::sys_mknodat(args),
        syscall::nrs::NR_STATFS => crate::statfs::sys_statfs(args),
        syscall::nrs::NR_FSTATFS => crate::statfs::sys_fstatfs(args),
        syscall::nrs::NR_GETCPU => crate::s309_getcpu::sys_getcpu(args),
        syscall::nrs::NR_SETXATTR => crate::s188_setxattr::sys_setxattr(args),
        syscall::nrs::NR_LSETXATTR => crate::s189_lsetxattr::sys_lsetxattr(args),
        syscall::nrs::NR_FSETXATTR => crate::s190_fsetxattr::sys_fsetxattr(args),
        syscall::nrs::NR_GETXATTR => crate::s191_getxattr::sys_getxattr(args),
        syscall::nrs::NR_LGETXATTR => crate::s192_lgetxattr::sys_lgetxattr(args),
        syscall::nrs::NR_FGETXATTR => crate::s193_fgetxattr::sys_fgetxattr(args),
        syscall::nrs::NR_LISTXATTR => crate::s194_listxattr::sys_listxattr(args),
        syscall::nrs::NR_LLISTXATTR => crate::s195_llistxattr::sys_llistxattr(args),
        syscall::nrs::NR_FLISTXATTR => crate::s196_flistxattr::sys_flistxattr(args),
        syscall::nrs::NR_REMOVEXATTR => crate::s197_removexattr::sys_removexattr(args),
        syscall::nrs::NR_LREMOVEXATTR => crate::s198_lremovexattr::sys_lremovexattr(args),
        syscall::nrs::NR_FREMOVEXATTR => crate::s199_fremovexattr::sys_fremovexattr(args),
        syscall::nrs::NR_SCHED_GETPARAM => crate::s143_sched_getparam::sys_sched_getparam(args),
        syscall::nrs::NR_SCHED_SETSCHEDULER => crate::s144_sched_setscheduler::sys_sched_setscheduler(args),
        syscall::nrs::NR_SCHED_GETSCHEDULER => crate::s145_sched_getscheduler::sys_sched_getscheduler(args),
        syscall::nrs::NR_SCHED_GET_PRIORITY_MAX => crate::s146_sched_get_priority_max::sys_sched_get_priority_max(args),
        syscall::nrs::NR_SCHED_GET_PRIORITY_MIN => crate::s147_sched_get_priority_min::sys_sched_get_priority_min(args),
        syscall::nrs::NR_SCHED_GETAFFINITY => crate::s204_sched_getaffinity::sys_sched_getaffinity(args),
        syscall::nrs::NR_SCHED_SETAFFINITY => crate::s203_sched_setaffinity::sys_sched_setaffinity(args),
        syscall::nrs::NR_PRCTL => crate::s157_prctl::sys_prctl(args),
        syscall::nrs::NR_FUTEX => crate::s202_futex::sys_futex(args),
        syscall::nrs::NR_FUTEX_WAITV => crate::futex_waitv::sys_futex_waitv(args),
        syscall::nrs::NR_CLONE3 => crate::s435_clone3::sys_clone3(args),
        syscall::nrs::NR_MPROTECT => crate::s010_mprotect::sys_mprotect(args),
        syscall::nrs::NR_MADVISE => crate::s028_madvise::sys_madvise(args),
        syscall::nrs::NR_PRLIMIT64 => crate::s302_prlimit64::sys_prlimit64(args),
        syscall::nrs::NR_RT_SIGACTION => crate::s013_rt_sigaction::sys_rt_sigaction(args),
        syscall::nrs::NR_RT_SIGPROCMASK => crate::s014_rt_sigprocmask::sys_rt_sigprocmask(args),
        syscall::nrs::NR_SIGALTSTACK => crate::s131_sigaltstack::sys_sigaltstack(args),
        syscall::nrs::NR_NANOSLEEP => crate::s035_nanosleep::sys_nanosleep(args),
        syscall::nrs::NR_CLOCK_NANOSLEEP => crate::proc::sys_clock_nanosleep(args),
        syscall::nrs::NR_CLOSE => crate::s003_close::sys_close(args),
        syscall::nrs::NR_CLOSE_RANGE => crate::s436_close_range::sys_close_range(args),
        syscall::nrs::NR_DUP => crate::s032_dup::sys_dup(args),
        syscall::nrs::NR_DUP2 => crate::s033_dup2::sys_dup2(args),
        syscall::nrs::NR_DUP3 => crate::s292_dup3::sys_dup3(args),
        syscall::nrs::NR_FORK => crate::clone::sys_clone_dispatch(args, 0x11, 0, 0, 0, 0, 0, None),
        syscall::nrs::NR_VFORK => crate::clone::sys_clone_dispatch(args, 0x4111, 0, 0, 0, 0, 0, None),
        syscall::nrs::NR_CLONE => {
            #[cfg(target_arch = "x86_64")] let (ctid, tls) = (args.a3, args.a4);
            #[cfg(target_arch = "aarch64")] let (ctid, tls) = (args.a4, args.a3);
            let flags = args.a0;
            if (flags & (crate::clone::CLONE_PIDFD | crate::clone::CLONE_PARENT_SETTID))
                == (crate::clone::CLONE_PIDFD | crate::clone::CLONE_PARENT_SETTID) {
                return Some(-(syscall::errno::Errno::Einval.as_i32() as i64));
            }
            if (flags & crate::clone::CLONE_PIDFD) != 0
                && (args.a2 == 0 || args.a2.checked_add(4).map_or(true, |e| e > hal::USER_VA_END)) {
                return Some(-(syscall::errno::Errno::Efault.as_i32() as i64));
            }
            crate::clone::sys_clone_dispatch(
                args, flags, args.a1, args.a2, args.a2, ctid, tls, None,
            )
        }
        syscall::nrs::NR_EXECVE => crate::execve::sys_execve(args),
        syscall::nrs::NR_EXECVEAT => crate::execve::sys_execveat(args),
        syscall::nrs::NR_WAIT4 => crate::wait::sys_wait4(args),
        syscall::nrs::NR_WAITID => crate::waitid::sys_waitid(args),
        syscall::nrs::NR_RT_SIGPENDING => crate::s127_rt_sigpending::sys_rt_sigpending(args),
        syscall::nrs::NR_RT_SIGSUSPEND => crate::s130_rt_sigsuspend::sys_rt_sigsuspend(args),
        syscall::nrs::NR_RT_SIGTIMEDWAIT => crate::s128_rt_sigtimedwait::sys_rt_sigtimedwait(args),
        syscall::nrs::NR_RT_SIGQUEUEINFO => crate::s129_rt_sigqueueinfo::sys_rt_sigqueueinfo(args),
        syscall::nrs::NR_RT_TGSIGQUEUEINFO => crate::s297_rt_tgsigqueueinfo::sys_rt_tgsigqueueinfo(args),
        syscall::nrs::NR_PIPE => {
            let mut a = *args;
            a.a1 = 0;
            crate::s293_pipe2::sys_pipe2(&a)
        }
        syscall::nrs::NR_CREAT => crate::s002_open::sys_creat(args),
        syscall::nrs::NR_EXIT_GROUP => crate::s060_exit::sys_exit_group(args),
        syscall::nrs::NR_INIT_MODULE => crate::s175_init_module::sys_init_module(args),
        syscall::nrs::NR_FINIT_MODULE => crate::s313_finit_module::sys_finit_module(args),
        syscall::nrs::NR_DELETE_MODULE => crate::s176_delete_module::sys_delete_module(args),
        syscall::nrs::NR_NEWFSTATAT => crate::fs::sys_newfstatat(args),
        syscall::nrs::NR_STAT => crate::s004_stat::sys_stat(args),
        syscall::nrs::NR_LSTAT => crate::s006_lstat::sys_lstat(args),
        syscall::nrs::NR_SET_ROBUST_LIST => crate::s273_set_robust_list::sys_set_robust_list(args),
        syscall::nrs::NR_GET_ROBUST_LIST => crate::s274_get_robust_list::sys_get_robust_list(args),
        syscall::nrs::NR_FCHMODAT2 => crate::s452_fchmodat2::sys_fchmodat2(args),
        syscall::nrs::NR_MSEAL => crate::s462_mseal::sys_mseal(args),
        syscall::nrs::NR_IOPRIO_SET => crate::s251_ioprio_set::sys_ioprio_set(args),
        syscall::nrs::NR_IOPRIO_GET => crate::s252_ioprio_get::sys_ioprio_get(args),
        syscall::nrs::NR_SCHED_GETATTR => crate::s315_sched_getattr::sys_sched_getattr(args),
        syscall::nrs::NR_LSM_GET_SELF_ATTR => crate::s459_lsm_get::sys_lsm_get_self_attr(args),
        syscall::nrs::NR_LSM_SET_SELF_ATTR => crate::s460_lsm_set::sys_lsm_set_self_attr(args),
        syscall::nrs::NR_LSM_LIST_MODULES => crate::s461_lsm_list::sys_lsm_list_modules(args),
        syscall::nrs::NR_FUTEX_WAKE => crate::s454_futex_wake::sys_futex_wake(args),
        syscall::nrs::NR_FUTEX_WAIT => crate::s455_futex_wait::sys_futex_wait(args),
        syscall::nrs::NR_SETXATTRAT => crate::s463_setxattrat::sys_setxattrat(args),
        syscall::nrs::NR_GETXATTRAT => crate::s464_getxattrat::sys_getxattrat(args),
        syscall::nrs::NR_LISTXATTRAT => crate::s465_listxattrat::sys_listxattrat(args),
        syscall::nrs::NR_REMOVEXATTRAT => crate::s466_removexattrat::sys_removexattrat(args),
        syscall::nrs::NR_FUTEX_REQUEUE => crate::s456_futex_requeue::sys_futex_requeue(args),
        syscall::nrs::NR_STATMOUNT => crate::s457_statmount::sys_statmount(args),
        syscall::nrs::NR_LISTMOUNT => crate::s458_listmount::sys_listmount(args),
        syscall::nrs::NR_FILE_GETATTR => crate::s468_file_getattr::sys_file_getattr(args),
        syscall::nrs::NR_FILE_SETATTR => crate::s469_file_setattr::sys_file_setattr(args),
        syscall::nrs::NR_LISTNS => crate::s470_listns::sys_listns(args),
        syscall::nrs::NR_RSEQ_SLICE_YIELD => crate::s471_rseq_slice_yield::sys_rseq_slice_yield(args),
        syscall::nrs::NR_SCHED_SETPARAM => crate::s142_sched_setparam::sys_sched_setparam(args),
        syscall::nrs::NR_SCHED_SETATTR => crate::s314_sched_setattr::sys_sched_setattr(args),
        syscall::nrs::NR_OPEN_TREE_ATTR => crate::s467_open_tree_attr::sys_open_tree_attr(args),
        syscall::nrs::NR_SYSLOG => crate::s103_syslog::sys_syslog(args),
        syscall::nrs::NR_URETPROBE => crate::s335_uretprobe::sys_uretprobe(args),
        syscall::nrs::NR_UPROBE => crate::s336_uprobe::sys_uprobe(args),
        syscall::nrs::NR_MAP_SHADOW_STACK => crate::s453_map_shadow_stack::sys_map_shadow_stack(args),
        n if crate::misc::is_obsolete(n) => -(syscall::errno::Errno::Enosys.as_i32() as i64),
        syscall::nrs::NR_RT_SIGRETURN => unsafe { ::fs::sig_dispatch::rt_sigreturn() },
        _ => return None,
    })
}
