[package]
name = "drv-rtl8125"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
pci = { path = "../pci" }
pmm = { path = "../../kernel/mm-pmm" }
iommu = { path = "../../kernel/iommu" }
drv = { path = "../drv" }
mmio-map = { path = "../../kernel/mmio-map" }
net = { path = "../../kernel/net" }
sync = { path = "../../shared/sync" }
sched = { path = "../../kernel/sched" }
arch-irq = { path = "../../kernel/arch-irq" }
pci-irq = { path = "../../kernel/pci-irq" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
hal-x86_64 = { path = "../../arch/hal-x86_64" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
hal-aarch64 = { path = "../../arch/hal-aarch64" }

[lints]
workspace = true
