use super::types::*;
use core::mem::{offset_of, size_of};

#[test]
fn bio_layout_matches_the_module_header_contract() { assert_eq!(size_of::<LinuxBioVec>(), 16); assert_eq!(size_of::<LinuxBio>(), 80); assert_eq!(offset_of!(LinuxBio, bi_size), 40); assert_eq!(offset_of!(LinuxBio, bi_io_vec), 48); assert_eq!(offset_of!(LinuxBio, bi_vcnt), 56); assert_eq!(offset_of!(LinuxBio, bi_end_io), 64); }
#[test]
fn block_device_layout_matches_the_supported_module_abi() { assert_eq!(size_of::<LinuxBlockDevice>(), 984); assert_eq!(offset_of!(LinuxBlockDevice, bd_disk), 16); assert_eq!(offset_of!(LinuxBlockDevice, bd_queue), 24); assert_eq!(offset_of!(LinuxBlockDevice, bd_holders), 128); assert_eq!(offset_of!(LinuxBlockDevice, bd_fsfreeze_mutex), 152); assert_eq!(offset_of!(LinuxBlockDevice, bd_device), 208); }
#[test]
fn gendisk_layout_matches_the_supported_module_abi() { assert_eq!(size_of::<LinuxGendisk>(), 656); assert_eq!(offset_of!(LinuxGendisk, part0), 64); assert_eq!(offset_of!(LinuxGendisk, queue), 80); assert_eq!(offset_of!(LinuxGendisk, flags), 344); assert_eq!(offset_of!(LinuxGendisk, state), 352); assert_eq!(offset_of!(LinuxGendisk, queue_kobj), 408); assert_eq!(offset_of!(LinuxGendisk, diskseq), 600); assert_eq!(offset_of!(LinuxGendisk, rqos_state_mutex), 624); assert_eq!(offset_of!(LinuxGendisk, zoned), 512); }
#[test]
fn blk_mq_tag_set_layout_matches_the_supported_module_abi() { assert_eq!(size_of::<LinuxBlkMqTagSet>(), 240); assert_eq!(offset_of!(LinuxBlkMqTagSet, map), 8); assert_eq!(offset_of!(LinuxBlkMqTagSet, nr_maps), 56); assert_eq!(offset_of!(LinuxBlkMqTagSet, driver_data), 88); assert_eq!(offset_of!(LinuxBlkMqTagSet, tags), 96); assert_eq!(offset_of!(LinuxBlkMqTagSet, tag_list_lock), 112); assert_eq!(offset_of!(LinuxBlkMqTagSet, srcu), 160); assert_eq!(offset_of!(LinuxBlkMqTagSet, tags_srcu), 168); assert_eq!(offset_of!(LinuxBlkMqTagSet, update_nr_hwq_lock), 200); }
#[test]
fn request_queue_layout_matches_the_supported_module_abi() { assert_eq!(size_of::<LinuxRequestQueue>(), 992); assert_eq!(offset_of!(LinuxRequestQueue, queuedata), 0); assert_eq!(offset_of!(LinuxRequestQueue, mq_ops), 16); assert_eq!(offset_of!(LinuxRequestQueue, rq_timeout), 40); assert_eq!(offset_of!(LinuxRequestQueue, disk), 96); assert_eq!(offset_of!(LinuxRequestQueue, limits), 112); assert_eq!(offset_of!(LinuxRequestQueue, mq_freeze_depth), 828); assert_eq!(offset_of!(LinuxRequestQueue, td), 832); assert_eq!(offset_of!(LinuxRequestQueue, tag_set), 912); assert_eq!(offset_of!(LinuxRequestQueue, debugfs_mutex), 960); }
#[test]
fn request_and_batch_layouts_match_the_module_header_contract() { assert_eq!(size_of::<LinuxRequest>(), 112); assert_eq!(offset_of!(LinuxRequest, bio), 24); assert_eq!(offset_of!(LinuxRequest, cmd_flags), 40); assert_eq!(offset_of!(LinuxRequest, sector), 64); assert_eq!(offset_of!(LinuxRequest, end_io), 88); assert_eq!(offset_of!(LinuxRequest, rq_next), 104); assert_eq!(size_of::<LinuxIoCompBatch>(), 40); assert_eq!(offset_of!(LinuxIoCompBatch, complete), 24); }
#[test]
fn queue_limits_layout_matches_the_supported_module_abi() { assert_eq!(size_of::<LinuxBlkIntegrity>(), 7); assert_eq!(size_of::<LinuxQueueLimits>(), 192); assert_eq!(offset_of!(LinuxQueueLimits, logical_block_size), 56); assert_eq!(offset_of!(LinuxQueueLimits, max_segments), 156); assert_eq!(offset_of!(LinuxQueueLimits, integrity), 184); }
#[test]
fn zoned_report_layout_matches_the_module_header_contract() { assert_eq!(size_of::<LinuxBlkZone>(), 64); assert_eq!(offset_of!(LinuxBlkZone, start), 0); assert_eq!(offset_of!(LinuxBlkZone, wp), 16); assert_eq!(offset_of!(LinuxBlkZone, zone_type), 24); assert_eq!(offset_of!(LinuxBlkZone, capacity), 32); assert_eq!(size_of::<LinuxBlkReportZonesArgs>(), 24); assert_eq!(offset_of!(LinuxBlkReportZonesArgs, cb), 0); assert_eq!(offset_of!(LinuxBlkReportZonesArgs, data), 8); assert_eq!(offset_of!(LinuxBlkReportZonesArgs, report_active), 16); assert_eq!(size_of::<LinuxGendiskZoned>(), 72); assert_eq!(offset_of!(LinuxGendiskZoned, zone_wplugs_hash), 48); }
