[package]
name = "f2fs"
version = "0.1.0"
edition = "2021"
publish = false
[lib]
path = "src/lib.rs"
[dependencies]
sync    = { path = "../../shared/sync" }
syscall = { path = "../syscall" }
klog    = { path = "../../shared/klog" }
vfs     = { path = "../vfs" }
block   = { path = "../block" }
sectors = { path = "../sectors" }
crc     = { path = "../../shared/crc" }


[features]
default = []
hosted = []

[lints]
workspace = true
