//! posix — glibc-ABI surface, one fn/file (docs/59§3). Implemented at G8 (docs/59§6).
//! write/read land early (G2), mmap/brk at G3, for the entry + malloc paths.
pub mod io;
pub mod mman;
#[cfg(feature = "freestanding")]
pub mod random;
#[cfg(feature = "freestanding")]
pub mod ids;
#[cfg(feature = "freestanding")]
pub mod process;
#[cfg(feature = "freestanding")]
pub mod procmisc;
#[cfg(feature = "freestanding")]
pub mod proctimer;
#[cfg(feature = "freestanding")]
pub mod fd;
#[cfg(feature = "freestanding")]
pub mod epoll;
#[cfg(feature = "freestanding")]
pub mod linuxfd;
#[cfg(feature = "freestanding")]
pub mod xattr;
#[cfg(feature = "freestanding")]
pub mod morecalls;
#[cfg(feature = "freestanding")]
pub mod spawn;
#[cfg(feature = "freestanding")]
pub mod misc2;
#[cfg(feature = "freestanding")]
pub mod admin;
#[cfg(feature = "freestanding")]
pub mod statfs;
#[cfg(feature = "freestanding")]
pub mod modern;
#[cfg(feature = "freestanding")]
pub mod sysmisc;
#[cfg(feature = "freestanding")]
pub mod clone;
#[cfg(feature = "freestanding")]
pub mod fs;
pub mod stat;
pub mod fnmatch;
pub mod getopt;
pub mod libgen;
pub mod dirent;
#[cfg(feature = "freestanding")]
pub mod glob;
#[cfg(feature = "freestanding")]
pub mod argz;
#[cfg(feature = "freestanding")]
pub mod argp;
#[cfg(feature = "freestanding")]
pub mod envz;
#[cfg(feature = "freestanding")]
pub mod wordexp;
#[cfg(feature = "freestanding")]
pub mod mntent;
#[cfg(feature = "freestanding")]
pub mod fstab;
#[cfg(feature = "freestanding")]
pub mod ftw;
#[cfg(feature = "freestanding")]
pub mod sched;
#[cfg(feature = "freestanding")]
pub mod resource;
#[cfg(feature = "freestanding")]
pub mod utmp;
#[cfg(feature = "freestanding")]
pub mod vector;
#[cfg(feature = "freestanding")]
pub mod vfsctl;
#[cfg(feature = "freestanding")]
pub mod mem;
#[cfg(feature = "freestanding")]
pub mod special;
#[cfg(feature = "freestanding")]
pub mod utime;
pub mod pty;
#[cfg(feature = "freestanding")]
pub mod tty;
pub mod sysvipc;
#[cfg(feature = "freestanding")]
pub mod shm;
#[cfg(feature = "freestanding")]
pub mod posixsem;
