[package]
name = "md"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
block = { path = "../block" }
sync = { path = "../../shared/sync" }
sched = { path = "../sched" }
timekeeper = { path = "../timekeeper" }

[features]
default = []
hosted = ["block/hosted"]

[lints]
workspace = true
