// The purgatory's assembled body. Split out of the parent manifest only for
// the file-length cap (`08§7`); the parent owns the bounds and the accessor.
//
// One body, two homes. In the kernel the blob is read-only data that is copied,
// never executed in place — the reference likewise keeps its purgatory in
// `.rodata`. In a hosted test build it must additionally be EXECUTABLE, because
// the tests call into it; assembling the identical bytes into an executable
// section is what makes the thing under test the thing that ships.
macro_rules! purgatory_asm {
    ($section:literal) => { core::arch::global_asm!(
    $section,
    ".balign 4096",
    ".globl oxide_purgatory_blob_start",
    "oxide_purgatory_blob_start:",

    // --- patched by the kernel ------------------------------------------
    "oxp_regs:      .fill 136, 1, 0",              // entry64_regs, 17 * 8
    "oxp_digest:    .fill 32, 1, 0",               // purgatory_sha256_digest
    "               .fill 8, 1, 0",                // pad to the region table
    "oxp_regions:   .fill 256, 1, 0",              // purgatory_sha_regions
    "oxp_regions_end:",

    // --- fixed data -----------------------------------------------------
    // Null, unused, 64-bit code (L=1) at 0x10, flat data at 0x18.
    "oxp_gdt:       .word 0, 0, 0, 0",
    "               .word 0, 0, 0, 0",
    "               .word 0xFFFF, 0x0000, 0x9A00, 0x00AF",
    "               .word 0xFFFF, 0x0000, 0x9200, 0x00CF",
    "oxp_gdtr:      .word 31",                     // limit = GDT_SIZE - 1
    "               .quad 0",                      // base, written at run time
    "               .fill 6, 1, 0",
    "oxp_h0:        .long 0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a",
    "               .long 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19",
    "oxp_k:         .long 0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5",
    "               .long 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5",
    "               .long 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3",
    "               .long 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174",
    "               .long 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc",
    "               .long 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da",
    "               .long 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7",
    "               .long 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967",
    "               .long 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13",
    "               .long 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85",
    "               .long 0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3",
    "               .long 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070",
    "               .long 0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5",
    "               .long 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3",
    "               .long 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208",
    "               .long 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2",

    // The data area is exactly OFF_CODE bytes. `.org` both pads and CHECKS:
    // an overrun is "attempt to move .org backwards", a build failure, which is
    // the same class of guarantee the linker ASSERT gives the trampoline.
    ".org 0x300",

    // --- entry ----------------------------------------------------------
    ".globl oxide_purgatory_entry",
    "oxide_purgatory_entry:",
    "    cli",
    "    lea  rax, [rip + oxp_gdt]",
    "    mov  qword ptr [rip + oxp_gdtr + 2], rax",
    "    lgdt [rip + oxp_gdtr]",
    "    mov  eax, 0x18",
    "    mov  ds, ax",
    "    mov  es, ax",
    "    mov  ss, ax",
    "    mov  fs, ax",
    "    mov  gs, ax",
    "    lea  rsp, [rip + oxp_pstack_end]",
    // Reload CS through a far return: the incoming selector belongs to a GDT
    // that no longer exists.
    "    push 0x10",
    "    lea  rax, [rip + oxp_cs_ok]",
    "    push rax",
    "    retfq",
    "oxp_cs_ok:",
    // Frame: [rsp, rsp+128) SHA context, [rsp+128, rsp+160) computed digest.
    "    sub  rsp, 160",
    "    mov  rdi, rsp",
    "    call oxp_sha_init",
    "    lea  rbx, [rip + oxp_regions]",
    "    lea  rbp, [rip + oxp_regions_end]",
    "oxp_rgn:",
    "    mov  rdx, [rbx + 8]",
    "    test rdx, rdx",
    "    jz   oxp_rgn_next",
    "    mov  rdi, rsp",
    "    mov  rsi, [rbx]",
    "    call oxp_sha_update",
    "oxp_rgn_next:",
    "    add  rbx, 16",
    "    cmp  rbx, rbp",
    "    jb   oxp_rgn",
    "    mov  rdi, rsp",
    "    lea  rsi, [rsp + 128]",
    "    call oxp_sha_final",
    // Fail closed: any difference halts here forever rather than entering a
    // kernel the relocation did not deliver intact.
    "    lea  rsi, [rip + oxp_digest]",
    "    lea  rdi, [rsp + 128]",
    "    mov  ecx, 32",
    "oxp_cmp:",
    "    mov  al, [rdi]",
    "    cmp  al, [rsi]",
    "    jne  oxp_halt",
    "    inc  rdi",
    "    inc  rsi",
    "    dec  ecx",
    "    jnz  oxp_cmp",
    // Every register comes from the block, RIP-relatively, so no register is
    // needed to hold a base and `rsp` and `rax` can be loaded last.
    "    mov  rcx, [rip + oxp_regs + 8]",
    "    mov  rdx, [rip + oxp_regs + 16]",
    "    mov  rbx, [rip + oxp_regs + 24]",
    "    mov  rbp, [rip + oxp_regs + 40]",
    "    mov  rsi, [rip + oxp_regs + 48]",
    "    mov  rdi, [rip + oxp_regs + 56]",
    "    mov  r8,  [rip + oxp_regs + 64]",
    "    mov  r9,  [rip + oxp_regs + 72]",
    "    mov  r10, [rip + oxp_regs + 80]",
    "    mov  r11, [rip + oxp_regs + 88]",
    "    mov  r12, [rip + oxp_regs + 96]",
    "    mov  r13, [rip + oxp_regs + 104]",
    "    mov  r14, [rip + oxp_regs + 112]",
    "    mov  r15, [rip + oxp_regs + 120]",
    "    mov  rsp, [rip + oxp_regs + 32]",
    "    mov  rax, [rip + oxp_regs + 0]",
    "    jmp  [rip + oxp_regs + 128]",
    "oxp_halt:",
    "    cli",
    "    hlt",
    "    jmp  oxp_halt",

    // --- SHA-256 --------------------------------------------------------
    // Context, 128 bytes: h[8] @0, total @32, buflen @40, buf[64] @48,
    // data pointer @112, remaining length @120. The last two are in the
    // context rather than in registers because `oxp_sha_compress` is free to
    // clobber every caller-saved register.
    "oxp_sha_init:",                               // rdi = ctx (preserved)
    "    lea  rsi, [rip + oxp_h0]",
    "    xor  ecx, ecx",
    "oxp_si_1:",
    "    mov  eax, [rsi + rcx*4]",
    "    mov  [rdi + rcx*4], eax",
    "    inc  ecx",
    "    cmp  ecx, 8",
    "    jb   oxp_si_1",
    "    mov  qword ptr [rdi + 32], 0",
    "    mov  qword ptr [rdi + 40], 0",
    "    ret",

    "oxp_sha_update:",                             // rdi = ctx, rsi = p, rdx = n
    "    test rdx, rdx",
    "    jz   oxp_su_done",
    "    add  [rdi + 32], rdx",
    "    mov  [rdi + 112], rsi",
    "    mov  [rdi + 120], rdx",
    "oxp_su_loop:",
    "    mov  rdx, [rdi + 120]",
    "    test rdx, rdx",
    "    jz   oxp_su_done",
    "    mov  rcx, [rdi + 40]",
    "    test rcx, rcx",
    "    jnz  oxp_su_buffer",
    "    cmp  rdx, 64",
    "    jb   oxp_su_buffer",
    "    mov  rsi, [rdi + 112]",
    "    call oxp_sha_compress",
    "    add  qword ptr [rdi + 112], 64",
    "    sub  qword ptr [rdi + 120], 64",
    "    jmp  oxp_su_loop",
    "oxp_su_buffer:",
    "    mov  rax, 64",
    "    sub  rax, rcx",
    "    cmp  rax, rdx",
    "    jbe  oxp_su_take",
    "    mov  rax, rdx",
    "oxp_su_take:",
    "    mov  rsi, [rdi + 112]",
    "    lea  r8, [rdi + 48]",
    "    add  r8, rcx",
    "    mov  r9, rax",
    "oxp_su_copy:",
    "    mov  r10b, [rsi]",
    "    mov  [r8], r10b",
    "    inc  rsi",
    "    inc  r8",
    "    dec  r9",
    "    jnz  oxp_su_copy",
    "    add  [rdi + 40], rax",
    "    add  [rdi + 112], rax",
    "    sub  [rdi + 120], rax",
    "    cmp  qword ptr [rdi + 40], 64",
    "    jne  oxp_su_loop",
    "    lea  rsi, [rdi + 48]",
    "    call oxp_sha_compress",
    "    mov  qword ptr [rdi + 40], 0",
    "    jmp  oxp_su_loop",
    "oxp_su_done:",
    "    ret",

    "oxp_sha_final:",                              // rdi = ctx, rsi = out(32)
    "    mov  [rdi + 112], rsi",
    "    mov  rcx, [rdi + 40]",
    "    lea  r8, [rdi + 48]",
    "    mov  byte ptr [r8 + rcx], 0x80",
    "    inc  rcx",
    "    mov  rax, rcx",
    "oxp_sf_pad:",
    "    cmp  rax, 64",
    "    jae  oxp_sf_padded",
    "    mov  byte ptr [r8 + rax], 0",
    "    inc  rax",
    "    jmp  oxp_sf_pad",
    "oxp_sf_padded:",
    "    cmp  rcx, 56",
    "    jbe  oxp_sf_len",
    // The 0x80 left no room for the length: close this block and zero a new one.
    "    mov  rsi, r8",
    "    call oxp_sha_compress",
    "    lea  r8, [rdi + 48]",
    "    xor  eax, eax",
    "oxp_sf_zero:",
    "    cmp  eax, 56",
    "    jae  oxp_sf_len",
    "    mov  byte ptr [r8 + rax], 0",
    "    inc  eax",
    "    jmp  oxp_sf_zero",
    "oxp_sf_len:",
    "    mov  rax, [rdi + 32]",
    "    shl  rax, 3",
    "    bswap rax",
    "    mov  [rdi + 104], rax",                   // buf + 56
    "    lea  rsi, [rdi + 48]",
    "    call oxp_sha_compress",
    "    mov  rsi, [rdi + 112]",
    "    xor  ecx, ecx",
    "oxp_sf_out:",
    "    mov  eax, [rdi + rcx*4]",
    "    bswap eax",
    "    mov  [rsi + rcx*4], eax",
    "    inc  ecx",
    "    cmp  ecx, 8",
    "    jb   oxp_sf_out",
    "    ret",

    "oxp_sha_compress:",                           // rdi = ctx (preserved), rsi = block
    "    push rbx",
    "    push rbp",
    "    push r12",
    "    push r13",
    "    push r14",
    "    push r15",
    "    push rdi",
    "    sub  rsp, 256",
    "    mov  rbp, rsp",
    "    xor  ecx, ecx",
    "oxp_sc_w0:",
    "    mov  eax, [rsi + rcx*4]",
    "    bswap eax",
    "    mov  [rbp + rcx*4], eax",
    "    inc  ecx",
    "    cmp  ecx, 16",
    "    jb   oxp_sc_w0",
    "oxp_sc_w1:",
    "    mov  eax, [rbp + rcx*4 - 8]",             // w[i-2]
    "    mov  edx, eax",
    "    ror  edx, 17",
    "    mov  ebx, eax",
    "    ror  ebx, 19",
    "    xor  edx, ebx",
    "    shr  eax, 10",
    "    xor  edx, eax",
    "    add  edx, [rbp + rcx*4 - 28]",            // w[i-7]
    "    mov  eax, [rbp + rcx*4 - 60]",            // w[i-15]
    "    mov  ebx, eax",
    "    ror  ebx, 7",
    "    mov  r8d, eax",
    "    ror  r8d, 18",
    "    xor  ebx, r8d",
    "    shr  eax, 3",
    "    xor  ebx, eax",
    "    add  edx, ebx",
    "    add  edx, [rbp + rcx*4 - 64]",            // w[i-16]
    "    mov  [rbp + rcx*4], edx",
    "    inc  ecx",
    "    cmp  ecx, 64",
    "    jb   oxp_sc_w1",
    "    mov  r8d,  [rdi + 0]",                    // a
    "    mov  r9d,  [rdi + 4]",                    // b
    "    mov  r10d, [rdi + 8]",                    // c
    "    mov  r11d, [rdi + 12]",                   // d
    "    mov  r12d, [rdi + 16]",                   // e
    "    mov  r13d, [rdi + 20]",                   // f
    "    mov  r14d, [rdi + 24]",                   // g
    "    mov  r15d, [rdi + 28]",                   // h
    "    lea  rsi, [rip + oxp_k]",
    "    xor  ebx, ebx",
    "oxp_sc_rnd:",
    // T1 = h + BSIG1(e) + CH(e,f,g) + K[i] + w[i]
    "    mov  eax, r12d",
    "    ror  eax, 6",
    "    mov  edx, r12d",
    "    ror  edx, 11",
    "    xor  eax, edx",
    "    mov  edx, r12d",
    "    ror  edx, 25",
    "    xor  eax, edx",
    "    add  eax, r15d",
    "    mov  edx, r12d",
    "    and  edx, r13d",
    "    mov  ecx, r12d",
    "    not  ecx",
    "    and  ecx, r14d",
    "    xor  edx, ecx",
    "    add  eax, edx",
    "    add  eax, [rsi + rbx*4]",
    "    add  eax, [rbp + rbx*4]",
    // T2 = BSIG0(a) + MAJ(a,b,c); rdi is on the stack, so edi is a free temp.
    "    mov  ecx, r8d",
    "    ror  ecx, 2",
    "    mov  edx, r8d",
    "    ror  edx, 13",
    "    xor  ecx, edx",
    "    mov  edx, r8d",
    "    ror  edx, 22",
    "    xor  ecx, edx",
    "    mov  edx, r8d",
    "    and  edx, r9d",
    "    mov  edi, r8d",
    "    and  edi, r10d",
    "    xor  edx, edi",
    "    mov  edi, r9d",
    "    and  edi, r10d",
    "    xor  edx, edi",
    "    add  ecx, edx",
    "    mov  r15d, r14d",
    "    mov  r14d, r13d",
    "    mov  r13d, r12d",
    "    lea  r12d, [r11 + rax]",
    "    mov  r11d, r10d",
    "    mov  r10d, r9d",
    "    mov  r9d, r8d",
    "    lea  r8d, [rax + rcx]",
    "    inc  ebx",
    "    cmp  ebx, 64",
    "    jb   oxp_sc_rnd",
    "    mov  rdi, [rsp + 256]",
    "    add  [rdi + 0], r8d",
    "    add  [rdi + 4], r9d",
    "    add  [rdi + 8], r10d",
    "    add  [rdi + 12], r11d",
    "    add  [rdi + 16], r12d",
    "    add  [rdi + 20], r13d",
    "    add  [rdi + 24], r14d",
    "    add  [rdi + 28], r15d",
    "    add  rsp, 256",
    "    pop  rdi",
    "    pop  r15",
    "    pop  r14",
    "    pop  r13",
    "    pop  r12",
    "    pop  rbp",
    "    pop  rbx",
    "    ret",

    // A caller-ABI door onto the SAME SHA-256 the verification uses, so the
    // shipped bytes — not a re-implementation of them — are what the hosted
    // tests exercise. Never called on the kexec path.
    ".globl oxide_purgatory_sha256",
    "oxide_purgatory_sha256:",                     // rdi = p, rsi = n, rdx = out
    "    push rbx",
    "    push rbp",
    "    push r12",
    "    push r13",
    "    push r14",
    "    push r15",
    "    sub  rsp, 144",
    "    mov  r12, rdi",
    "    mov  r13, rsi",
    "    mov  r14, rdx",
    "    mov  rdi, rsp",
    "    call oxp_sha_init",
    "    mov  rdi, rsp",
    "    mov  rsi, r12",
    "    mov  rdx, r13",
    "    call oxp_sha_update",
    "    mov  rdi, rsp",
    "    mov  rsi, r14",
    "    call oxp_sha_final",
    "    add  rsp, 144",
    "    pop  r15",
    "    pop  r14",
    "    pop  r13",
    "    pop  r12",
    "    pop  rbp",
    "    pop  rbx",
    "    ret",

    // Both stacks are carried as real bytes. `.org` is again the fit check:
    // code that outgrew its region cannot move the counter backwards.
    ".org 0x1000",
    "oxp_pstack:    .fill 4096, 1, 0",
    "oxp_pstack_end:",
    "oxp_nstack:    .fill 4096, 1, 0",
    ".org 0x3000",
    ".globl oxide_purgatory_blob_end",
    "oxide_purgatory_blob_end:",
    ); };
}

#[cfg(target_os = "oxide-kernel")]
purgatory_asm!(".section .rodata.oxide_purgatory,\"a\",@progbits");
#[cfg(not(target_os = "oxide-kernel"))]
purgatory_asm!(".section .text.oxide_purgatory,\"ax\",@progbits");

