[package]
name = "modules"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
hal  = { path = "../../arch/hal" }
hal-x86_64 = { path = "../../arch/hal-x86_64" }
hal-aarch64 = { path = "../../arch/hal-aarch64" }
klog = { path = "../../shared/klog" }
sync = { path = "../../shared/sync" }
elf  = { path = "../../shared/elf" }
pmm  = { path = "../mm-pmm" }
sched = { path = "../sched" }
timer = { path = "../timer" }
mmio-map = { path = "../mmio-map" }
arch-irq = { path = "../arch-irq" }
pci = { path = "../../drivers/pci" }
vfs = { path = "../vfs" }

[features]
default = []
hosted  = []
debug-modules = []
