[package]
name = "modules"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
hal  = { path = "../../arch/hal" }
hal-x86_64 = { path = "../../arch/hal-x86_64" }
hal-aarch64 = { path = "../../arch/hal-aarch64" }
klog = { path = "../../shared/klog" }
sync = { path = "../../shared/sync" }
elf  = { path = "../../shared/elf" }
crc  = { path = "../../shared/crc" }
crypt = { path = "../../shared/crypt" }
ext4 = { path = "../ext4" }
pmm  = { path = "../mm-pmm" }
sched = { path = "../sched" }
vmm = { path = "../mm-vmm" }
uaccess = { path = "../uaccess" }
timer = { path = "../timer" }
mmio-map = { path = "../mmio-map" }
arch-irq = { path = "../arch-irq" }
devfs = { path = "../devfs" }
drv = { path = "../../drivers/drv" }
pci = { path = "../../drivers/pci" }
vfs = { path = "../vfs" }
net = { path = "../net" }
block = { path = "../block" }
input = { path = "../input" }
tracefs = { path = "../tracefs" }
kernfs = { path = "../kernfs" }
syscall = { path = "../syscall" }

[features]
default = []
hosted  = ["net/hosted"]
debug-modules = []
