//! The synthetic ntdll export catalog: the names the kernel publishes and the
//! service each one selects.
//!
//! Split out of the page builder so the same table answers two questions: what
//! the page exports, and which service a shipped module's export name means
//! when its stub arrives at the syscall entry carrying a raw ordinal.

use super::{CHKSTK_INDEX, C_SPECIFIC_HANDLER_INDEX, DBG_BREAK_POINT_INDEX};

pub const NTDLL_EXPORTS: [&[u8]; 552] = [
    b"NtAllocateVirtualMemory", b"NtFreeVirtualMemory", b"NtProtectVirtualMemory", b"NtQueryVirtualMemory",
    b"NtTerminateProcess", b"NtCreateEvent", b"NtClose", b"NtSetEvent", b"NtResetEvent", b"NtWaitForSingleObject",
    b"NtCreateFile", b"NtOpenFile", b"NtReadFile", b"NtWriteFile", b"NtQueryInformationFile", b"NtSetInformationFile", b"NtQueryDirectoryFile", b"NtWaitForMultipleObjects",
    b"NtCreateSection", b"NtMapViewOfSection", b"NtUnmapViewOfSection", b"NtQueryInformationProcess", b"NtCreateThreadEx", b"NtTerminateThread", b"NtQueryInformationThread",
    b"RtlAllocateHeap", b"RtlFreeHeap", b"NtdllDefWindowProc_A", b"NtdllDefWindowProc_W", b"RtlReAllocateHeap", b"LdrResolveDelayLoadedAPI", b"RtlUnwind", b"NtCreateSemaphore", b"NtReleaseSemaphore", b"NtCreateMutant", b"NtReleaseMutant", b"NtQueryMutant", b"NtLockFile", b"NtUnlockFile", b"NtDuplicateObject", b"NtCreateTimer", b"NtSetTimer", b"NtCancelTimer", b"NtCreateIoCompletion", b"NtSetIoCompletion", b"NtRemoveIoCompletion", b"NtSignalAndWaitForSingleObject", b"NtOpenProcessToken", b"NtOpenThreadToken", b"NtQueryInformationToken", b"RtlInitUnicodeString", b"RtlInitUnicodeStringEx", b"NtQueryObject", b"RtlInitAnsiString", b"RtlInitAnsiStringEx", b"NtQuerySecurityObject", b"RtlQueryPerformanceCounter", b"RtlQueryPerformanceFrequency", b"NtRenameKey", b"NtSetSecurityObject", b"RtlAddAccessAllowedAce", b"RtlAddAccessAllowedAceEx", b"RtlAddAccessDeniedAce", b"RtlAddAccessDeniedAceEx", b"RtlAddAce", b"RtlAddAuditAccessAce", b"RtlAddAuditAccessAceEx", b"RtlCreateAcl", b"RtlCreateSecurityDescriptor", b"RtlCreateUnicodeStringFromAsciiz", b"RtlDosPathNameToNtPathName_U", b"RtlFreeUnicodeString", b"RtlGetAce", b"RtlGetControlSecurityDescriptor", b"RtlIsTextUnicode", b"RtlLengthSecurityDescriptor", b"RtlMakeSelfRelativeSD", b"RtlNtStatusToDosError", b"RtlQueryInformationAcl", b"RtlSelfRelativeToAbsoluteSD", b"RtlUniform", b"RtlDeleteCriticalSection", b"RtlEnterCriticalSection", b"RtlLeaveCriticalSection", b"_vsnprintf", b"RtlSizeHeap", b"RtlExitUserThread", b"RtlQueryUnbiasedInterruptTime", b"DbgUiGetThreadDebugObject", b"DbgUiIssueRemoteBreakin", b"LdrGetDllDirectory", b"LdrGetProcedureAddress", b"LdrSetDllDirectory", b"NtAddAtom", b"NtAssignProcessToJobObject", b"NtCreateJobObject", b"NtCreateMailslotFile", b"NtDeleteAtom", b"NtDeviceIoControlFile", b"NtFindAtom", b"NtFsControlFile", b"NtOpenJobObject", b"NtPowerInformation", b"NtQueryInformationAtom", b"NtQueryInformationJobObject", b"NtQuerySection", b"NtQuerySystemInformation", b"NtQuerySystemTime", b"NtSetInformationDebugObject", b"NtSetInformationJobObject", b"NtSetInformationProcess", b"NtSetInformationThread", b"NtSetThreadExecutionState", b"NtTerminateJobObject", b"RtlAcquirePebLock", b"RtlReleasePebLock", b"RtlAddAtomToAtomTable",
    b"RtlAnsiStringToUnicodeString", b"RtlCaptureContext", b"RtlCharToInteger", b"RtlCreateAtomTable", b"RtlCreateHeap", b"RtlCreateUnicodeString", b"RtlDeleteAtomFromAtomTable", b"RtlDeregisterWait", b"RtlDestroyAtomTable", b"RtlDestroyHeap", b"RtlDetermineDosPathNameType_U", b"RtlDosPathNameToNtPathName_U_WithStatus", b"RtlExitUserProcess", b"RtlGetProcessHeaps", b"RtlGetUserInfoHeap", b"RtlImageNtHeader", b"RtlInitializeCriticalSection", b"RtlInitializeCriticalSectionAndSpinCount", b"RtlInitializeCriticalSectionEx", b"RtlIsNameLegalDOS8Dot3", b"RtlLockHeap", b"RtlUnlockHeap", b"RtlLookupAtomInAtomTable", b"RtlOemStringToUnicodeString", b"RtlQueryAtomInAtomTable", b"RtlRegisterWait", b"RtlRestoreContext", b"RtlSetIoCompletionCallback", b"RtlGetLastWin32Error", b"RtlRestoreLastWin32Error", b"RtlSetLastWin32Error", b"RtlSetSearchPathMode", b"RtlSetUnhandledExceptionFilter", b"RtlSetUserValueHeap", b"RtlTimeFieldsToTime", b"RtlTimeToTimeFields", b"RtlTimeToSecondsSince1970", b"RtlUnicodeStringToAnsiSize", b"RtlUnicodeStringToAnsiString", b"RtlUnicodeStringToInteger", b"RtlUnicodeStringToOemSize", b"RtlUnicodeStringToOemString", b"RtlUnicodeToMultiByteN", b"RtlUnicodeToMultiByteSize", b"RtlUnicodeToOemN", b"RtlUpcaseUnicodeString", b"RtlUpperChar", b"_wcsicmp", b"_wcsnicmp", b"isalpha", b"islower", b"memcpy", b"memmove", b"memset", b"strcat", b"strchr", b"strcpy", b"strlen", b"strpbrk", b"strrchr", b"tolower", b"wcscat", b"wcschr", b"wcscmp", b"wcscpy", b"wcslen", b"wcsncmp", b"wcsrchr", b"wcstoul", b"__wine_dbg_header", b"__wine_dbg_output", b"__wine_dbg_strdup", b"RtlGUIDFromString", b"RtlRandom", b"wine_get_host_version", b"RtlInterlockedFlushSList", b"RtlInterlockedPushEntrySList", b"RtlTryEnterCriticalSection", b"RtlAreBitsClear", b"RtlAreBitsSet", b"RtlInitializeBitMap", b"RtlLookupFunctionEntry", b"RtlPcToFileHeader", b"RtlSetBits", b"RtlUnwindEx", b"_setjmp", b"_setjmpex", b"longjmp", b"__wine_dbg_get_channel_flags", b"LdrGetDllFullName", b"LdrLoadDll", b"LdrQueryImageFileExecutionOptions", b"NtCallbackReturn", b"NtOpenDirectoryObject",
    b"RtlFindActivationContextSectionString", b"RtlImageDirectoryEntryToData", b"RtlImageRvaToVa", b"RtlInitializeNtUserPfn", b"RtlMultiByteToUnicodeN", b"RtlMultiByteToUnicodeSize", b"RtlRetrieveNtUserPfn", b"RtlResetNtUserPfn", b"ApiSetQueryApiSetPresenceEx", b"DbgBreakPoint", b"DbgUiConnectToDbg", b"DbgUiContinue", b"DbgUiRemoteBreakin", b"DbgUiStopDebugging", b"DbgUiWaitStateChange", b"DbgUiConvertStateChangeStructure", b"DbgUiDebugActiveProcess", b"LdrAccessResource", b"LdrAddDllDirectory", b"LdrRemoveDllDirectory", b"LdrAddRefDll", b"LdrDisableThreadCalloutsForDll", b"LdrFindResourceDirectory_U", b"LdrFindResource_U", b"LdrGetDllHandleEx", b"LdrGetDllPath", b"LdrSetDefaultDllDirectories", b"LdrUnloadDll", b"NtAccessCheck", b"NtAdjustGroupsToken", b"NtAdjustPrivilegesToken", b"NtAllocateLocallyUniqueId", b"NtAllocateVirtualMemoryEx", b"NtCancelIoFile", b"NtCancelIoFileEx", b"NtCancelSynchronousIoFile", b"NtCompareObjects", b"NtConvertBetweenAuxiliaryCounterAndPerformanceCounter", b"NtCreateKey", b"NtCreateNamedPipeFile", b"NtCreateSectionEx",
    b"NtCreateSymbolicLinkObject",
    b"NtCreateUserProcess",
    b"NtDelayExecution",
    b"NtDeleteKey",
    b"NtDeleteValueKey",
    b"NtDuplicateToken",
    b"NtEnumerateKey",
    b"NtEnumerateValueKey",
    b"NtFilterToken",
    b"NtFlushBuffersFile",
    b"NtFlushInstructionCache",
    b"NtFlushKey",
    b"NtFlushVirtualMemory",
    b"NtGetContextThread",
    b"NtGetNlsSectionPtr",
    b"NtGetTickCount",
    b"NtGetWriteWatch",
    b"NtImpersonateAnonymousToken",
    b"NtIsProcessInJob",
    b"NtLoadKey",
    b"NtLockVirtualMemory",
    b"NtMakeTemporaryObject",
    b"NtMapViewOfSectionEx",
    b"NtNotifyChangeDirectoryFile",
    b"NtNotifyChangeKey",
    b"NtOpenEvent",
    b"NtOpenKey",
    b"NtOpenKeyEx",
    b"NtOpenMutant",
    b"NtOpenProcess",
    b"NtOpenSection",
    b"NtOpenSemaphore",
    b"NtOpenSymbolicLinkObject",
    b"NtOpenThread",
    b"NtOpenTimer",
    b"NtPrivilegeCheck",
    b"NtPulseEvent",
    b"NtQueryAttributesFile",
    b"NtQueryDefaultLocale",
    b"NtQueryDefaultUILanguage",
    b"NtQueryDirectoryObject",
    b"NtQueryFullAttributesFile",
    b"NtQueryInstallUILanguage",
    b"NtQueryKey",
    b"NtQueryPerformanceCounter",
    b"NtQuerySymbolicLinkObject",
    b"NtQuerySystemInformationEx",
    b"NtQueryValueKey",
    b"NtQueryVolumeInformationFile",
    b"NtQueueApcThread",
    b"NtQueueApcThreadEx2",
    b"NtRaiseException",
    b"NtReadFileScatter",
    b"NtReadVirtualMemory",
    b"NtRemoveIoCompletionEx",
    b"NtResetWriteWatch",
    b"NtResumeThread",
    b"NtSaveKey",
    b"NtSetContextThread",
    b"NtSetInformationObject",
    b"NtSetInformationToken",
    b"NtSetInformationVirtualMemory",
    b"NtSetSystemInformation",
    b"NtSetSystemTime",
    b"NtSetValueKey",
    b"NtSuspendThread",
    b"NtUnloadKey",
    b"NtUnlockVirtualMemory",
    b"NtUnmapViewOfSectionEx",
    b"NtWriteFileGather",
    b"NtWriteVirtualMemory",
    b"NtYieldExecution",
    b"RtlActivateActivationContext",
    b"RtlActivateActivationContextEx",
    b"RtlAddAccessAllowedObjectAce",
    b"RtlAddAccessDeniedObjectAce",
    b"RtlAddAuditAccessObjectAce",
    b"RtlAddMandatoryAce",
    b"RtlAddRefActivationContext",
    b"RtlAllocateAndInitializeSid",
    b"RtlAreAllAccessesGranted",
    b"RtlAreAnyAccessesGranted",
    b"RtlBarrier",
    b"RtlClearBits",
    b"RtlCompactHeap",
    b"RtlCompareUnicodeStrings",
    b"RtlConvertSidToUnicodeString",
    b"RtlConvertToAutoInheritSecurityObject",
    b"RtlCopyContext",
    b"RtlCopySid",
    b"RtlCreateActivationContext",
    b"RtlCreateEnvironment",
    b"RtlCreateProcessParametersEx",
    b"RtlCreateTimer",
    b"RtlCreateTimerQueue",
    b"RtlCreateUserStack",
    b"RtlDeactivateActivationContext",
    b"RtlReleaseActivationContext",
    b"RtlDeleteAce",
    b"RtlDeleteBarrier",
    b"RtlDeleteSecurityObject",
    b"RtlDeleteTimer",
    b"RtlDeleteTimerQueueEx",
    b"RtlDeregisterWaitEx",
    b"RtlDeriveCapabilitySidsFromName",
    b"RtlDestroyEnvironment",
    b"RtlDestroyProcessParameters",
    b"RtlDoesFileExists_U",
    b"RtlDosSearchPath_U",
    b"RtlDowncaseUnicodeChar",
    b"RtlDuplicateUnicodeString",
    b"RtlEqualPrefixSid",
    b"RtlEqualSid",
    b"RtlExpandEnvironmentStrings_U",
    b"RtlFindActivationContextSectionGuid",
    b"RtlFindClearBitsAndSet",
    b"RtlFindMessage",
    b"RtlFirstFreeAce",
    b"RtlFlsAlloc",
    b"RtlFlsFree",
    b"RtlFlsGetValue",
    b"RtlFlsSetValue",
    b"RtlFormatMessage",
    b"RtlFormatMessageEx",
    b"RtlFreeThreadActivationContextStack",
    b"RtlFreeActivationContextStack",
    b"RtlFreeAnsiString",
    b"RtlFreeSid",
    b"RtlFreeUserStack",
    b"RtlGetActiveActivationContext",
    b"RtlGetCurrentDirectory_U",
    b"RtlGetCurrentPeb",
    b"RtlGetDaclSecurityDescriptor",
    b"RtlGetEnabledExtendedFeatures",
    b"RtlGetExePath",
    b"RtlGetExtendedContextLength2",
    b"RtlGetExtendedFeaturesMask",
    b"RtlGetFullPathName_U",
    b"RtlGetGroupSecurityDescriptor",
    b"RtlGetLocaleFileMappingAddress",
    b"RtlGetNativeSystemInformation",
    b"RtlGetOwnerSecurityDescriptor",
    b"RtlGetProductInfo",
    b"RtlGetProcessPreferredUILanguages",
    b"RtlGetSaclSecurityDescriptor",
    b"RtlGetSearchPath",
    b"RtlGetSystemPreferredUILanguages",
    b"RtlGetSystemTimePrecise",
    b"RtlGetThreadErrorMode",
    b"RtlGetThreadPreferredUILanguages",
    b"RtlGetUserPreferredUILanguages",
    b"RtlGetVersion",
    b"RtlIdentifierAuthoritySid",
    b"RtlIdnToAscii",
    b"RtlIdnToNameprepUnicode",
    b"RtlIdnToUnicode",
    b"RtlImpersonateSelf",
    b"RtlInitBarrier",
    b"RtlInitCodePageTable",
    b"RtlInitializeExtendedContext2",
    b"RtlInitializeSid",
    b"RtlIsDosDeviceName_U",
    b"RtlIsNormalizedString",
    b"RtlIsProcessorFeaturePresent",
    b"RtlLengthRequiredSid",
    b"RtlLengthSid",
    b"RtlLocalTimeToSystemTime",
    b"RtlLocateExtendedFeature",
    b"RtlMapGenericMask",
    b"RtlNewSecurityObject",
    b"RtlNewSecurityObjectEx",
    b"RtlNewSecurityObjectWithMultipleInheritance",
    b"RtlNormalizeProcessParams",
    b"RtlNormalizeString",
    b"RtlOpenCurrentUser",
    b"RtlProcessFlsData",
    b"RtlQueryActivationContextApplicationSettings",
    b"RtlQueryDynamicTimeZoneInformation",
    b"RtlQueryEnvironmentVariable_U",
    b"RtlQueryHeapInformation",
    b"RtlQueryInformationActivationContext",
    b"RtlQueryTimeZoneInformation",
    b"RtlQueueWorkItem",
    b"RtlRaiseException",
    b"RtlRaiseStatus",
    b"RtlReleasePath",
    b"RtlRunOnceBeginInitialize",
    b"RtlRunOnceComplete",
    b"RtlRunOnceExecuteOnce",
    b"RtlSetControlSecurityDescriptor",
    b"RtlSetCurrentDirectory_U",
    b"RtlSetCurrentEnvironment",
    b"RtlSetDaclSecurityDescriptor",
    b"RtlSetEnvironmentVariable",
    b"RtlSetExtendedFeaturesMask",
    b"RtlSetGroupSecurityDescriptor",
    b"RtlSetOwnerSecurityDescriptor",
    b"RtlSetHeapInformation",
    b"RtlSetProcessPreferredUILanguages",
    b"RtlSetSaclSecurityDescriptor",
    b"RtlSetThreadErrorMode",
    b"RtlSetThreadPreferredUILanguages",
    b"RtlSetTimeZoneInformation",
    b"RtlSleepConditionVariableCS",
    b"RtlSleepConditionVariableSRW",
    b"RtlSubAuthorityCountSid",
    b"RtlSubAuthoritySid",
    b"RtlSystemTimeToLocalTime",
    b"RtlUTF8ToUnicodeN",
    b"RtlUnicodeToUTF8N",
    b"RtlUpdateTimer",
    b"RtlValidAcl",
    b"RtlValidSecurityDescriptor",
    b"RtlValidSid",
    b"RtlValidateHeap",
    b"RtlWaitOnAddress",
    b"RtlWakeAddressAll",
    b"RtlWakeAddressSingle",
    b"RtlWalkHeap",
    b"RtlWow64EnableFsRedirection",
    b"RtlWow64EnableFsRedirectionEx",
    b"RtlWow64GetProcessMachines",
    b"RtlWow64GetThreadContext",
    b"RtlWow64SetThreadContext",
    b"RtlZombifyActivationContext",
    b"TpAllocCleanupGroup",
    b"TpAllocIoCompletion",
    b"TpAllocPool",
    b"TpAllocTimer",
    b"TpAllocWait",
    b"TpAllocWork",
    b"TpCallbackMayRunLong",
    b"TpQueryPoolStackInformation",
    b"TpSetPoolStackInformation",
    b"TpSimpleTryPost",
    b"_strnicmp",
    b"_vsnwprintf",
    b"isalnum",
    b"iswalnum",
    b"isxdigit",
    b"memcmp",
    b"strcmp",
    b"strncmp",
    b"strtol",
    b"towupper",
    b"wcscspn",
    b"wcsnlen",
    b"wcspbrk",
    b"wcsspn",
    b"wcsstr",
    b"wcstol",
    b"LdrGetDllHandle",
    b"RtlFindExportedRoutineByName",
    b"NtTestAlert", b"NtContinue", b"NtMakePermanentObject", b"RtlDeNormalizeProcessParams", b"TpPostWork", b"TpReleaseWork", b"TpReleaseTimer", b"TpSetTimer",
    b"RtlIpv4AddressToStringA", b"RtlIpv4AddressToStringW", b"RtlIpv4AddressToStringExA", b"RtlIpv4AddressToStringExW", b"RtlIpv4StringToAddressA", b"RtlIpv4StringToAddressW", b"RtlIpv4StringToAddressExA", b"RtlIpv4StringToAddressExW", b"RtlIpv6AddressToStringA", b"RtlIpv6AddressToStringW", b"RtlIpv6AddressToStringExA", b"RtlIpv6AddressToStringExW", b"RtlIpv6StringToAddressA", b"RtlIpv6StringToAddressW", b"RtlIpv6StringToAddressExA", b"RtlIpv6StringToAddressExW", b"RtlNtStatusToDosErrorNoTeb", b"MD4Init", b"MD4Update", b"MD4Final",
    b"RtlAcquireSRWLockExclusive", b"RtlAcquireSRWLockShared", b"RtlReleaseSRWLockExclusive", b"RtlReleaseSRWLockShared", b"RtlTryAcquireSRWLockExclusive", b"RtlWakeConditionVariable",
    b"RtlAddFunctionTable", b"RtlDeleteFunctionTable", b"RtlInstallFunctionTableCallback",
    b"RtlCompareString", b"RtlCopyUnicodeString", b"RtlEqualUnicodeString", b"RtlComputeCrc32", b"RtlImageRvaToSection", b"RtlIsCurrentProcess", b"_wcslwr",
    // The counted-string initializer the runtime publishes under two names:
    // the byte-string entry is the ANSI one, so both reach one service.
    b"RtlInitString",
    // Compiler-emitted stack probe: not a service, a single `ret` on the page.
    b"__chkstk",
    // Language-specific handler for compiler-generated structured exception
    // handling: user-mode control flow over user-mode data that enters
    // user-mode filters, so it is machine code on the page rather than a trap.
    b"__C_specific_handler",
];

/// Service a catalog index selects, or `None` for the machine-code entries and
/// any index past the table.
/// # C: O(1)
pub fn service_for_index(index: usize) -> Option<syscall::nt::NtService> {
    match index {
            0 => Some(syscall::nt::NtService::AllocateVirtualMemory),
            1 => Some(syscall::nt::NtService::FreeVirtualMemory),
            2 => Some(syscall::nt::NtService::ProtectVirtualMemory),
            3 => Some(syscall::nt::NtService::QueryVirtualMemory),
            4 => Some(syscall::nt::NtService::TerminateProcess),
            5 => Some(syscall::nt::NtService::CreateEvent),
            6 => Some(syscall::nt::NtService::Close),
            7 => Some(syscall::nt::NtService::SetEvent),
            8 => Some(syscall::nt::NtService::ResetEvent),
            9 => Some(syscall::nt::NtService::WaitForSingleObject),
            10 => Some(syscall::nt::NtService::CreateFile),
            11 => Some(syscall::nt::NtService::OpenFile),
            12 => Some(syscall::nt::NtService::ReadFile),
            13 => Some(syscall::nt::NtService::WriteFile),
            14 => Some(syscall::nt::NtService::QueryInformationFile),
            15 => Some(syscall::nt::NtService::SetInformationFile),
            16 => Some(syscall::nt::NtService::QueryDirectoryFile),
            17 => Some(syscall::nt::NtService::WaitForMultipleObjects),
            18 => Some(syscall::nt::NtService::CreateSection),
            19 => Some(syscall::nt::NtService::MapViewOfSection),
            20 => Some(syscall::nt::NtService::UnmapViewOfSection),
            21 => Some(syscall::nt::NtService::QueryInformationProcess),
            22 => Some(syscall::nt::NtService::CreateThreadEx),
            23 => Some(syscall::nt::NtService::TerminateThread),
            24 => Some(syscall::nt::NtService::QueryInformationThread),
            25 => Some(syscall::nt::NtService::AllocateHeap),
            26 => Some(syscall::nt::NtService::FreeHeap),
            27 | 28 => Some(syscall::nt::NtService::DefaultWindowProc),
            29 => Some(syscall::nt::NtService::ReallocateHeap),
            30 => Some(syscall::nt::NtService::ResolveDelayLoadedApi),
            31 => Some(syscall::nt::NtService::RtlUnwind),
            32 => Some(syscall::nt::NtService::CreateSemaphore),
            33 => Some(syscall::nt::NtService::ReleaseSemaphore),
            34 => Some(syscall::nt::NtService::CreateMutant),
            35 => Some(syscall::nt::NtService::ReleaseMutant),
            36 => Some(syscall::nt::NtService::QueryMutant),
            37 => Some(syscall::nt::NtService::LockFile),
            38 => Some(syscall::nt::NtService::UnlockFile),
            39 => Some(syscall::nt::NtService::DuplicateObject),
            40 => Some(syscall::nt::NtService::CreateTimer),
            41 => Some(syscall::nt::NtService::SetTimer),
            42 => Some(syscall::nt::NtService::CancelTimer),
            43 => Some(syscall::nt::NtService::CreateIoCompletion),
            44 => Some(syscall::nt::NtService::SetIoCompletion),
            45 => Some(syscall::nt::NtService::RemoveIoCompletion),
            46 => Some(syscall::nt::NtService::SignalAndWait),
            47 => Some(syscall::nt::NtService::OpenProcessToken),
            48 => Some(syscall::nt::NtService::OpenThreadToken),
            49 => Some(syscall::nt::NtService::QueryToken),
            50 => Some(syscall::nt::NtService::RtlInitUnicodeString),
            51 => Some(syscall::nt::NtService::RtlInitUnicodeStringEx),
            52 => Some(syscall::nt::NtService::QueryObject),
            53 => Some(syscall::nt::NtService::RtlInitAnsiString),
            54 => Some(syscall::nt::NtService::RtlInitAnsiStringEx),
            55 => Some(syscall::nt::NtService::QuerySecurityObject),
            56 => Some(syscall::nt::NtService::RtlQueryPerformanceCounter),
            57 => Some(syscall::nt::NtService::RtlQueryPerformanceFrequency),
            58 => Some(syscall::nt::NtService::RenameKey),
            59 => Some(syscall::nt::NtService::SetSecurityObject),
            60 => Some(syscall::nt::NtService::RtlAddAccessAllowedAce),
            61 => Some(syscall::nt::NtService::RtlAddAccessAllowedAceEx),
            62 => Some(syscall::nt::NtService::RtlAddAccessDeniedAce),
            63 => Some(syscall::nt::NtService::RtlAddAccessDeniedAceEx),
            64 => Some(syscall::nt::NtService::RtlAddAce),
            65 => Some(syscall::nt::NtService::RtlAddAuditAccessAce),
            66 => Some(syscall::nt::NtService::RtlAddAuditAccessAceEx),
            67 => Some(syscall::nt::NtService::RtlCreateAcl),
            68 => Some(syscall::nt::NtService::RtlCreateSecurityDescriptor),
            69 => Some(syscall::nt::NtService::RtlCreateUnicodeStringFromAsciiz),
            70 => Some(syscall::nt::NtService::RtlDosPathNameToNtPathNameU),
            71 => Some(syscall::nt::NtService::RtlFreeUnicodeString),
            72 => Some(syscall::nt::NtService::RtlGetAce),
            73 => Some(syscall::nt::NtService::RtlGetControlSecurityDescriptor),
            74 => Some(syscall::nt::NtService::RtlIsTextUnicode),
            75 => Some(syscall::nt::NtService::RtlLengthSecurityDescriptor),
            76 => Some(syscall::nt::NtService::RtlMakeSelfRelativeSD),
            77 => Some(syscall::nt::NtService::RtlNtStatusToDosError),
            78 => Some(syscall::nt::NtService::RtlQueryInformationAcl),
            79 => Some(syscall::nt::NtService::RtlSelfRelativeToAbsoluteSD),
            80 => Some(syscall::nt::NtService::RtlUniform),
            81 => Some(syscall::nt::NtService::RtlDeleteCriticalSection),
            82 => Some(syscall::nt::NtService::RtlEnterCriticalSection),
            83 => Some(syscall::nt::NtService::RtlLeaveCriticalSection),
            84 => Some(syscall::nt::NtService::Vsnprintf),
            85 => Some(syscall::nt::NtService::RtlSizeHeap),
            86 => Some(syscall::nt::NtService::RtlExitUserThread),
            87 => Some(syscall::nt::NtService::RtlQueryUnbiasedInterruptTime),
            88 => Some(syscall::nt::NtService::DbgUiGetThreadDebugObject),
            89 => Some(syscall::nt::NtService::DbgUiIssueRemoteBreakin),
            90 => Some(syscall::nt::NtService::LdrGetDllDirectory),
            91 => Some(syscall::nt::NtService::LdrGetProcedureAddress),
            92 => Some(syscall::nt::NtService::LdrSetDllDirectory),
            93 => Some(syscall::nt::NtService::AddAtom),
            94 => Some(syscall::nt::NtService::AssignProcessToJobObject),
            95 => Some(syscall::nt::NtService::CreateJobObject),
            96 => Some(syscall::nt::NtService::CreateMailslotFile),
            97 => Some(syscall::nt::NtService::DeleteAtom),
            98 => Some(syscall::nt::NtService::DeviceIoControlFile),
            99 => Some(syscall::nt::NtService::FindAtom),
            100 => Some(syscall::nt::NtService::FsControlFile),
            101 => Some(syscall::nt::NtService::OpenJobObject),
            102 => Some(syscall::nt::NtService::PowerInformation),
            103 => Some(syscall::nt::NtService::QueryInformationAtom),
            104 => Some(syscall::nt::NtService::QueryInformationJobObject),
            105 => Some(syscall::nt::NtService::QuerySection),
            106 => Some(syscall::nt::NtService::QuerySystemInformation),
            107 => Some(syscall::nt::NtService::QuerySystemTime),
            108 => Some(syscall::nt::NtService::SetInformationDebugObject),
            109 => Some(syscall::nt::NtService::SetInformationJobObject),
            110 => Some(syscall::nt::NtService::SetInformationProcess),
            111 => Some(syscall::nt::NtService::SetInformationThread),
            112 => Some(syscall::nt::NtService::SetThreadExecutionState), 113 => Some(syscall::nt::NtService::TerminateJobObject),
            114 => Some(syscall::nt::NtService::RtlAcquirePebLock), 115 => Some(syscall::nt::NtService::RtlReleasePebLock), 116 => Some(syscall::nt::NtService::RtlAddAtomToAtomTable), 117 => Some(syscall::nt::NtService::RtlAnsiStringToUnicodeString), 118 => Some(syscall::nt::NtService::RtlCaptureContext), 119 => Some(syscall::nt::NtService::RtlCharToInteger), 120 => Some(syscall::nt::NtService::RtlCreateAtomTable), 121 => Some(syscall::nt::NtService::RtlCreateHeap), 122 => Some(syscall::nt::NtService::RtlCreateUnicodeString), 123 => Some(syscall::nt::NtService::RtlDeleteAtomFromAtomTable), 124 => Some(syscall::nt::NtService::RtlDeregisterWait), 125 => Some(syscall::nt::NtService::RtlDestroyAtomTable), 126 => Some(syscall::nt::NtService::RtlDestroyHeap), 127 => Some(syscall::nt::NtService::RtlDetermineDosPathNameTypeU), 128 => Some(syscall::nt::NtService::RtlDosPathNameToNtPathNameUWithStatus), 129 => Some(syscall::nt::NtService::RtlExitUserProcess), 130 => Some(syscall::nt::NtService::RtlGetProcessHeaps), 131 => Some(syscall::nt::NtService::RtlGetUserInfoHeap), 132 => Some(syscall::nt::NtService::RtlImageNtHeader), 133 => Some(syscall::nt::NtService::RtlInitializeCriticalSection), 134 => Some(syscall::nt::NtService::RtlInitializeCriticalSectionAndSpinCount), 135 => Some(syscall::nt::NtService::RtlInitializeCriticalSectionEx), 136 => Some(syscall::nt::NtService::RtlIsNameLegalDOS8Dot3), 137 => Some(syscall::nt::NtService::RtlLockHeap), 138 => Some(syscall::nt::NtService::RtlUnlockHeap), 139 => Some(syscall::nt::NtService::RtlLookupAtomInAtomTable), 140 => Some(syscall::nt::NtService::RtlOemStringToUnicodeString), 141 => Some(syscall::nt::NtService::RtlQueryAtomInAtomTable), 142 => Some(syscall::nt::NtService::RtlRegisterWait), 143 => Some(syscall::nt::NtService::RtlRestoreContext), 144 => Some(syscall::nt::NtService::RtlSetIoCompletionCallback), 145 => Some(syscall::nt::NtService::RtlGetLastWin32Error), 146 => Some(syscall::nt::NtService::RtlRestoreLastWin32Error), 147 => Some(syscall::nt::NtService::RtlSetLastWin32Error), 148 => Some(syscall::nt::NtService::RtlSetSearchPathMode), 149 => Some(syscall::nt::NtService::RtlSetUnhandledExceptionFilter), 150 => Some(syscall::nt::NtService::RtlSetUserValueHeap), 151 => Some(syscall::nt::NtService::RtlTimeFieldsToTime), 152 => Some(syscall::nt::NtService::RtlTimeToTimeFields), 153 => Some(syscall::nt::NtService::RtlTimeToSecondsSince1970), 154 => Some(syscall::nt::NtService::RtlUnicodeStringToAnsiSize), 155 => Some(syscall::nt::NtService::RtlUnicodeStringToAnsiString), 156 => Some(syscall::nt::NtService::RtlUnicodeStringToInteger), 157 => Some(syscall::nt::NtService::RtlUnicodeStringToOemSize), 158 => Some(syscall::nt::NtService::RtlUnicodeStringToOemString), 159 => Some(syscall::nt::NtService::RtlUnicodeToMultiByteN),
            160 => Some(syscall::nt::NtService::RtlUnicodeToMultiByteSize),
            161 => Some(syscall::nt::NtService::RtlUnicodeToOemN),
            162 => Some(syscall::nt::NtService::RtlUpcaseUnicodeString),
            163 => Some(syscall::nt::NtService::RtlUpperChar),
            164 => Some(syscall::nt::NtService::Wcsicmp),
            165 => Some(syscall::nt::NtService::Wcsnicmp),
            166 => Some(syscall::nt::NtService::Isalpha),
            167 => Some(syscall::nt::NtService::Islower),
            168 => Some(syscall::nt::NtService::Memcpy),
            169 => Some(syscall::nt::NtService::Memmove),
            170 => Some(syscall::nt::NtService::Memset),
            171 => Some(syscall::nt::NtService::Strcat),
            172 => Some(syscall::nt::NtService::Strchr),
            173 => Some(syscall::nt::NtService::Strcpy),
            174 => Some(syscall::nt::NtService::Strlen),
            175 => Some(syscall::nt::NtService::Strpbrk),
            176 => Some(syscall::nt::NtService::Strrchr),
            177 => Some(syscall::nt::NtService::Tolower),
            178 => Some(syscall::nt::NtService::Wcscat),
            179 => Some(syscall::nt::NtService::Wcschr),
            180 => Some(syscall::nt::NtService::Wcscmp),
            181 => Some(syscall::nt::NtService::Wcscpy),
            182 => Some(syscall::nt::NtService::Wcslen),
            183 => Some(syscall::nt::NtService::Wcsncmp),
            184 => Some(syscall::nt::NtService::Wcsrchr),
            185 => Some(syscall::nt::NtService::Wcstoul),
            186 => Some(syscall::nt::NtService::WineDbgHeader),
            187 => Some(syscall::nt::NtService::WineDbgOutput),
            188 => Some(syscall::nt::NtService::WineDbgStrdup),
            189 => Some(syscall::nt::NtService::RtlGUIDFromString),
            190 => Some(syscall::nt::NtService::RtlRandom),
            191 => Some(syscall::nt::NtService::WineGetHostVersion),
            192 => Some(syscall::nt::NtService::RtlInterlockedFlushSList),
            193 => Some(syscall::nt::NtService::RtlInterlockedPushEntrySList),
            194 => Some(syscall::nt::NtService::RtlTryEnterCriticalSection),
            195 => Some(syscall::nt::NtService::RtlAreBitsClear),
            196 => Some(syscall::nt::NtService::RtlAreBitsSet),
            197 => Some(syscall::nt::NtService::RtlInitializeBitMap),
            198 => Some(syscall::nt::NtService::RtlLookupFunctionEntry),
            199 => Some(syscall::nt::NtService::RtlPcToFileHeader),
            200 => Some(syscall::nt::NtService::RtlSetBits),
            201 => Some(syscall::nt::NtService::RtlUnwindEx),
            202 => Some(syscall::nt::NtService::Setjmp),
            203 => Some(syscall::nt::NtService::Setjmpex),
            204 => Some(syscall::nt::NtService::Longjmp),
            205 => Some(syscall::nt::NtService::WineDbgGetChannelFlags),
            206 => Some(syscall::nt::NtService::LdrGetDllFullName),
            207 => Some(syscall::nt::NtService::LdrLoadDll),
            208 => Some(syscall::nt::NtService::LdrQueryImageFileExecutionOptions),
            209 => Some(syscall::nt::NtService::CallbackReturn),
            210 => Some(syscall::nt::NtService::OpenDirectoryObject),
            211 => Some(syscall::nt::NtService::RtlFindActivationContextSectionString),
            212 => Some(syscall::nt::NtService::RtlImageDirectoryEntryToData),
            213 => Some(syscall::nt::NtService::RtlImageRvaToVa),
            214 => Some(syscall::nt::NtService::RtlInitializeNtUserPfn),
            215 => Some(syscall::nt::NtService::RtlMultiByteToUnicodeN),
            216 => Some(syscall::nt::NtService::RtlMultiByteToUnicodeSize),
            217 => Some(syscall::nt::NtService::RtlRetrieveNtUserPfn),
            218 => Some(syscall::nt::NtService::RtlResetNtUserPfn),
            219 => Some(syscall::nt::NtService::ApiSetQueryApiSetPresenceEx),
            221 => Some(syscall::nt::NtService::DbgUiConnectToDbg),
            222 => Some(syscall::nt::NtService::DbgUiContinue),
            223 => Some(syscall::nt::NtService::DbgUiRemoteBreakin),
            224 => Some(syscall::nt::NtService::DbgUiStopDebugging),
            225 => Some(syscall::nt::NtService::DbgUiWaitStateChange),
            226 => Some(syscall::nt::NtService::DbgUiConvertStateChangeStructure),
            227 => Some(syscall::nt::NtService::DbgUiDebugActiveProcess),
            228 => Some(syscall::nt::NtService::LdrAccessResource),
            229 => Some(syscall::nt::NtService::LdrAddDllDirectory),
            230 => Some(syscall::nt::NtService::LdrRemoveDllDirectory),
            231 => Some(syscall::nt::NtService::LdrAddRefDll),
            232 => Some(syscall::nt::NtService::LdrDisableThreadCalloutsForDll),
            233 => Some(syscall::nt::NtService::LdrFindResourceDirectory),
            234 => Some(syscall::nt::NtService::LdrFindResource),
            235 => Some(syscall::nt::NtService::LdrGetDllHandleEx),
            236 => Some(syscall::nt::NtService::LdrGetDllPath),
            237 => Some(syscall::nt::NtService::LdrSetDefaultDllDirectories),
            238 => Some(syscall::nt::NtService::LdrUnloadDll),
            239 => Some(syscall::nt::NtService::NtAccessCheck),
            240 => Some(syscall::nt::NtService::NtAdjustGroupsToken),
            241 => Some(syscall::nt::NtService::NtAdjustPrivilegesToken),
            242 => Some(syscall::nt::NtService::NtAllocateLocallyUniqueId),
            243 => Some(syscall::nt::NtService::NtAllocateVirtualMemoryEx),
            244 => Some(syscall::nt::NtService::NtCancelIoFile),
            245 => Some(syscall::nt::NtService::NtCancelIoFileEx),
            246 => Some(syscall::nt::NtService::NtCancelSynchronousIoFile),
            247 => Some(syscall::nt::NtService::NtCompareObjects),
            248 => Some(syscall::nt::NtService::NtConvertBetweenAuxiliaryCounterAndPerformanceCounter),
            249 => Some(syscall::nt::NtService::CreateKey),
            250 => Some(syscall::nt::NtService::NtCreateNamedPipeFile),
            251 => Some(syscall::nt::NtService::NtCreateSectionEx),
            252 => Some(syscall::nt::NtService::NtCreateSymbolicLinkObject),
            253 => Some(syscall::nt::NtService::NtCreateUserProcess),
            254 => Some(syscall::nt::NtService::NtDelayExecution),
            255 => Some(syscall::nt::NtService::NtDeleteKey),
            256 => Some(syscall::nt::NtService::NtDeleteValueKey),
            257 => Some(syscall::nt::NtService::NtDuplicateToken),
            258 => Some(syscall::nt::NtService::NtEnumerateKey),
            259 => Some(syscall::nt::NtService::NtEnumerateValueKey),
            260 => Some(syscall::nt::NtService::NtFilterToken),
            261 => Some(syscall::nt::NtService::NtFlushBuffersFile),
            262 => Some(syscall::nt::NtService::NtFlushInstructionCache),
            263 => Some(syscall::nt::NtService::NtFlushKey),
            264 => Some(syscall::nt::NtService::NtFlushVirtualMemory),
            265 => Some(syscall::nt::NtService::NtGetContextThread),
            266 => Some(syscall::nt::NtService::NtGetNlsSectionPtr),
            267 => Some(syscall::nt::NtService::NtGetTickCount),
            268 => Some(syscall::nt::NtService::NtGetWriteWatch),
            269 => Some(syscall::nt::NtService::NtImpersonateAnonymousToken),
            270 => Some(syscall::nt::NtService::NtIsProcessInJob),
            271 => Some(syscall::nt::NtService::NtLoadKey),
            272 => Some(syscall::nt::NtService::NtLockVirtualMemory),
            273 => Some(syscall::nt::NtService::NtMakeTemporaryObject),
            274 => Some(syscall::nt::NtService::NtMapViewOfSectionEx),
            275 => Some(syscall::nt::NtService::NtNotifyChangeDirectoryFile),
            276 => Some(syscall::nt::NtService::NtNotifyChangeKey),
            277 => Some(syscall::nt::NtService::NtOpenEvent),
            278 => Some(syscall::nt::NtService::OpenKey),
            279 => Some(syscall::nt::NtService::NtOpenKeyEx),
            280 => Some(syscall::nt::NtService::NtOpenMutant),
            281 => Some(syscall::nt::NtService::NtOpenProcess),
            282 => Some(syscall::nt::NtService::NtOpenSection),
            283 => Some(syscall::nt::NtService::NtOpenSemaphore),
            284 => Some(syscall::nt::NtService::NtOpenSymbolicLinkObject),
            285 => Some(syscall::nt::NtService::NtOpenThread),
            286 => Some(syscall::nt::NtService::NtOpenTimer),
            287 => Some(syscall::nt::NtService::NtPrivilegeCheck),
            288 => Some(syscall::nt::NtService::NtPulseEvent),
            289 => Some(syscall::nt::NtService::NtQueryAttributesFile),
            290 => Some(syscall::nt::NtService::NtQueryDefaultLocale),
            291 => Some(syscall::nt::NtService::NtQueryDefaultUILanguage),
            292 => Some(syscall::nt::NtService::NtQueryDirectoryObject),
            293 => Some(syscall::nt::NtService::NtQueryFullAttributesFile),
            294 => Some(syscall::nt::NtService::NtQueryInstallUILanguage),
            295 => Some(syscall::nt::NtService::NtQueryKey),
            296 => Some(syscall::nt::NtService::NtQueryPerformanceCounter),
            297 => Some(syscall::nt::NtService::NtQuerySymbolicLinkObject),
            298 => Some(syscall::nt::NtService::NtQuerySystemInformationEx),
            299 => Some(syscall::nt::NtService::NtQueryValueKey),
            300 => Some(syscall::nt::NtService::NtQueryVolumeInformationFile),
            301 => Some(syscall::nt::NtService::NtQueueApcThread),
            302 => Some(syscall::nt::NtService::NtQueueApcThreadEx2),
            303 => Some(syscall::nt::NtService::NtRaiseException),
            304 => Some(syscall::nt::NtService::NtReadFileScatter),
            305 => Some(syscall::nt::NtService::NtReadVirtualMemory),
            306 => Some(syscall::nt::NtService::NtRemoveIoCompletionEx),
            307 => Some(syscall::nt::NtService::NtResetWriteWatch),
            308 => Some(syscall::nt::NtService::NtResumeThread),
            309 => Some(syscall::nt::NtService::NtSaveKey),
            310 => Some(syscall::nt::NtService::NtSetContextThread),
            311 => Some(syscall::nt::NtService::NtSetInformationObject),
            312 => Some(syscall::nt::NtService::NtSetInformationToken),
            313 => Some(syscall::nt::NtService::NtSetInformationVirtualMemory),
            314 => Some(syscall::nt::NtService::NtSetSystemInformation),
            315 => Some(syscall::nt::NtService::NtSetSystemTime),
            316 => Some(syscall::nt::NtService::NtSetValueKey),
            317 => Some(syscall::nt::NtService::NtSuspendThread),
            318 => Some(syscall::nt::NtService::NtUnloadKey),
            319 => Some(syscall::nt::NtService::NtUnlockVirtualMemory),
            320 => Some(syscall::nt::NtService::NtUnmapViewOfSectionEx),
            321 => Some(syscall::nt::NtService::NtWriteFileGather),
            322 => Some(syscall::nt::NtService::NtWriteVirtualMemory),
            323 => Some(syscall::nt::NtService::NtYieldExecution),
            324 => Some(syscall::nt::NtService::RtlActivateActivationContext),
            325 => Some(syscall::nt::NtService::RtlActivateActivationContextEx),
            326 => Some(syscall::nt::NtService::RtlAddAccessAllowedObjectAce),
            327 => Some(syscall::nt::NtService::RtlAddAccessDeniedObjectAce),
            328 => Some(syscall::nt::NtService::RtlAddAuditAccessObjectAce),
            329 => Some(syscall::nt::NtService::RtlAddMandatoryAce),
            330 => Some(syscall::nt::NtService::RtlAddRefActivationContext),
            331 => Some(syscall::nt::NtService::RtlAllocateAndInitializeSid),
            332 => Some(syscall::nt::NtService::RtlAreAllAccessesGranted),
            333 => Some(syscall::nt::NtService::RtlAreAnyAccessesGranted),
            334 => Some(syscall::nt::NtService::RtlBarrier),
            335 => Some(syscall::nt::NtService::RtlClearBits),
            336 => Some(syscall::nt::NtService::RtlCompactHeap),
            337 => Some(syscall::nt::NtService::RtlCompareUnicodeStrings),
            338 => Some(syscall::nt::NtService::RtlConvertSidToUnicodeString),
            339 => Some(syscall::nt::NtService::RtlConvertToAutoInheritSecurityObject),
            340 => Some(syscall::nt::NtService::RtlCopyContext),
            341 => Some(syscall::nt::NtService::RtlCopySid),
            342 => Some(syscall::nt::NtService::RtlCreateActivationContext),
            343 => Some(syscall::nt::NtService::RtlCreateEnvironment),
            344 => Some(syscall::nt::NtService::RtlCreateProcessParametersEx),
            345 => Some(syscall::nt::NtService::RtlCreateTimer),
            346 => Some(syscall::nt::NtService::RtlCreateTimerQueue),
            347 => Some(syscall::nt::NtService::RtlCreateUserStack),
            348 => Some(syscall::nt::NtService::RtlDeactivateActivationContext),
            349 => Some(syscall::nt::NtService::RtlReleaseActivationContext),
            350 => Some(syscall::nt::NtService::RtlDeleteAce),
            351 => Some(syscall::nt::NtService::RtlDeleteBarrier),
            352 => Some(syscall::nt::NtService::RtlDeleteSecurityObject),
            353 => Some(syscall::nt::NtService::RtlDeleteTimer),
            354 => Some(syscall::nt::NtService::RtlDeleteTimerQueueEx),
            355 => Some(syscall::nt::NtService::RtlDeregisterWaitEx),
            356 => Some(syscall::nt::NtService::RtlDeriveCapabilitySidsFromName),
            357 => Some(syscall::nt::NtService::RtlDestroyEnvironment),
            358 => Some(syscall::nt::NtService::RtlDestroyProcessParameters),
            359 => Some(syscall::nt::NtService::RtlDoesFileExistsU),
            360 => Some(syscall::nt::NtService::RtlDosSearchPathU),
            361 => Some(syscall::nt::NtService::RtlDowncaseUnicodeChar),
            362 => Some(syscall::nt::NtService::RtlDuplicateUnicodeString),
            363 => Some(syscall::nt::NtService::RtlEqualPrefixSid),
            364 => Some(syscall::nt::NtService::RtlEqualSid),
            365 => Some(syscall::nt::NtService::RtlExpandEnvironmentStringsU),
            366 => Some(syscall::nt::NtService::RtlFindActivationContextSectionGuid),
            367 => Some(syscall::nt::NtService::RtlFindClearBitsAndSet),
            368 => Some(syscall::nt::NtService::RtlFindMessage),
            369 => Some(syscall::nt::NtService::RtlFirstFreeAce),
            370 => Some(syscall::nt::NtService::RtlFlsAlloc),
            371 => Some(syscall::nt::NtService::RtlFlsFree),
            372 => Some(syscall::nt::NtService::RtlFlsGetValue),
            373 => Some(syscall::nt::NtService::RtlFlsSetValue),
            374 => Some(syscall::nt::NtService::RtlFormatMessage),
            375 => Some(syscall::nt::NtService::RtlFormatMessageEx),
            376 => Some(syscall::nt::NtService::RtlFreeThreadActivationContextStack),
            377 => Some(syscall::nt::NtService::RtlFreeActivationContextStack),
            378 => Some(syscall::nt::NtService::RtlFreeAnsiString),
            379 => Some(syscall::nt::NtService::RtlFreeSid),
            380 => Some(syscall::nt::NtService::RtlFreeUserStack),
            381 => Some(syscall::nt::NtService::RtlGetActiveActivationContext),
            382 => Some(syscall::nt::NtService::RtlGetCurrentDirectoryU),
            383 => Some(syscall::nt::NtService::RtlGetCurrentPeb),
            384 => Some(syscall::nt::NtService::RtlGetDaclSecurityDescriptor),
            385 => Some(syscall::nt::NtService::RtlGetEnabledExtendedFeatures),
            386 => Some(syscall::nt::NtService::RtlGetExePath),
            387 => Some(syscall::nt::NtService::RtlGetExtendedContextLength2),
            388 => Some(syscall::nt::NtService::RtlGetExtendedFeaturesMask),
            389 => Some(syscall::nt::NtService::RtlGetFullPathNameU),
            390 => Some(syscall::nt::NtService::RtlGetGroupSecurityDescriptor),
            391 => Some(syscall::nt::NtService::RtlGetLocaleFileMappingAddress),
            392 => Some(syscall::nt::NtService::RtlGetNativeSystemInformation),
            393 => Some(syscall::nt::NtService::RtlGetOwnerSecurityDescriptor),
            394 => Some(syscall::nt::NtService::RtlGetProductInfo),
            395 => Some(syscall::nt::NtService::RtlGetProcessPreferredUILanguages),
            396 => Some(syscall::nt::NtService::RtlGetSaclSecurityDescriptor),
            397 => Some(syscall::nt::NtService::RtlGetSearchPath),
            398 => Some(syscall::nt::NtService::RtlGetSystemPreferredUILanguages),
            399 => Some(syscall::nt::NtService::RtlGetSystemTimePrecise),
            400 => Some(syscall::nt::NtService::RtlGetThreadErrorMode),
            401 => Some(syscall::nt::NtService::RtlGetThreadPreferredUILanguages),
            402 => Some(syscall::nt::NtService::RtlGetUserPreferredUILanguages),
            403 => Some(syscall::nt::NtService::RtlGetVersion),
            404 => Some(syscall::nt::NtService::RtlIdentifierAuthoritySid),
            405 => Some(syscall::nt::NtService::RtlIdnToAscii),
            406 => Some(syscall::nt::NtService::RtlIdnToNameprepUnicode),
            407 => Some(syscall::nt::NtService::RtlIdnToUnicode),
            408 => Some(syscall::nt::NtService::RtlImpersonateSelf),
            409 => Some(syscall::nt::NtService::RtlInitBarrier),
            410 => Some(syscall::nt::NtService::RtlInitCodePageTable),
            411 => Some(syscall::nt::NtService::RtlInitializeExtendedContext2),
            412 => Some(syscall::nt::NtService::RtlInitializeSid),
            413 => Some(syscall::nt::NtService::RtlIsDosDeviceNameU),
            414 => Some(syscall::nt::NtService::RtlIsNormalizedString),
            415 => Some(syscall::nt::NtService::RtlIsProcessorFeaturePresent),
            416 => Some(syscall::nt::NtService::RtlLengthRequiredSid),
            417 => Some(syscall::nt::NtService::RtlLengthSid),
            418 => Some(syscall::nt::NtService::RtlLocalTimeToSystemTime),
            419 => Some(syscall::nt::NtService::RtlLocateExtendedFeature),
            420 => Some(syscall::nt::NtService::RtlMapGenericMask),
            421 => Some(syscall::nt::NtService::RtlNewSecurityObject),
            422 => Some(syscall::nt::NtService::RtlNewSecurityObjectEx),
            423 => Some(syscall::nt::NtService::RtlNewSecurityObjectWithMultipleInheritance),
            424 => Some(syscall::nt::NtService::RtlNormalizeProcessParams),
            425 => Some(syscall::nt::NtService::RtlNormalizeString),
            426 => Some(syscall::nt::NtService::RtlOpenCurrentUser),
            427 => Some(syscall::nt::NtService::RtlProcessFlsData),
            428 => Some(syscall::nt::NtService::RtlQueryActivationContextApplicationSettings),
            429 => Some(syscall::nt::NtService::RtlQueryDynamicTimeZoneInformation),
            430 => Some(syscall::nt::NtService::RtlQueryEnvironmentVariableU),
            431 => Some(syscall::nt::NtService::RtlQueryHeapInformation),
            432 => Some(syscall::nt::NtService::RtlQueryInformationActivationContext),
            433 => Some(syscall::nt::NtService::RtlQueryTimeZoneInformation),
            434 => Some(syscall::nt::NtService::RtlQueueWorkItem),
            435 => Some(syscall::nt::NtService::RtlRaiseException),
            436 => Some(syscall::nt::NtService::RtlRaiseStatus),
            437 => Some(syscall::nt::NtService::RtlReleasePath),
            438 => Some(syscall::nt::NtService::RtlRunOnceBeginInitialize),
            439 => Some(syscall::nt::NtService::RtlRunOnceComplete),
            440 => Some(syscall::nt::NtService::RtlRunOnceExecuteOnce),
            441 => Some(syscall::nt::NtService::RtlSetControlSecurityDescriptor),
            442 => Some(syscall::nt::NtService::RtlSetCurrentDirectoryU),
            443 => Some(syscall::nt::NtService::RtlSetCurrentEnvironment),
            444 => Some(syscall::nt::NtService::RtlSetDaclSecurityDescriptor),
            445 => Some(syscall::nt::NtService::RtlSetEnvironmentVariable),
            446 => Some(syscall::nt::NtService::RtlSetExtendedFeaturesMask),
            447 => Some(syscall::nt::NtService::RtlSetGroupSecurityDescriptor),
            448 => Some(syscall::nt::NtService::RtlSetOwnerSecurityDescriptor),
            449 => Some(syscall::nt::NtService::RtlSetHeapInformation),
            450 => Some(syscall::nt::NtService::RtlSetProcessPreferredUILanguages),
            451 => Some(syscall::nt::NtService::RtlSetSaclSecurityDescriptor),
            452 => Some(syscall::nt::NtService::RtlSetThreadErrorMode),
            453 => Some(syscall::nt::NtService::RtlSetThreadPreferredUILanguages),
            454 => Some(syscall::nt::NtService::RtlSetTimeZoneInformation),
            455 => Some(syscall::nt::NtService::RtlSleepConditionVariableCS),
            456 => Some(syscall::nt::NtService::RtlSleepConditionVariableSRW),
            457 => Some(syscall::nt::NtService::RtlSubAuthorityCountSid),
            458 => Some(syscall::nt::NtService::RtlSubAuthoritySid),
            459 => Some(syscall::nt::NtService::RtlSystemTimeToLocalTime),
            460 => Some(syscall::nt::NtService::RtlUTF8ToUnicodeN),
            461 => Some(syscall::nt::NtService::RtlUnicodeToUTF8N),
            462 => Some(syscall::nt::NtService::RtlUpdateTimer),
            463 => Some(syscall::nt::NtService::RtlValidAcl),
            464 => Some(syscall::nt::NtService::RtlValidSecurityDescriptor),
            465 => Some(syscall::nt::NtService::RtlValidSid),
            466 => Some(syscall::nt::NtService::RtlValidateHeap),
            467 => Some(syscall::nt::NtService::RtlWaitOnAddress),
            468 => Some(syscall::nt::NtService::RtlWakeAddressAll),
            469 => Some(syscall::nt::NtService::RtlWakeAddressSingle),
            470 => Some(syscall::nt::NtService::RtlWalkHeap),
            471 => Some(syscall::nt::NtService::RtlWow64EnableFsRedirection),
            472 => Some(syscall::nt::NtService::RtlWow64EnableFsRedirectionEx),
            473 => Some(syscall::nt::NtService::RtlWow64GetProcessMachines),
            474 => Some(syscall::nt::NtService::RtlWow64GetThreadContext),
            475 => Some(syscall::nt::NtService::RtlWow64SetThreadContext),
            476 => Some(syscall::nt::NtService::RtlZombifyActivationContext),
            477 => Some(syscall::nt::NtService::TpAllocCleanupGroup),
            478 => Some(syscall::nt::NtService::TpAllocIoCompletion),
            479 => Some(syscall::nt::NtService::TpAllocPool),
            480 => Some(syscall::nt::NtService::TpAllocTimer),
            481 => Some(syscall::nt::NtService::TpAllocWait),
            482 => Some(syscall::nt::NtService::TpAllocWork),
            483 => Some(syscall::nt::NtService::TpCallbackMayRunLong),
            484 => Some(syscall::nt::NtService::TpQueryPoolStackInformation),
            485 => Some(syscall::nt::NtService::TpSetPoolStackInformation),
            486 => Some(syscall::nt::NtService::TpSimpleTryPost),
            487 => Some(syscall::nt::NtService::Strnicmp),
            488 => Some(syscall::nt::NtService::Vsnwprintf),
            489 => Some(syscall::nt::NtService::Isalnum),
            490 => Some(syscall::nt::NtService::Iswalnum),
            491 => Some(syscall::nt::NtService::Isxdigit),
            492 => Some(syscall::nt::NtService::Memcmp),
            493 => Some(syscall::nt::NtService::Strcmp),
            494 => Some(syscall::nt::NtService::Strncmp),
            495 => Some(syscall::nt::NtService::Strtol),
            496 => Some(syscall::nt::NtService::Towupper),
            497 => Some(syscall::nt::NtService::Wcscspn),
            498 => Some(syscall::nt::NtService::Wcsnlen),
            499 => Some(syscall::nt::NtService::Wcspbrk),
            500 => Some(syscall::nt::NtService::Wcsspn),
            501 => Some(syscall::nt::NtService::Wcsstr),
            502 => Some(syscall::nt::NtService::Wcstol),
            503 => Some(syscall::nt::NtService::LdrGetDllHandle),
            504 => Some(syscall::nt::NtService::RtlFindExportedRoutineByName),
            505 => Some(syscall::nt::NtService::NtTestAlert),
            506 => Some(syscall::nt::NtService::NtContinue),
            507 => Some(syscall::nt::NtService::NtMakePermanentObject),
            508 => Some(syscall::nt::NtService::RtlDeNormalizeProcessParams),
            509 => Some(syscall::nt::NtService::TpPostWork),
            510 => Some(syscall::nt::NtService::TpReleaseWork),
            511 => Some(syscall::nt::NtService::TpReleaseTimer),
            512 => Some(syscall::nt::NtService::TpSetTimer),
            513 => Some(syscall::nt::NtService::RtlIpv4AddressToStringA),
            514 => Some(syscall::nt::NtService::RtlIpv4AddressToStringW),
            515 => Some(syscall::nt::NtService::RtlIpv4AddressToStringExA),
            516 => Some(syscall::nt::NtService::RtlIpv4AddressToStringExW),
            517 => Some(syscall::nt::NtService::RtlIpv4StringToAddressA),
            518 => Some(syscall::nt::NtService::RtlIpv4StringToAddressW),
            519 => Some(syscall::nt::NtService::RtlIpv4StringToAddressExA),
            520 => Some(syscall::nt::NtService::RtlIpv4StringToAddressExW),
            521 => Some(syscall::nt::NtService::RtlIpv6AddressToStringA),
            522 => Some(syscall::nt::NtService::RtlIpv6AddressToStringW),
            523 => Some(syscall::nt::NtService::RtlIpv6AddressToStringExA),
            524 => Some(syscall::nt::NtService::RtlIpv6AddressToStringExW),
            525 => Some(syscall::nt::NtService::RtlIpv6StringToAddressA),
            526 => Some(syscall::nt::NtService::RtlIpv6StringToAddressW),
            527 => Some(syscall::nt::NtService::RtlIpv6StringToAddressExA),
            528 => Some(syscall::nt::NtService::RtlIpv6StringToAddressExW),
            529 => Some(syscall::nt::NtService::RtlNtStatusToDosErrorNoTeb),
            530 => Some(syscall::nt::NtService::Md4Init),
            531 => Some(syscall::nt::NtService::Md4Update),
            532 => Some(syscall::nt::NtService::Md4Final),
            533 => Some(syscall::nt::NtService::RtlAcquireSRWLockExclusive),
            534 => Some(syscall::nt::NtService::RtlAcquireSRWLockShared),
            535 => Some(syscall::nt::NtService::RtlReleaseSRWLockExclusive),
            536 => Some(syscall::nt::NtService::RtlReleaseSRWLockShared),
            537 => Some(syscall::nt::NtService::RtlTryAcquireSRWLockExclusive),
            538 => Some(syscall::nt::NtService::RtlWakeConditionVariable),
            539 => Some(syscall::nt::NtService::RtlAddFunctionTable),
            540 => Some(syscall::nt::NtService::RtlDeleteFunctionTable),
            541 => Some(syscall::nt::NtService::RtlInstallFunctionTableCallback),
            542 => Some(syscall::nt::NtService::RtlCompareString),
            543 => Some(syscall::nt::NtService::RtlCopyUnicodeString),
            544 => Some(syscall::nt::NtService::RtlEqualUnicodeString),
            545 => Some(syscall::nt::NtService::RtlComputeCrc32),
            546 => Some(syscall::nt::NtService::RtlImageRvaToSection),
            547 => Some(syscall::nt::NtService::RtlIsCurrentProcess),
            548 => Some(syscall::nt::NtService::Wcslwr),
            549 => Some(syscall::nt::NtService::RtlInitAnsiString),
            // Neither machine-code entry traps; their selectors are never encoded.
            DBG_BREAK_POINT_INDEX | CHKSTK_INDEX | C_SPECIFIC_HANDLER_INDEX => None,
            _ => None,
    }
}

/// Service a published export name selects. # C: O(N) over the catalog
pub fn service_for_export(name: &[u8]) -> Option<syscall::nt::NtService> {
    let index = NTDLL_EXPORTS.iter().position(|export| *export == name)?;
    service_for_index(index)
}

#[cfg(test)]
#[path = "ntdll_catalog/tests.rs"]
mod tests;
