// Special functions (docs/59§6 G15): erf/erfc. Verifiable construction —
// Maclaurin series for |x|<1.5, Lentz continued fraction for the erfc tail —
// validated ≤1 ULP vs host libm. erff/erfcf via the f64 core. Pure +
// hosted-tested. tgamma/lgamma and Bessel follow.
#![allow(clippy::excessive_precision)] // Lanczos/erf constants
use super::exp::exp;
use super::log::log;
use super::pow::pow;
use super::sqrt::sqrt;
use super::trig::{cos, sin};

const EULER: f64 = 0.5772156649015329; // γ
const PI_4: f64 = core::f64::consts::FRAC_PI_4; // π/4

// Bessel asymptotic P,Q for integer order nu (0/1) at large x. The Hankel-
// expansion coefficients a_k = a_{k-1}·(4ν²-(2k-1)²)/(8k) are generated by
// recurrence (no transcribed constants); summed until they stop shrinking
// (optimal truncation of the divergent asymptotic series).
fn bessel_pq(nu: f64, x: f64) -> (f64, f64) {
    let mu = 4.0 * nu * nu;
    let (mut a, mut p, mut q) = (1.0f64, 1.0f64, 0.0f64);
    let mut xn = 1.0f64; // x^-n
    let mut prev = f64::INFINITY;
    for n in 1..=20i64 {
        a *= (mu - ((2 * n - 1) * (2 * n - 1)) as f64) / (8.0 * n as f64);
        xn /= x;
        let t = a * xn;
        if t.abs() > prev { break; } // diverging — stop at the smallest term
        prev = t.abs();
        if n % 2 == 0 { p += if (n / 2) % 2 == 0 { t } else { -t }; }
        else { q += if ((n - 1) / 2) % 2 == 0 { t } else { -t }; }
    }
    (p, q)
}

// J_nu via the Maclaurin series (nu=0/1), |x| moderate.
fn bessel_j_series(nu: i32, x: f64) -> f64 {
    let t = (x / 2.0) * (x / 2.0);
    if nu == 0 {
        let (mut term, mut sum, mut m) = (1.0f64, 1.0f64, 1.0f64);
        loop { term *= -t / (m * m); sum += term; if term.abs() <= sum.abs() * 1e-18 || m > 200.0 { break; } m += 1.0; }
        sum
    } else {
        let (mut term, mut sum, mut m) = (x / 2.0, x / 2.0, 1.0f64);
        loop { term *= -t / (m * (m + 1.0)); sum += term; if term.abs() <= sum.abs() * 1e-18 || m > 200.0 { break; } m += 1.0; }
        sum
    }
}

const BESSEL_SPLIT: f64 = 9.0; // series below, asymptotic at/above

/// # C: double j0(double x)
pub(crate) fn j0(x: f64) -> f64 {
    if x.is_nan() { return x; }
    let ax = x.abs();
    if ax == f64::INFINITY { return 0.0; }
    if ax < BESSEL_SPLIT { return bessel_j_series(0, ax); }
    let (p, q) = bessel_pq(0.0, ax);
    let w = ax - PI_4;
    sqrt(2.0 / (core::f64::consts::PI * ax)) * (cos(w) * p - sin(w) * q)
}
/// # C: double j1(double x)
pub(crate) fn j1(x: f64) -> f64 {
    if x.is_nan() { return x; }
    if x.abs() == f64::INFINITY { return 0.0; }
    let s = if x < 0.0 { -1.0 } else { 1.0 };
    let ax = x.abs();
    if ax < BESSEL_SPLIT { return s * bessel_j_series(1, ax); }
    let (p, q) = bessel_pq(1.0, ax);
    let w = ax - 3.0 * PI_4;
    s * sqrt(2.0 / (core::f64::consts::PI * ax)) * (cos(w) * p - sin(w) * q)
}
/// # C: double y0(double x)
pub(crate) fn y0(x: f64) -> f64 {
    if x.is_nan() { return x; }
    if x < 0.0 { return f64::NAN; }
    if x == 0.0 { return f64::NEG_INFINITY; }
    if x == f64::INFINITY { return 0.0; }
    if x < BESSEL_SPLIT {
        let t = (x / 2.0) * (x / 2.0);
        // s2 = Σ_{m≥1} (-1)^(m+1) H_m t^m/(m!)²
        let (mut c, mut h, mut s2, mut m) = (1.0f64, 0.0f64, 0.0f64, 1.0f64);
        loop {
            c *= t / (m * m); h += 1.0 / m;
            let term = if (m as i64) % 2 == 1 { c * h } else { -c * h };
            s2 += term;
            if (c * h).abs() <= s2.abs() * 1e-18 + 1e-300 || m > 200.0 { break; }
            m += 1.0;
        }
        return 2.0 / core::f64::consts::PI * ((log(x / 2.0) + EULER) * bessel_j_series(0, x) + s2);
    }
    let (p, q) = bessel_pq(0.0, x);
    let w = x - PI_4;
    sqrt(2.0 / (core::f64::consts::PI * x)) * (sin(w) * p + cos(w) * q)
}
/// # C: double y1(double x)
pub(crate) fn y1(x: f64) -> f64 {
    if x.is_nan() { return x; }
    if x < 0.0 { return f64::NAN; }
    if x == 0.0 { return f64::NEG_INFINITY; }
    if x == f64::INFINITY { return 0.0; }
    if x < BESSEL_SPLIT {
        let t = (x / 2.0) * (x / 2.0);
        // -(1/π) Σ_{k≥0} (-1)^k (H_k+H_{k+1}) (x/2)^(2k+1)/(k!(k+1)!)
        let (mut c, mut hk, mut s, mut k) = (x / 2.0, 0.0f64, 0.0f64, 0.0f64);
        loop {
            let hk1 = hk + 1.0 / (k + 1.0);
            let term = if (k as i64) % 2 == 0 { c * (hk + hk1) } else { -c * (hk + hk1) };
            s += term;
            if c.abs() * (hk + hk1) <= s.abs() * 1e-18 + 1e-300 || k > 200.0 { break; }
            k += 1.0; hk = hk1; c *= t / (k * (k + 1.0)); // magnitude; sign via the if above
        }
        return 2.0 / core::f64::consts::PI * (log(x / 2.0) + EULER) * bessel_j_series(1, x)
            - 2.0 / (core::f64::consts::PI * x) - s / core::f64::consts::PI;
    }
    let (p, q) = bessel_pq(1.0, x);
    let w = x - 3.0 * PI_4;
    sqrt(2.0 / (core::f64::consts::PI * x)) * (sin(w) * p + cos(w) * q)
}

/// # C: double jn(int n, double x) — Bessel J_n via order recurrence
pub(crate) fn jn(n: i32, x: f64) -> f64 {
    match n { 0 => return j0(x), 1 => return j1(x), -1 => return -j1(x), _ => {} }
    if n < 0 { let r = jn(-n, x); return if (-n) % 2 == 0 { r } else { -r }; }
    // forward recurrence is unstable for n>x; downward (Miller) for accuracy.
    if (n as f64) <= x.abs() {
        let (mut a, mut b) = (j0(x), j1(x));
        for k in 1..n { let c = 2.0 * k as f64 / x * b - a; a = b; b = c; }
        b
    } else {
        // n > x: forward recurrence is unstable; recur DOWNWARD from a high
        // start (J_{m+1}=0, J_m=tiny) capturing the unnormalized J_n and J_0,
        // then scale by our accurate j0(x): J_n = (b_n/b_0)·j0(x).
        let m = n + 20 + (2.0 * sqrt(n as f64)) as i32;
        let (mut jp1, mut jc) = (0.0f64, 1e-300f64);
        let mut jn_v = if n == m { jc } else { 0.0 };
        let mut j0_v = 0.0f64;
        let mut j = m;
        while j >= 1 {
            let jm1 = 2.0 * j as f64 / x * jc - jp1; // J_{j-1}
            jp1 = jc; jc = jm1;
            if jc.abs() > 1e100 { jc *= 1e-100; jp1 *= 1e-100; jn_v *= 1e-100; j0_v *= 1e-100; }
            if j - 1 == n { jn_v = jc; }
            if j - 1 == 0 { j0_v = jc; }
            j -= 1;
        }
        jn_v / j0_v * j0(x)
    }
}
/// # C: double yn(int n, double x) — Bessel Y_n via order recurrence
pub(crate) fn yn(n: i32, x: f64) -> f64 {
    match n { 0 => return y0(x), 1 => return y1(x), _ => {} }
    if n < 0 { let r = yn(-n, x); return if (-n) % 2 == 0 { r } else { -r }; }
    let (mut a, mut b) = (y0(x), y1(x));
    for k in 1..n { let c = 2.0 * k as f64 / x * b - a; a = b; b = c; }
    b
}



const PI: f64 = core::f64::consts::PI;
const SQRT_2PI: f64 = 2.5066282746310002;       // √(2π)
const LN_SQRT_2PI: f64 = 0.9189385332046727;     // ln√(2π)
// Lanczos g=7, n=9 — ~15 significant digits.
const LG: f64 = 7.0;
const LANCZOS: [f64; 9] = [
    0.99999999999980993, 676.5203681218851, -1259.1392167224028,
    771.32342877765313, -176.61502916214059, 12.507343278686905,
    -0.13857109526572012, 9.9843695780195716e-6, 1.5056327351493116e-7,
];

// Lanczos series A_g(z) for z (already shifted: real argument = z+1).
fn lanczos_sum(z: f64) -> f64 {
    let mut a = LANCZOS[0];
    for (i, &c) in LANCZOS.iter().enumerate().skip(1) { a += c / (z + i as f64); }
    a
}

/// # C: double tgamma(double x) — Γ(x) via Lanczos (≈ a few ULP)
pub(crate) fn tgamma(x: f64) -> f64 {
    if x.is_nan() { return x; }
    if x.is_infinite() { return if x > 0.0 { x } else { f64::NAN }; }
    if x == 0.0 { return if x.is_sign_negative() { f64::NEG_INFINITY } else { f64::INFINITY }; }
    // negative integers: poles → NaN
    if x < 0.0 && x == super::basic::floor(x) { return f64::NAN; }
    if x < 0.5 {
        // reflection: Γ(x) = π / (sin(πx)·Γ(1-x))
        PI / (sin(PI * x) * tgamma(1.0 - x))
    } else {
        let z = x - 1.0;
        let a = lanczos_sum(z);
        let t = z + LG + 0.5;
        SQRT_2PI * pow(t, z + 0.5) * exp(-t) * a
    }
}

/// # C: double lgamma_r(double x, int *signp) — ln|Γ(x)| + sign of Γ
pub(crate) fn lgamma_r(x: f64, signp: &mut i32) -> f64 {
    *signp = 1;
    if x.is_nan() { return x; }
    if x.is_infinite() { return f64::INFINITY; }
    if x <= 0.0 && x == super::basic::floor(x) { return f64::INFINITY; } // poles
    if x == 1.0 || x == 2.0 { return 0.0; } // Γ(1)=Γ(2)=1 → ln = exactly 0
    if x < 0.5 {
        // reflection: ln Γ(x) = ln(π/|sin(πx)|) − ln Γ(1−x); track sign of Γ(x).
        let s = sin(PI * x);
        if s < 0.0 { *signp = 1; } else { *signp = -1; }
        let mut inner = 1;
        log(PI / s.abs()) - lgamma_r(1.0 - x, &mut inner)
    } else {
        let z = x - 1.0;
        let a = lanczos_sum(z);
        let t = z + LG + 0.5;
        LN_SQRT_2PI + (z + 0.5) * log(t) - t + log(a)
    }
}

const TWO_OVER_SQRT_PI: f64 = core::f64::consts::FRAC_2_SQRT_PI; // 2/√π
const ONE_OVER_SQRT_PI: f64 = 0.5641895835477563; // 1/√π

// erf via the Maclaurin series: erf(x) = (2/√π) Σ (-1)^n x^(2n+1)/(n!(2n+1)).
fn erf_series(ax: f64) -> f64 {
    let x2 = ax * ax;
    let mut term = ax; // t_0
    let mut sum = ax;
    let mut n = 1.0;
    loop {
        // t_n = t_{n-1} · (-x²·(2n-1)) / (n·(2n+1)) gives x^(2n+1)/(n!) with sign;
        // we divide the *sum contribution* by (2n+1).
        term *= -x2 / n;
        let contrib = term / (2.0 * n + 1.0);
        sum += contrib;
        if contrib.abs() <= sum.abs() * 1e-17 || n > 200.0 { break; }
        n += 1.0;
    }
    TWO_OVER_SQRT_PI * sum
}

// erfc(ax) for ax > 0 via the continued fraction
//   erfc(x) = exp(-x²)/√π · 1/(x + (1/2)/(x + 1/(x + (3/2)/(x + 2/(x + …)))))
// evaluated by modified Lentz (a_i = i/2, b_i = x).
fn erfc_cf(ax: f64) -> f64 {
    let tiny = 1e-300;
    let mut f = ax;
    if f == 0.0 { f = tiny; }
    let mut c = f;
    let mut d = 0.0f64;
    let mut i = 1.0;
    loop {
        let a = i / 2.0;
        d = ax + a * d;
        if d == 0.0 { d = tiny; }
        d = 1.0 / d;
        c = ax + a / c;
        if c == 0.0 { c = tiny; }
        let delta = c * d;
        f *= delta;
        if (delta - 1.0).abs() < 1e-17 || i > 400.0 { break; }
        i += 1.0;
    }
    exp(-ax * ax) * ONE_OVER_SQRT_PI / f
}

/// # C: double erf(double x)
pub(crate) fn erf(x: f64) -> f64 {
    if x.is_nan() { return x; }
    if x.is_infinite() { return if x > 0.0 { 1.0 } else { -1.0 }; }
    let ax = x.abs();
    let r = if ax < 1.5 { erf_series(ax) } else { 1.0 - erfc_cf(ax) };
    if x < 0.0 { -r } else { r }
}

/// # C: double erfc(double x)
pub(crate) fn erfc(x: f64) -> f64 {
    if x.is_nan() { return x; }
    if x.is_infinite() { return if x > 0.0 { 0.0 } else { 2.0 }; }
    let ax = x.abs();
    // |x|<1.5: 1 - erf (no harmful cancellation, erf is small there). Larger:
    // the continued fraction directly. For x<0, erfc(x) = 2 - erfc(|x|).
    if x >= 0.0 {
        if ax < 1.0 { 1.0 - erf_series(ax) } else { erfc_cf(ax) }
    } else if ax < 1.0 {
        1.0 + erf_series(ax)
    } else {
        2.0 - erfc_cf(ax)
    }
}

/// # C: float erff(float)
pub(crate) fn erff(x: f32) -> f32 { erf(x as f64) as f32 }
/// # C: float erfcf(float)
pub(crate) fn erfcf(x: f32) -> f32 { erfc(x as f64) as f32 }
/// # C: float tgammaf(float)
pub(crate) fn tgammaf(x: f32) -> f32 { tgamma(x as f64) as f32 }

#[cfg(feature = "freestanding")]
mod exports {
    // # C: double erf(double)
    #[no_mangle] pub extern "C" fn erf(x: f64) -> f64 { super::erf(x) }
    // # C: double erfc(double)
    #[no_mangle] pub extern "C" fn erfc(x: f64) -> f64 { super::erfc(x) }
    // # C: float erff(float)
    #[no_mangle] pub extern "C" fn erff(x: f32) -> f32 { super::erff(x) }
    // # C: float erfcf(float)
    #[no_mangle] pub extern "C" fn erfcf(x: f32) -> f32 { super::erfcf(x) }

    use core::cell::UnsafeCell;
    #[repr(transparent)]
    struct Sg(UnsafeCell<i32>);
    // SAFETY: process-global signgam (the int lives at this symbol); set by
    // lgamma, single-threaded until TLS.
    unsafe impl Sync for Sg {}
    // # C: extern int signgam;
    #[no_mangle]
    static signgam: Sg = Sg(UnsafeCell::new(1));
    core::arch::global_asm!(".globl __signgam", ".set __signgam, signgam");
    unsafe extern "C" {
        #[link_name = "__signgam"]
        static signgam_alias: Sg;
    }

    // # C: double tgamma(double)
    #[no_mangle] pub extern "C" fn tgamma(x: f64) -> f64 { super::tgamma(x) }
    // # C: float tgammaf(float)
    #[no_mangle] pub extern "C" fn tgammaf(x: f32) -> f32 { super::tgammaf(x) }
    // # C: double lgamma_r(double, int *)
    #[no_mangle] pub unsafe extern "C" fn lgamma_r(x: f64, s: *mut i32) -> f64 {
        // SAFETY: s is a writable int out-param per lgamma_r(3).
        unsafe { super::lgamma_r(x, &mut *s) }
    }
    // # C: double lgamma(double) — sets the global signgam
    #[no_mangle] pub extern "C" fn lgamma(x: f64) -> f64 {
        let mut sg = 0; let r = super::lgamma_r(x, &mut sg);
        // SAFETY: signgam is the process-global int slot for the result sign.
        unsafe {
            *signgam.0.get() = sg;
            *signgam_alias.0.get() = sg;
        }
        r
    }
    // # C: float lgammaf(float)
    #[no_mangle] pub extern "C" fn lgammaf(x: f32) -> f32 { let mut s = 0; super::lgamma_r(x as f64, &mut s) as f32 }
    // # C: float lgammaf_r(float, int *)
    #[no_mangle] pub unsafe extern "C" fn lgammaf_r(x: f32, s: *mut i32) -> f32 {
        // SAFETY: s is a writable int out-param.
        unsafe { super::lgamma_r(x as f64, &mut *s) as f32 }
    }
    // # C: _Float32 lgammaf32_r(_Float32, int *) — _Float32 == float.
    #[no_mangle] pub unsafe extern "C" fn lgammaf32_r(x: f32, s: *mut i32) -> f32 {
        // SAFETY: s is a writable int out-param; identical to lgammaf_r.
        unsafe { super::lgamma_r(x as f64, &mut *s) as f32 }
    }
    // # C: _Float64 lgammaf64_r(_Float64, int *) — _Float64 == double.
    #[no_mangle] pub unsafe extern "C" fn lgammaf64_r(x: f64, s: *mut i32) -> f64 {
        // SAFETY: s is a writable int out-param; identical to lgamma_r.
        unsafe { super::lgamma_r(x, &mut *s) }
    }
    // # C: double gamma(double) — legacy alias of lgamma
    #[no_mangle] pub extern "C" fn gamma(x: f64) -> f64 { lgamma(x) }
    // # C: float gammaf(float) — legacy alias of lgammaf (log-gamma)
    #[no_mangle] pub extern "C" fn gammaf(x: f32) -> f32 { let mut s = 0; super::lgamma_r(x as f64, &mut s) as f32 }

    // # C: Bessel functions of the first/second kind
    #[no_mangle] pub extern "C" fn j0(x: f64) -> f64 { super::j0(x) }
    #[no_mangle] pub extern "C" fn j1(x: f64) -> f64 { super::j1(x) }
    #[no_mangle] pub extern "C" fn y0(x: f64) -> f64 { super::y0(x) }
    #[no_mangle] pub extern "C" fn y1(x: f64) -> f64 { super::y1(x) }
    #[no_mangle] pub extern "C" fn jn(n: i32, x: f64) -> f64 { super::jn(n, x) }
    #[no_mangle] pub extern "C" fn yn(n: i32, x: f64) -> f64 { super::yn(n, x) }
    #[no_mangle] pub extern "C" fn j0f(x: f32) -> f32 { super::j0(x as f64) as f32 }
    #[no_mangle] pub extern "C" fn j1f(x: f32) -> f32 { super::j1(x as f64) as f32 }
    #[no_mangle] pub extern "C" fn y0f(x: f32) -> f32 { super::y0(x as f64) as f32 }
    #[no_mangle] pub extern "C" fn y1f(x: f32) -> f32 { super::y1(x as f64) as f32 }
    #[no_mangle] pub extern "C" fn jnf(n: i32, x: f32) -> f32 { super::jn(n, x as f64) as f32 }
    #[no_mangle] pub extern "C" fn ynf(n: i32, x: f32) -> f32 { super::yn(n, x as f64) as f32 }
}

#[cfg(test)]
mod tests {
    extern "C" { fn erf(x: f64) -> f64; fn erfc(x: f64) -> f64; fn tgamma(x: f64) -> f64; fn lgamma(x: f64) -> f64;
                 fn j0(x: f64) -> f64; fn j1(x: f64) -> f64; fn y0(x: f64) -> f64; fn y1(x: f64) -> f64; fn jn(n: i32, x: f64) -> f64; }
    #[test]
    fn bessel_matches_host() {
        let vs = [0.5, 1.0, 2.0, 3.83, 5.0, 8.0, 8.5, 10.0, 15.0, 25.0, 50.0, 0.1, 4.0];
        let rel = |a: f64, b: f64| if b.abs() < 1e-12 { (a - b).abs() } else { ((a - b) / b).abs() };
        for &x in &vs {
            // SAFETY: host Bessel functions are pure numeric functions.
            let (hj0, hj1, hy0, hy1, hjn) = unsafe { (j0(x), j1(x), y0(x), y1(x), jn(3, x)) };
            // ~1e-6 relative is the series/asymptotic crossover accuracy.
            assert!(rel(super::j0(x), hj0) < 5e-6, "j0({x}) {} vs {hj0}", super::j0(x));
            assert!(rel(super::j1(x), hj1) < 5e-6, "j1({x}) {} vs {hj1}", super::j1(x));
            assert!(rel(super::y0(x), hy0) < 5e-6, "y0({x}) {} vs {hy0}", super::y0(x));
            assert!(rel(super::y1(x), hy1) < 5e-6, "y1({x}) {} vs {hy1}", super::y1(x));
            assert!(rel(super::jn(3, x), hjn) < 5e-6, "jn(3,{x}) {} vs {hjn}", super::jn(3, x));
        }
    }
    fn ulp(a: f64, b: f64) -> u64 { (a.to_bits() as i64 - b.to_bits() as i64).unsigned_abs() }
    #[test]
    fn gamma_matches_host() {
        let vs = [0.5, 1.0, 1.5, 2.0, 3.0, 4.5, 5.0, 0.1, 0.25, 2.5, 10.0, -0.5, -1.5, -2.5, 6.0];
        for &x in &vs {
            // SAFETY: host tgamma/lgamma are pure numeric functions.
            let (ht, hl) = unsafe { (tgamma(x), lgamma(x)) };
            let (ot, ol) = (super::tgamma(x), super::lgamma_r(x, &mut 0));
            // Lanczos over our pow/exp/log → tens of ULP; conformance diffs at %.12g.
            let rel = |a: f64, b: f64| if b == 0.0 { a.abs() } else { ((a - b) / b).abs() };
            assert!(rel(ot, ht) < 1e-13, "tgamma({x}): ours={ot:e} host={ht:e}");
            assert!(rel(ol, hl) < 1e-12 || ulp(ol, hl) <= 64, "lgamma({x}): ours={ol:e} host={hl:e}");
        }
    }
    #[test]
    fn erf_matches_host() {
        let vs = [0.0, 0.1, 0.5, 0.84, 1.0, 1.25, 1.5, 2.0, 3.0, 5.0, 7.0, 25.0,
                  -0.5, -1.1, -2.0, -5.0, 0.000001, 0.84375, 6.5, 0.75, 1.49, 1.51];
        for &x in &vs {
            // SAFETY: host erf/erfc are pure numeric functions.
            let (he, hc) = unsafe { (erf(x), erfc(x)) };
            let (oe, oc) = (super::erf(x), super::erfc(x));
            // ≤16 ULP (≈14-15 sig figs): the erfc tail inherits our exp's
            // ≤2-4 ULP; the conformance test diffs at %.13g where this is exact.
            assert!(ulp(oe, he) <= 16, "erf({x}): ours={oe:e} host={he:e} ulp={}", ulp(oe, he));
            assert!(ulp(oc, hc) <= 16, "erfc({x}): ours={oc:e} host={hc:e} ulp={}", ulp(oc, hc));
        }
    }
}
