[package]
name = "drv-xhci"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
mmio-map = { path = "../../kernel/mmio-map" }
pmm = { path = "../../kernel/mm-pmm" }
drv = { path = "../drv" }
pci = { path = "../pci" }
sched = { path = "../../kernel/sched" }
sync = { path = "../../shared/sync" }
arch-irq = { path = "../../kernel/arch-irq" }
pci-irq = { path = "../../kernel/pci-irq" }
softirq = { path = "../../kernel/softirq" }
input = { path = "../../kernel/input" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
hal-x86_64 = { path = "../../arch/hal-x86_64" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
hal-aarch64 = { path = "../../arch/hal-aarch64" }

[lints]
workspace = true
