[package]
name = "drv-igc"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
pci = { path = "../pci" }
pmm = { path = "../../kernel/mm-pmm" }
iommu = { path = "../../kernel/iommu" }
mmio-map = { path = "../../kernel/mmio-map" }
sched = { path = "../../kernel/sched" }

[lints]
workspace = true
