[package]
name = "firmware"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
hal  = { path = "../../arch/hal" }
fdt  = { path = "../../shared/fdt" }
crc  = { path = "../../shared/crc" }
klog = { path = "../../shared/klog" }
sync = { path = "../../shared/sync" }
pci  = { path = "../../drivers/pci" }
ext4 = { path = "../ext4" }
aml = { path = "../../../vendor/rust/aml-0.16.4" }
vfs = { path = "../vfs" }
timekeeper = { path = "../timekeeper" }
power-supply = { path = "../power-supply" }
backlight = { path = "../backlight" }
thermal = { path = "../thermal" }
cpu = { path = "../cpu" }
cpufreq = { path = "../cpufreq" }
cpuidle = { path = "../cpuidle" }
clk = { path = "../clk" }
regulator = { path = "../regulator" }
opp = { path = "../opp" }
scmi = { path = "../scmi" }
sched = { path = "../sched" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
hal-x86_64 = { path = "../../arch/hal-x86_64" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
hal-aarch64 = { path = "../../arch/hal-aarch64" }
mmio-map = { path = "../mmio-map" }

[dev-dependencies]
fdt = { path = "../../shared/fdt", features = ["fixture"] }

[features]
default = []
debug-acpi = []

[lints]
workspace = true
