[package]
name = "firmware"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
hal  = { path = "../../arch/hal" }
fdt  = { path = "../../shared/fdt" }
crc  = { path = "../../shared/crc" }
klog = { path = "../../shared/klog" }
sync = { path = "../../shared/sync" }
pci  = { path = "../../drivers/pci" }
ext4 = { path = "../ext4" }
aml = "0.16.4"

[features]
default = []
debug-acpi = []

[lints]
workspace = true
