[package]
name = "ninep"
version = "0.1.0"
edition = "2021"
publish = false
[lib]
path = "src/lib.rs"
[dependencies]
sync    = { path = "../../shared/sync" }
vfs     = { path = "../vfs" }

[target.'cfg(target_os = "oxide-kernel")'.dependencies]
sched   = { path = "../sched" }

[features]
default = []
hosted = []

[lints]
workspace = true
