pub const IPC_INIT_NSFS_INO: u64 = 0xEFFF_FFFF;
pub const UTS_INIT_NSFS_INO: u64 = 0xEFFF_FFFE;
pub const USER_INIT_NSFS_INO: u64 = 0xEFFF_FFFD;
pub const PID_INIT_NSFS_INO: u64 = 0xEFFF_FFFC;
pub const CGROUP_INIT_NSFS_INO: u64 = 0xEFFF_FFFB;
pub const TIME_INIT_NSFS_INO: u64 = 0xEFFF_FFFA;

pub const MNT_INIT_NSFS_INO: u64 = 0x7300_0000;
pub(crate) const FIRST_DYNAMIC_NSFS_INO: u64 = MNT_INIT_NSFS_INO + 1;
