[package]
name = "drv-e1000"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
drv = { path = "../drv" }
pci = { path = "../pci" }
mmio-map = { path = "../../kernel/mmio-map" }
net = { path = "../../kernel/net" }
pmm = { path = "../../kernel/mm-pmm" }
sync = { path = "../../shared/sync" }
softirq = { path = "../../kernel/softirq" }
arch-irq = { path = "../../kernel/arch-irq" }
sched = { path = "../../kernel/sched" }
klog = { path = "../../shared/klog" }
firmware = { path = "../../kernel/firmware" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
hal-x86_64 = { path = "../../arch/hal-x86_64" }
hal = { path = "../../arch/hal" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
hal-aarch64 = { path = "../../arch/hal-aarch64" }

[features]
default = []
debug-boot = []

[lints]
workspace = true
