// End-to-end coverage of the ONE signal-enqueue path (`live::send`), driven
// against real `Task`s and a real `ThreadGroup` rather than against the pure
// decision helpers in `sigsend` (those have their own tests).
//
// This is what proves the unification actually took: a signal generated by any
// producer lands in the right pending set, carries a real `siginfo_t`, and
// honours `prepare_signal`'s ignore/flush ladder.

extern crate alloc;

use alloc::sync::Arc;
use core::sync::atomic::Ordering;

use crate::live::send;
use crate::sigsend::{ForceMode, SigSource, SigTarget, SIG_IGN};
use crate::signum::{self, Signum};
use crate::task::{SaHandler, SchedClass, Task};

const SIGTERM: u32 = Signum::Sigterm as u32;
const SIGCHLD: u32 = Signum::Sigchld as u32;
const SIGSEGV: u32 = Signum::Sigsegv as u32;
const SIGCONT: u32 = Signum::Sigcont as u32;
const SIGTSTP: u32 = Signum::Sigtstp as u32;
const SIGRTMIN: u32 = signum::RT_SIGNAL_MIN;
const HANDLER: u64 = 0x4000;

fn task(tid: u32) -> Arc<Task> {
    let t = Arc::new(Task::new(tid, "send", SchedClass::Normal { weight: 1024 }));
    t.pid.attach(&t);
    t
}

fn sender() -> SigSource { SigSource::User { pid: 4242, uid: 1000 } }

fn install(t: &Task, sig: u32, handler: u64) {
    let _ = t.sigactions_ref().set_action(sig as usize,
        Some(SaHandler { handler, flags: 0, restorer: 0, mask: 0 }));
}

#[test]
fn a_process_directed_send_lands_in_the_shared_set_with_the_senders_identity() {
    let t = task(700);
    assert_eq!(send::send_signal(&t, SIGTERM, sender(), SigTarget::Process), Ok(()));
    assert_ne!(t.thread_group.shared_pending() & Signum::Sigterm.bit(), 0);
    assert_eq!(t.sigpending.load(Ordering::Acquire) & Signum::Sigterm.bit(), 0,
               "kill(2) must not touch one thread's private set");
    let rec = t.dequeue_pending(SIGTERM).unwrap().expect("a record, not a bare bit");
    assert_eq!((rec.code, rec.pid, rec.uid), (signum::SI_USER, 4242, 1000));
}

#[test]
fn a_thread_directed_send_lands_in_the_private_set() {
    let t = task(701);
    assert_eq!(send::send_signal(&t, SIGTERM, sender(), SigTarget::Thread), Ok(()));
    assert_ne!(t.sigpending.load(Ordering::Acquire) & Signum::Sigterm.bit(), 0);
    assert_eq!(t.thread_group.shared_pending() & Signum::Sigterm.bit(), 0);
}

#[test]
fn a_default_ignored_signal_is_dropped_at_send_time() {
    let t = task(702);
    // SIGCHLD's default action is Ignore, so `sig_ignored` drops the send
    // outright — nothing pending, nothing queued.
    assert_eq!(send::send_signal(&t, SIGCHLD, sender(), SigTarget::Process), Ok(()));
    assert_eq!(t.pending_signals() & Signum::Sigchld.bit(), 0);
}

#[test]
fn an_explicitly_ignored_signal_is_dropped_at_send_time() {
    let t = task(703);
    install(&t, SIGTERM, SIG_IGN);
    assert_eq!(send::send_signal(&t, SIGTERM, sender(), SigTarget::Process), Ok(()));
    assert_eq!(t.pending_signals() & Signum::Sigterm.bit(), 0);
}

#[test]
fn a_kernel_generated_send_is_not_dropped_by_sig_ign() {
    let t = task(704);
    install(&t, SIGTERM, SIG_IGN);
    // `SEND_SIG_PRIV` forces past the disposition — this is why a tty hangup
    // still reaches a process that installed `signal(SIGHUP, SIG_IGN)` when the
    // kernel decides it must.
    assert_eq!(send::send_signal(&t, SIGTERM, SigSource::Kernel, SigTarget::Process), Ok(()));
    assert_ne!(t.pending_signals() & Signum::Sigterm.bit(), 0);
    let rec = t.dequeue_pending(SIGTERM).unwrap().unwrap();
    assert_eq!(rec.code, signum::SI_KERNEL);
}

#[test]
fn a_blocked_signal_is_queued_even_with_sig_ign_installed() {
    let t = task(705);
    install(&t, SIGTERM, SIG_IGN);
    t.set_current_blocked(Signum::Sigterm.bit());
    // Blocked beats ignored: `sigwait`/`signalfd` must still be able to collect
    // it, and unblocking it later must deliver it.
    assert_eq!(send::send_signal(&t, SIGTERM, sender(), SigTarget::Process), Ok(()));
    assert_ne!(t.pending_signals() & Signum::Sigterm.bit(), 0);
}

#[test]
fn a_second_standard_signal_keeps_the_first_record() {
    let t = task(706);
    let first = SigSource::User { pid: 1, uid: 0 };
    let second = SigSource::User { pid: 2, uid: 0 };
    assert_eq!(send::send_signal(&t, SIGTERM, first, SigTarget::Process), Ok(()));
    assert_eq!(send::send_signal(&t, SIGTERM, second, SigTarget::Process), Ok(()));
    let rec = t.dequeue_pending(SIGTERM).unwrap().unwrap();
    assert_eq!(rec.pid, 1, "legacy_queue keeps the FIRST record");
    assert_eq!(t.dequeue_pending(SIGTERM), None, "and only one was queued");
}

#[test]
fn real_time_signals_queue_in_arrival_order_instead_of_collapsing() {
    let t = task(707);
    for pid in 1..=3u32 {
        assert_eq!(send::send_signal(&t, SIGRTMIN, SigSource::User { pid, uid: 0 },
                                     SigTarget::Process), Ok(()));
    }
    for pid in 1..=3u32 {
        let rec = t.dequeue_pending(SIGRTMIN).unwrap().unwrap();
        assert_eq!(rec.pid, pid);
    }
}

#[test]
fn a_queued_realtime_overflow_reports_eagain_only_for_a_user_queueing_sender() {
    let t = task(708);
    let queued = |v: u64| crate::task::SigInfo {
        signo: SIGRTMIN, code: signum::SI_QUEUE, pid: 1, uid: 0, value: v,
        sys: None, fault: None,
    };
    for v in 0..crate::task::RT_QUEUE_CAP as u64 {
        assert_eq!(send::send_signal(&t, SIGRTMIN, SigSource::Info(queued(v)),
                                     SigTarget::Process), Ok(()));
    }
    assert_eq!(send::send_signal(&t, SIGRTMIN, SigSource::Info(queued(999)),
                                 SigTarget::Process), Err(send::SendErr::Again));
    // `kill(2)` of the same signal at the same depth must NOT fail — POSIX
    // forbids EAGAIN there, so the record is silently lost instead.
    assert_eq!(send::send_signal(&t, SIGRTMIN, sender(), SigTarget::Process), Ok(()));
}

#[test]
fn sigcont_flushes_a_pending_stop_and_a_stop_flushes_a_pending_sigcont() {
    let t = task(709);
    assert_eq!(send::send_signal(&t, SIGTSTP, SigSource::Kernel, SigTarget::Process), Ok(()));
    assert_ne!(t.pending_signals() & Signum::Sigtstp.bit(), 0);
    assert_eq!(send::send_signal(&t, SIGCONT, SigSource::Kernel, SigTarget::Process), Ok(()));
    assert_eq!(t.pending_signals() & crate::sigsend::STOP_MASK, 0,
               "a queued stop must not re-stop a group SIGCONT just resumed");

    let u = task(710);
    assert_eq!(send::send_signal(&u, SIGCONT, SigSource::Kernel, SigTarget::Process), Ok(()));
    assert_eq!(send::send_signal(&u, SIGTSTP, SigSource::Kernel, SigTarget::Process), Ok(()));
    assert_eq!(u.pending_signals() & Signum::Sigcont.bit(), 0);
}

// --- force_sig_fault / force_sig_info ---------------------------------------

#[test]
fn a_forced_fault_signal_queues_a_sigfault_record_on_the_faulting_thread() {
    let t = task(711);
    install(&t, SIGSEGV, HANDLER);
    let info = crate::sigsend::fault_info(SIGSEGV, hal::siginfo::code::SEGV_MAPERR,
                                          0x7fff_dead_b000, 0);
    send::force_sig_info_to_task(&t, info, ForceMode::Current);
    // PIDTYPE_PID: a synchronous condition belongs to the thread that caused it.
    assert_ne!(t.sigpending.load(Ordering::Acquire) & Signum::Sigsegv.bit(), 0);
    assert_eq!(t.thread_group.shared_pending() & Signum::Sigsegv.bit(), 0);
    let rec = t.dequeue_pending(SIGSEGV).unwrap().expect("the _sigfault record");
    assert_eq!(rec.code, hal::siginfo::code::SEGV_MAPERR);
    assert_eq!(rec.fault.unwrap().addr, 0x7fff_dead_b000);
    // The handler survives: an unblocked, un-ignored fault signal is catchable.
    assert_eq!(t.sigactions_ref().get(SIGSEGV).handler, HANDLER);
}

#[test]
fn a_forced_fault_signal_unblocks_itself_and_resets_a_blocked_handler() {
    let t = task(712);
    install(&t, SIGSEGV, HANDLER);
    t.set_current_blocked(Signum::Sigsegv.bit());
    let info = crate::sigsend::fault_info(SIGSEGV, hal::siginfo::code::SEGV_ACCERR, 0x1000, 0);
    send::force_sig_info_to_task(&t, info, ForceMode::Current);
    // Without this a process that blocked SIGSEGV would re-fault forever on the
    // same instruction instead of dying.
    assert_eq!(t.sigmask.load(Ordering::Acquire) & Signum::Sigsegv.bit(), 0);
    assert_eq!(t.sigactions_ref().get(SIGSEGV).handler, 0, "reset to SIG_DFL");
    assert_ne!(t.pending_signals() & Signum::Sigsegv.bit(), 0);
}

#[test]
fn a_forced_fault_signal_overrides_an_ignoring_disposition() {
    let t = task(713);
    install(&t, SIGSEGV, SIG_IGN);
    let info = crate::sigsend::fault_info(SIGSEGV, hal::siginfo::code::SEGV_MAPERR, 0x2000, 0);
    send::force_sig_info_to_task(&t, info, ForceMode::Current);
    assert_eq!(t.sigactions_ref().get(SIGSEGV).handler, 0);
    assert_ne!(t.pending_signals() & Signum::Sigsegv.bit(), 0);
}

#[test]
fn handler_exit_mode_strips_a_handler_that_was_neither_blocked_nor_ignored() {
    let t = task(714);
    install(&t, Signum::Sigsys as u32, HANDLER);
    let info = crate::sigsend::fault_info(Signum::Sigsys as u32, 1, 0, 0);
    send::force_sig_info_to_task(&t, info, ForceMode::Exit);
    assert_eq!(t.sigactions_ref().get(Signum::Sigsys as u32).handler, 0,
               "a seccomp KILL action is not catchable");
}
