// End-to-end coverage of the ONE signal-enqueue path (`live::send`), driven
// against real `Task`s and a real `ThreadGroup` rather than against the pure
// decision helpers in `sigsend` (those have their own tests).
//
// This is what proves the unification actually took: a signal generated by any
// producer lands in the right pending set, carries a real `siginfo_t`, and
// honours `prepare_signal`'s ignore/flush ladder.

extern crate alloc;

use alloc::sync::Arc;
use core::sync::atomic::Ordering;

use crate::live::send;
use crate::sigsend::{ForceMode, SigSource, SigTarget, SIG_IGN};
use crate::signum::{self, Signum};
use crate::task::{SaHandler, SchedClass, Task};

const SIGTERM: u32 = Signum::Sigterm as u32;
const SIGCHLD: u32 = Signum::Sigchld as u32;
const SIGSEGV: u32 = Signum::Sigsegv as u32;
const SIGCONT: u32 = Signum::Sigcont as u32;
const SIGTSTP: u32 = Signum::Sigtstp as u32;
const SIGRTMIN: u32 = signum::RT_SIGNAL_MIN;
const HANDLER: u64 = 0x4000;

fn task(tid: u32) -> Arc<Task> {
    let t = Arc::new(Task::new(tid, "send", SchedClass::Normal { weight: 1024 }));
    t.pid.attach(&t);
    t
}

fn sender() -> SigSource { SigSource::User { pid: 4242, uid: 1000 } }

fn install(t: &Task, sig: u32, handler: u64) {
    let _ = t.sigactions_ref().set_action(sig as usize,
        Some(SaHandler { handler, flags: 0, restorer: 0, mask: 0 }));
}

#[test]
fn a_process_directed_send_lands_in_the_shared_set_with_the_senders_identity() {
    let t = task(700);
    assert_eq!(send::send_signal(&t, SIGTERM, sender(), SigTarget::Process), Ok(()));
    assert_ne!(t.thread_group.shared_pending() & Signum::Sigterm.bit(), 0);
    assert_eq!(t.sigpending.load(Ordering::Acquire) & Signum::Sigterm.bit(), 0,
               "kill(2) must not touch one thread's private set");
    let rec = t.dequeue_pending(SIGTERM).unwrap().expect("a record, not a bare bit");
    assert_eq!((rec.code, rec.pid, rec.uid), (signum::SI_USER, 4242, 1000));
}

#[test]
fn a_thread_directed_send_lands_in_the_private_set() {
    let t = task(701);
    assert_eq!(send::send_signal(&t, SIGTERM, sender(), SigTarget::Thread), Ok(()));
    assert_ne!(t.sigpending.load(Ordering::Acquire) & Signum::Sigterm.bit(), 0);
    assert_eq!(t.thread_group.shared_pending() & Signum::Sigterm.bit(), 0);
}

#[test]
fn a_default_ignored_signal_is_dropped_at_send_time() {
    let t = task(702);
    // SIGCHLD's default action is Ignore, so `sig_ignored` drops the send
    // outright — nothing pending, nothing queued.
    assert_eq!(send::send_signal(&t, SIGCHLD, sender(), SigTarget::Process), Ok(()));
    assert_eq!(t.pending_signals() & Signum::Sigchld.bit(), 0);
}

#[test]
fn an_explicitly_ignored_signal_is_dropped_at_send_time() {
    let t = task(703);
    install(&t, SIGTERM, SIG_IGN);
    assert_eq!(send::send_signal(&t, SIGTERM, sender(), SigTarget::Process), Ok(()));
    assert_eq!(t.pending_signals() & Signum::Sigterm.bit(), 0);
}

#[test]
fn a_kernel_generated_send_is_not_dropped_by_sig_ign() {
    let t = task(704);
    install(&t, SIGTERM, SIG_IGN);
    // `SEND_SIG_PRIV` forces past the disposition — this is why a tty hangup
    // still reaches a process that installed `signal(SIGHUP, SIG_IGN)` when the
    // kernel decides it must.
    assert_eq!(send::send_signal(&t, SIGTERM, SigSource::Kernel, SigTarget::Process), Ok(()));
    assert_ne!(t.pending_signals() & Signum::Sigterm.bit(), 0);
    let rec = t.dequeue_pending(SIGTERM).unwrap().unwrap();
    assert_eq!(rec.code, signum::SI_KERNEL);
}

#[test]
fn a_blocked_signal_is_queued_even_with_sig_ign_installed() {
    let t = task(705);
    install(&t, SIGTERM, SIG_IGN);
    t.set_current_blocked(Signum::Sigterm.bit());
    // Blocked beats ignored: `sigwait`/`signalfd` must still be able to collect
    // it, and unblocking it later must deliver it.
    assert_eq!(send::send_signal(&t, SIGTERM, sender(), SigTarget::Process), Ok(()));
    assert_ne!(t.pending_signals() & Signum::Sigterm.bit(), 0);
}

#[test]
fn a_second_standard_signal_keeps_the_first_record() {
    let t = task(706);
    let first = SigSource::User { pid: 1, uid: 0 };
    let second = SigSource::User { pid: 2, uid: 0 };
    assert_eq!(send::send_signal(&t, SIGTERM, first, SigTarget::Process), Ok(()));
    assert_eq!(send::send_signal(&t, SIGTERM, second, SigTarget::Process), Ok(()));
    let rec = t.dequeue_pending(SIGTERM).unwrap().unwrap();
    assert_eq!(rec.pid, 1, "legacy_queue keeps the FIRST record");
    assert_eq!(t.dequeue_pending(SIGTERM), None, "and only one was queued");
}

#[test]
fn real_time_signals_queue_in_arrival_order_instead_of_collapsing() {
    let t = task(707);
    for pid in 1..=3u32 {
        assert_eq!(send::send_signal(&t, SIGRTMIN, SigSource::User { pid, uid: 0 },
                                     SigTarget::Process), Ok(()));
    }
    for pid in 1..=3u32 {
        let rec = t.dequeue_pending(SIGRTMIN).unwrap().unwrap();
        assert_eq!(rec.pid, pid);
    }
}

#[test]
fn a_queued_realtime_overflow_reports_eagain_only_for_a_user_queueing_sender() {
    let t = task(708);
    let queued = |v: u64| crate::task::SigInfo {
        signo: SIGRTMIN, code: signum::SI_QUEUE, pid: 1, uid: 0, value: v,
        sys: None, fault: None,
    };
    for v in 0..crate::task::RT_QUEUE_CAP as u64 {
        assert_eq!(send::send_signal(&t, SIGRTMIN, SigSource::Info(queued(v)),
                                     SigTarget::Process), Ok(()));
    }
    assert_eq!(send::send_signal(&t, SIGRTMIN, SigSource::Info(queued(999)),
                                 SigTarget::Process), Err(send::SendErr::Again));
    // `kill(2)` of the same signal at the same depth must NOT fail — POSIX
    // forbids EAGAIN there, so the record is silently lost instead.
    assert_eq!(send::send_signal(&t, SIGRTMIN, sender(), SigTarget::Process), Ok(()));
}

#[test]
fn sigcont_flushes_a_pending_stop_and_a_stop_flushes_a_pending_sigcont() {
    let t = task(709);
    assert_eq!(send::send_signal(&t, SIGTSTP, SigSource::Kernel, SigTarget::Process), Ok(()));
    assert_ne!(t.pending_signals() & Signum::Sigtstp.bit(), 0);
    assert_eq!(send::send_signal(&t, SIGCONT, SigSource::Kernel, SigTarget::Process), Ok(()));
    assert_eq!(t.pending_signals() & crate::sigsend::STOP_MASK, 0,
               "a queued stop must not re-stop a group SIGCONT just resumed");

    let u = task(710);
    assert_eq!(send::send_signal(&u, SIGCONT, SigSource::Kernel, SigTarget::Process), Ok(()));
    assert_eq!(send::send_signal(&u, SIGTSTP, SigSource::Kernel, SigTarget::Process), Ok(()));
    assert_eq!(u.pending_signals() & Signum::Sigcont.bit(), 0);
}

// --- force_sig_fault / force_sig_info ---------------------------------------

#[test]
fn a_forced_fault_signal_queues_a_sigfault_record_on_the_faulting_thread() {
    let t = task(711);
    install(&t, SIGSEGV, HANDLER);
    let info = crate::sigsend::fault_info(SIGSEGV, hal::siginfo::code::SEGV_MAPERR,
                                          0x7fff_dead_b000, 0);
    send::force_sig_info_to_task(&t, info, ForceMode::Current);
    // PIDTYPE_PID: a synchronous condition belongs to the thread that caused it.
    assert_ne!(t.sigpending.load(Ordering::Acquire) & Signum::Sigsegv.bit(), 0);
    assert_eq!(t.thread_group.shared_pending() & Signum::Sigsegv.bit(), 0);
    let rec = t.dequeue_pending(SIGSEGV).unwrap().expect("the _sigfault record");
    assert_eq!(rec.code, hal::siginfo::code::SEGV_MAPERR);
    assert_eq!(rec.fault.unwrap().addr, 0x7fff_dead_b000);
    // The handler survives: an unblocked, un-ignored fault signal is catchable.
    assert_eq!(t.sigactions_ref().get(SIGSEGV).handler, HANDLER);
}

#[test]
fn a_forced_fault_signal_unblocks_itself_and_resets_a_blocked_handler() {
    let t = task(712);
    install(&t, SIGSEGV, HANDLER);
    t.set_current_blocked(Signum::Sigsegv.bit());
    let info = crate::sigsend::fault_info(SIGSEGV, hal::siginfo::code::SEGV_ACCERR, 0x1000, 0);
    send::force_sig_info_to_task(&t, info, ForceMode::Current);
    // Without this a process that blocked SIGSEGV would re-fault forever on the
    // same instruction instead of dying.
    assert_eq!(t.sigmask.load(Ordering::Acquire) & Signum::Sigsegv.bit(), 0);
    assert_eq!(t.sigactions_ref().get(SIGSEGV).handler, 0, "reset to SIG_DFL");
    assert_ne!(t.pending_signals() & Signum::Sigsegv.bit(), 0);
}

#[test]
fn a_forced_fault_signal_overrides_an_ignoring_disposition() {
    let t = task(713);
    install(&t, SIGSEGV, SIG_IGN);
    let info = crate::sigsend::fault_info(SIGSEGV, hal::siginfo::code::SEGV_MAPERR, 0x2000, 0);
    send::force_sig_info_to_task(&t, info, ForceMode::Current);
    assert_eq!(t.sigactions_ref().get(SIGSEGV).handler, 0);
    assert_ne!(t.pending_signals() & Signum::Sigsegv.bit(), 0);
}

#[test]
fn handler_exit_mode_strips_a_handler_that_was_neither_blocked_nor_ignored() {
    let t = task(714);
    install(&t, Signum::Sigsys as u32, HANDLER);
    let info = crate::sigsend::fault_info(Signum::Sigsys as u32, 1, 0, 0);
    send::force_sig_info_to_task(&t, info, ForceMode::Exit);
    assert_eq!(t.sigactions_ref().get(Signum::Sigsys as u32).handler, 0,
               "a seccomp KILL action is not catchable");
}

// --- SigInfo -> siginfo_t union-arm selection --------------------------------
//
// One selector serves BOTH the signal-frame builder and the syscall copy-out
// (`rt_sigtimedwait`, `waitid`). These pin the arm each record kind picks, so a
// future producer cannot quietly make a handler and a `sigwaitinfo` disagree.

#[test]
fn a_fault_record_selects_the_sigfault_arm_and_renders_si_addr() {
    let rec = crate::sigsend::fault_info(SIGSEGV, hal::siginfo::code::SEGV_ACCERR,
                                         0x7fff_0000_1000, 0);
    let mut buf = [0u8; 128];
    hal::write_siginfo(&mut buf, SIGSEGV, Some(rec.payload(SIGSEGV)));
    assert_eq!(i32::from_ne_bytes(buf[0..4].try_into().unwrap()), SIGSEGV as i32);
    assert_eq!(i32::from_ne_bytes(buf[8..12].try_into().unwrap()),
               hal::siginfo::code::SEGV_ACCERR);
    assert_eq!(u64::from_ne_bytes(buf[16..24].try_into().unwrap()), 0x7fff_0000_1000);
}

#[test]
fn a_kill_record_selects_the_rt_arm_and_renders_the_sender() {
    let rec = crate::sigsend::build_info(SIGTERM, SigSource::User { pid: 99, uid: 12 });
    let mut buf = [0u8; 128];
    hal::write_siginfo(&mut buf, SIGTERM, Some(rec.payload(SIGTERM)));
    assert_eq!(u32::from_ne_bytes(buf[16..20].try_into().unwrap()), 99);
    assert_eq!(u32::from_ne_bytes(buf[20..24].try_into().unwrap()), 12);
}

#[test]
fn a_sigchld_record_selects_the_four_byte_si_status_arm() {
    let rec = crate::task::SigInfo {
        signo: SIGCHLD, code: 1, pid: 5, uid: 0, value: u64::MAX, sys: None, fault: None,
    };
    let mut buf = [0u8; 128];
    hal::write_siginfo(&mut buf, SIGCHLD, Some(rec.payload(SIGCHLD)));
    // `_sigchld.si_status` is an int; bytes 28..32 must stay clear where an
    // `_rt` si_value's high half would be.
    assert!(buf[28..32].iter().all(|b| *b == 0));
}

// --- SIGCHLD is a PROCESS-directed signal like any other --------------------

/// A leader plus one sibling thread sharing its `ThreadGroup`, as `clone(2)`
/// with CLONE_THREAD builds them.
fn threaded(leader_tid: u32) -> (Arc<Task>, Arc<Task>) {
    let leader = task(leader_tid);
    let mut worker = Task::new(leader_tid + 1, "send-worker", SchedClass::Normal { weight: 1024 });
    worker.join_thread_group(Arc::clone(&leader.thread_group));
    let worker = Arc::new(worker);
    worker.pid.attach(&worker);
    (leader, worker)
}

/// `do_notify_parent`'s record: si_pid = child vpid, si_uid = child ruid,
/// si_status = the wait-encoded status, si_code = CLD_*.
fn child_exit(code: i32, vpid: u32, status: u64) -> crate::task::SigInfo {
    crate::task::SigInfo { signo: SIGCHLD, code, pid: vpid, uid: 0, value: status,
        sys: None, fault: None }
}

#[test]
fn a_child_event_reaches_a_sibling_thread_when_the_leader_blocks_sigchld() {
    // The divergence this closes: child events used to live in a per-THREAD
    // queue with no slot in the shared set, so a threaded supervisor whose
    // leader blocks SIGCHLD could never hand it to a worker — the shape of
    // every ordinary threaded supervisor.
    let (leader, worker) = threaded(710);
    install(&leader, SIGCHLD, HANDLER);
    leader.set_current_blocked(Signum::Sigchld.bit());
    const CLD_EXITED: i32 = 1;
    assert_eq!(send::send_signal(&leader, SIGCHLD,
        SigSource::Info(child_exit(CLD_EXITED, 4242, 7)), SigTarget::Process), Ok(()));
    assert_ne!(worker.pending_signals() & Signum::Sigchld.bit(), 0,
        "the sibling sees the child event in the shared set");
    let rec = worker.dequeue_pending(SIGCHLD).unwrap().expect("the full child record");
    assert_eq!((rec.code, rec.pid, rec.value), (CLD_EXITED, 4242, 7));
    assert_eq!(leader.pending_signals() & Signum::Sigchld.bit(), 0,
        "one consumer claims it, not both");
}

#[test]
fn a_default_disposition_parent_drops_the_child_event_at_send_time() {
    // `sig_ignored`: SIGCHLD's default action is Ignore, so an untouched parent
    // never accumulates child records. wait4 is unaffected — it reads the
    // zombie list, not this queue.
    let t = task(712);
    assert_eq!(send::send_signal(&t, SIGCHLD, SigSource::Info(child_exit(1, 9, 0)),
        SigTarget::Process), Ok(()));
    assert_eq!(t.pending_signals() & Signum::Sigchld.bit(), 0);
}

#[test]
fn a_blocked_sigchld_is_queued_even_with_the_default_disposition() {
    // What makes a `signalfd(SIGCHLD)` supervisor work: block first, and the
    // default-ignore disposition no longer drops the send.
    let t = task(714);
    t.set_current_blocked(Signum::Sigchld.bit());
    assert_eq!(send::send_signal(&t, SIGCHLD, SigSource::Info(child_exit(1, 55, 3)),
        SigTarget::Process), Ok(()));
    let rec = t.dequeue_pending(SIGCHLD).unwrap().expect("record, not a bare bit");
    assert_eq!((rec.pid, rec.value), (55, 3));
}

#[test]
fn a_burst_of_child_exits_collapses_onto_the_first_record() {
    // SIGCHLD is a standard signal, so `legacy_queue` keeps the FIRST record
    // and drops the rest — which is exactly why a supervisor must loop
    // `waitpid(-1, WNOHANG)` rather than count signals.
    let t = task(716);
    install(&t, SIGCHLD, HANDLER);
    for vpid in [11u32, 12, 13] {
        assert_eq!(send::send_signal(&t, SIGCHLD, SigSource::Info(child_exit(1, vpid, 0)),
            SigTarget::Process), Ok(()));
    }
    assert_eq!(t.dequeue_pending(SIGCHLD).unwrap().map(|r| r.pid), Some(11));
    assert_eq!(t.dequeue_pending(SIGCHLD), None, "only one record was queued");
}

// --- POSIX timer expiry from IRQ context -----------------------------------

#[test]
fn a_timer_expiry_queues_its_record_without_reserving() {
    // `send_signal_irq` is the hard-IRQ producer: the slot was reserved at
    // `timer_create`, so the expiry only pushes. A group-directed timer signal
    // is `PIDTYPE_TGID`, so it lands on the shared set where any thread can
    // take it — posting it into whichever thread the tick interrupted hid it
    // from every sibling.
    let (leader, worker) = threaded(720);
    install(&leader, SIGRTMIN, HANDLER);
    leader.thread_group.reserve_shared(SIGRTMIN);
    let rec = crate::timers::signal::timer_record(SIGRTMIN, 3, 0xfeed);
    assert!(send::send_signal_irq(&leader, rec, SigTarget::Process));
    assert_ne!(worker.pending_signals() & (1u64 << (SIGRTMIN - 1)), 0);
    let got = worker.dequeue_pending(SIGRTMIN).unwrap().expect("the _timer record");
    assert_eq!(got.code, crate::timers::signal::SI_TIMER);
    assert_eq!(crate::timers::signal::timer_id(&got), 3, "si_tid names the timer");
    assert_eq!(got.value, 0xfeed, "si_value is the sigev_value the creator registered");
}

#[test]
fn a_sigev_thread_id_expiry_stays_on_that_threads_private_set() {
    let (leader, worker) = threaded(724);
    install(&worker, SIGRTMIN, HANDLER);
    worker.sigq_reserve(SIGRTMIN);
    let rec = crate::timers::signal::timer_record(SIGRTMIN, 0, 0);
    assert!(send::send_signal_irq(&worker, rec, SigTarget::Thread));
    assert_ne!(worker.sigpending.load(Ordering::Acquire) & (1u64 << (SIGRTMIN - 1)), 0);
    assert_eq!(leader.thread_group.shared_pending() & (1u64 << (SIGRTMIN - 1)), 0,
        "SIGEV_THREAD_ID is PIDTYPE_PID — no sibling may steal it");
}

#[test]
fn an_irq_expiry_honours_the_same_ignore_ladder_as_every_other_send() {
    // The old producer set the pending bit directly, so `prepare_signal` never
    // ran for a timer expiry: a SIG_IGN disposition still woke the target.
    let t = task(728);
    install(&t, SIGRTMIN, SIG_IGN);
    t.thread_group.reserve_shared(SIGRTMIN);
    let rec = crate::timers::signal::timer_record(SIGRTMIN, 1, 0);
    assert!(!send::send_signal_irq(&t, rec, SigTarget::Process));
    assert_eq!(t.pending_signals() & (1u64 << (SIGRTMIN - 1)), 0);
}

#[test]
fn a_process_directed_send_raises_the_signalfd_readiness_edge() {
    // A signalfd's epoll subscribers hang off `Task::sigpending`, and a
    // signalfd reads `private | shared` — so a signal that becomes pending
    // ONLY on the shared set still owes every thread's source a POLLIN edge.
    // Without it a service manager parked in `epoll_wait` on its SIGCHLD
    // signalfd slept through every child exit: the fd would have read as
    // ready, but nothing ever told epoll to look.
    let (leader, worker) = threaded(730);
    install(&leader, SIGCHLD, HANDLER);
    let before = (leader.sigpending.poll_subscribers().generation(),
                  worker.sigpending.poll_subscribers().generation());
    assert_eq!(send::send_signal(&leader, SIGCHLD, SigSource::Info(child_exit(1, 9, 0)),
        SigTarget::Process), Ok(()));
    assert!(leader.sigpending.poll_subscribers().generation() > before.0);
    assert!(worker.sigpending.poll_subscribers().generation() > before.1,
        "a sibling's signalfd is watching the same shared set");
}

#[test]
fn an_irq_expiry_raises_the_readiness_edge_on_the_task_it_publishes_from() {
    let t = task(734);
    install(&t, SIGRTMIN, HANDLER);
    t.thread_group.reserve_shared(SIGRTMIN);
    let before = t.sigpending.poll_subscribers().generation();
    let rec = crate::timers::signal::timer_record(SIGRTMIN, 0, 0);
    assert!(send::send_signal_irq(&t, rec, SigTarget::Process));
    assert!(t.sigpending.poll_subscribers().generation() > before);
}
