[package]
name = "sound"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
vfs     = { path = "../vfs" }
devfs   = { path = "../devfs" }
drv     = { path = "../../drivers/drv" }
syscall = { path = "../syscall" }
sync    = { path = "../../shared/sync" }
hal     = { path = "../../arch/hal" }
pmm     = { path = "../mm-pmm" }
klog    = { path = "../../shared/klog" }
sched   = { path = "../sched" }
timekeeper = { path = "../timekeeper" }

[features]
default = []
debug-boot = []

[lints]
workspace = true
