[package]
name = "sound"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
vfs     = { path = "../vfs" }
devfs   = { path = "../devfs" }
syscall = { path = "../syscall" }
sync    = { path = "../../shared/sync" }
hal     = { path = "../../arch/hal" }
klog    = { path = "../../shared/klog" }
drv-virtio-snd = { path = "../../drivers/drv-virtio-snd" }

[features]
default = []
debug-boot = []
